const REVIEWED_REPO = "sergiiiavt/desktop-automation-lab";
const REVIEWED_BRANCH = "main";
const REVIEWED_COMMIT = "005202a18108c5b287fe98467f9dabfa93d17508";
const REVIEWED_AT = "2026-08-29";

const reviewedUrl = (path: string) =>
  `https://github.com/${REVIEWED_REPO}/blob/${REVIEWED_COMMIT}/${path}`;

const labels = {
  en: {
    actual: "Actual project block",
    source: "Reviewed source",
    what: "What happens",
    why: "Why this block exists",
    state: "State before → after",
    breakage: "What breaks if you remove or change it",
  },
  uk: {
    actual: "Реальний блок проєкту",
    source: "Перевірене джерело",
    what: "Що відбувається",
    why: "Навіщо цей блок існує",
    state: "Стан до → після",
    breakage: "Що зламається, якщо прибрати або змінити",
  },
} as const;

type WalkthroughSpec = {
  path: string;
  codeLanguage: string;
  code: string;
  what: string;
  whatUk: string;
  why: string;
  whyUk: string;
  state: string;
  stateUk: string;
  breakage: string;
  breakageUk: string;
};

function walkthroughConcept(language: "en" | "uk", spec: WalkthroughSpec) {
  const copy = labels[language];
  const localized = language === "uk";
  return [
    `### ${copy.actual}`,
    `[${copy.source}: \`${spec.path}\`](${reviewedUrl(spec.path)})`,
    `\`\`\`${spec.codeLanguage}`,
    spec.code,
    "```",
    `### ${copy.what}`,
    localized ? spec.whatUk : spec.what,
    `### ${copy.why}`,
    localized ? spec.whyUk : spec.why,
    `### ${copy.state}`,
    localized ? spec.stateUk : spec.state,
    `### ${copy.breakage}`,
    localized ? spec.breakageUk : spec.breakage,
  ].join("\n\n");
}

type LessonSpec = WalkthroughSpec & {
  id: string;
  order: number;
  title: string;
  titleUk: string;
  summary: string;
  summaryUk: string;
  keyPoints: string[];
  keyPointsUk: string[];
  pitfalls: string[];
  pitfallsUk: string[];
  exercise?: string;
  exerciseUk?: string;
  sourceIds: string[];
};

function lesson(spec: LessonSpec) {
  return {
    id: spec.id,
    moduleId: "desktop-automation-lab",
    level: "Advanced",
    order: spec.order,
    title: spec.title,
    titleUk: spec.titleUk,
    summary: spec.summary,
    summaryUk: spec.summaryUk,
    concept: walkthroughConcept("en", spec),
    conceptUk: walkthroughConcept("uk", spec),
    keyPoints: spec.keyPoints,
    keyPointsUk: spec.keyPointsUk,
    pitfalls: spec.pitfalls,
    pitfallsUk: spec.pitfallsUk,
    exercise: spec.exercise,
    exerciseUk: spec.exerciseUk,
    sourceIds: ["desktop-automation-lab-repo", ...spec.sourceIds],
  };
}

export const desktopAutomationModule = {
  id: "desktop-automation-lab",
  label: "Real project: Desktop automation",
  labelUk: "Реальний проєкт: Desktop automation",
  navLabel: "Desktop automation lab",
  navLabelUk: "Desktop automation lab",
  level: "Advanced",
  description: "Dissect a real Windows desktop automation repository block by block: pytest + pywinauto, NUnit + FlaUI/UIA3, local PowerShell execution, Allure and GitHub Actions CI/CD.",
  descriptionUk: "Розберіть реальний Windows desktop automation repository блок за блоком: pytest + pywinauto, NUnit + FlaUI/UIA3, локальний PowerShell запуск, Allure та GitHub Actions CI/CD.",
  introMarkdown: [
    "## How to use this walkthrough",
    "",
    `Every code block below is taken from **${REVIEWED_REPO}** and reviewed against commit \`${REVIEWED_COMMIT}\` (${REVIEWED_AT}). The point is not to memorize syntax. Trace what process, window, UI element, file, test runner or CI runner exists before the block and what state exists after it.`,
    "",
    "The same Notepad problem is implemented twice: Python + pytest + pywinauto and C# + NUnit + FlaUI/UIA3. That makes the repository useful for learning both desktop automation fundamentals and framework design. The final lessons then follow the exact local runner and GitHub Actions workflow through test execution, Allure aggregation and report deployment.",
    "",
    "### Study rule",
    "For each block answer five questions before moving on: **What calls this? What external system does it touch? What state does it create or change? How does the code know the action succeeded? What cleanup or failure path exists?**",
  ].join("\n"),
  introMarkdownUk: [
    "## Як проходити цей walkthrough",
    "",
    `Кожен code block нижче взятий з **${REVIEWED_REPO}** і перевірений проти commit \`${REVIEWED_COMMIT}\` (${REVIEWED_AT}). Мета не в тому, щоб запам'ятати syntax. Треба простежити, який process, window, UI element, file, test runner або CI runner існує до блоку і який state існує після нього.`,
    "",
    "Та сама задача з Notepad реалізована двічі: Python + pytest + pywinauto та C# + NUnit + FlaUI/UIA3. Тому repository зручний одночасно для вивчення desktop automation fundamentals і framework design. Фінальні lessons проходять точний local runner та GitHub Actions workflow аж до test execution, Allure aggregation і deployment report.",
    "",
    "### Правило проходження",
    "Перед переходом далі дайте відповідь на п'ять питань для кожного блоку: **Хто його викликає? З якою зовнішньою системою він працює? Який state створює або змінює? Як код розуміє, що дія успішна? Який cleanup або failure path існує?**",
  ].join("\n"),
  sourceIds: [
    "desktop-automation-lab-repo",
    "microsoft-windows-uia",
    "pywinauto-docs",
    "pytest-fixtures-docs",
    "flaui-repo",
    "nunit-lifecycle-docs",
    "github-actions-workflow-docs",
    "github-actions-contexts-docs",
    "allure-pytest-docs",
    "allure-nunit-docs",
  ],
};

export const desktopAutomationSources = [
  {
    id: "desktop-automation-lab-repo",
    title: "Desktop Automation Lab — reviewed commit",
    url: `https://github.com/${REVIEWED_REPO}/tree/${REVIEWED_COMMIT}`,
    publisher: "sergiiiavt",
    kind: "Reference implementation",
    role: "Exact source code used by every project-walkthrough lesson",
  },
  {
    id: "microsoft-windows-uia",
    title: "UI Automation Overview",
    url: "https://learn.microsoft.com/en-us/windows/win32/winauto/uiauto-uiautomationoverview",
    publisher: "Microsoft Learn",
    kind: "Official documentation",
    role: "Windows UI Automation tree, elements, control types, properties and patterns",
  },
  {
    id: "pywinauto-docs",
    title: "pywinauto documentation",
    url: "https://pywinauto.readthedocs.io/en/latest/",
    publisher: "pywinauto",
    kind: "Official documentation",
    role: "Python Windows GUI automation, UIA backend and wrappers",
  },
  {
    id: "pytest-fixtures-docs",
    title: "pytest fixtures reference",
    url: "https://docs.pytest.org/en/latest/reference/reference.html#pytest-fixture",
    publisher: "pytest",
    kind: "Official documentation",
    role: "Fixture injection, yield values and teardown semantics",
  },
  {
    id: "flaui-repo",
    title: "FlaUI",
    url: "https://github.com/FlaUI/FlaUI",
    publisher: "FlaUI",
    kind: "Official repository",
    role: "FlaUI architecture, UIA2/UIA3 backends and Windows automation elements",
  },
  {
    id: "nunit-lifecycle-docs",
    title: "NUnit SetUp and TearDown",
    url: "https://docs.nunit.org/articles/nunit/writing-tests/setup-teardown/SetUp-and-TearDown-Changes.html",
    publisher: "NUnit",
    kind: "Official documentation",
    role: "Per-test setup/teardown lifecycle and inheritance behavior",
  },
  {
    id: "github-actions-workflow-docs",
    title: "Workflow syntax for GitHub Actions",
    url: "https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-syntax",
    publisher: "GitHub Docs",
    kind: "Official documentation",
    role: "Triggers, jobs, runners, steps, actions and conditions",
  },
  {
    id: "github-actions-contexts-docs",
    title: "Contexts reference",
    url: "https://docs.github.com/en/actions/reference/workflows-and-actions/contexts",
    publisher: "GitHub Docs",
    kind: "Official documentation",
    role: "github, runner, secrets and variables contexts used by the CI workflow",
  },
  {
    id: "allure-pytest-docs",
    title: "Allure Report — Pytest",
    url: "https://allurereport.org/docs/pytest/",
    publisher: "Allure Report",
    kind: "Official documentation",
    role: "pytest result generation, attachments and Allure report workflow",
  },
  {
    id: "allure-nunit-docs",
    title: "Allure Report — NUnit",
    url: "https://allurereport.org/docs/nunit/",
    publisher: "Allure Report",
    kind: "Official documentation",
    role: "NUnit integration, result directory, metadata and attachments",
  },
];

export const desktopAutomationLessons = [
  lesson({
    id: "ta-lesson-desktop-automation-project-map",
    order: 49,
    title: "Start from the execution map, not from syntax",
    titleUk: "Починайте з execution map, а не з syntax",
    summary: "Build the mental model of the repository before opening individual helpers.",
    summaryUk: "Спочатку побудуйте mental model repository, а вже потім відкривайте окремі helpers.",
    path: "README.md",
    codeLanguage: "text",
    code: "desktop-automation-lab/\n├── flaui/Notepad.Tests/\n├── python/tests/test_notepad.py\n├── scripts/run-local.ps1\n└── .github/workflows/desktop-ui-tests.yml",
    what: "The repository has four execution layers. Test scenario code lives in Python and C#. `run-local.ps1` orchestrates both stacks on a developer machine. `desktop-ui-tests.yml` recreates the environment on a GitHub-hosted Windows runner, runs the suites, combines their Allure results and publishes artifacts/report output.",
    whatUk: "Repository має чотири execution layers. Test scenario code живе у Python і C#. `run-local.ps1` оркеструє обидва stacks на developer machine. `desktop-ui-tests.yml` відтворює environment на GitHub-hosted Windows runner, запускає suites, об'єднує їхні Allure results і публікує artifacts/report output.",
    why: "Without this map, helper functions look unrelated. The useful unit of understanding is the execution chain: runner → setup → application launch → UI Automation discovery → interaction → assertion → cleanup → reporting.",
    whyUk: "Без цієї карти helper functions виглядають не пов'язаними. Корисна одиниця розуміння — execution chain: runner → setup → application launch → UI Automation discovery → interaction → assertion → cleanup → reporting.",
    state: "Before: a repository containing files. After: a model of which layer owns test intent, framework mechanics, local orchestration and CI orchestration.",
    stateUk: "До: repository з набором файлів. Після: модель того, який layer відповідає за test intent, framework mechanics, local orchestration та CI orchestration.",
    breakage: "If you learn files in isolation, it becomes easy to confuse framework code with test behavior or to treat CI commands as unrelated shell syntax.",
    breakageUk: "Якщо вчити файли ізольовано, легко переплутати framework code з test behavior або сприймати CI commands як не пов'язаний shell syntax.",
    keyPoints: ["Trace ownership across layers.", "The same Notepad behavior is intentionally implemented in two stacks."],
    keyPointsUk: ["Простежуйте ownership між layers.", "Та сама поведінка Notepad навмисно реалізована у двох stacks."],
    pitfalls: ["Opening the largest base-class file first and trying to memorize it top-to-bottom."],
    pitfallsUk: ["Відкрити найбільший base-class file першим і намагатися запам'ятати його зверху вниз."],
    exercise: "Draw the execution chain from `dotnet test` or `pytest` to the final saved text file and screenshot before reading the next lesson.",
    exerciseUk: "Намалюйте execution chain від `dotnet test` або `pytest` до фінального saved text file і screenshot перед наступним lesson.",
    sourceIds: [],
  }),
  lesson({
    id: "ta-lesson-desktop-automation-python-dependencies",
    order: 50,
    title: "Python dependencies: what each package contributes",
    titleUk: "Python dependencies: роль кожного package",
    summary: "Read `requirements.txt` as the boundary of the Python automation stack.",
    summaryUk: "Читайте `requirements.txt` як boundary Python automation stack.",
    path: "python/requirements.txt",
    codeLanguage: "text",
    code: "pywinauto==0.6.9\npytest==8.4.1\nPillow==11.3.0\nallure-pytest==2.16.0\npyperclip==1.9.0",
    what: "`pytest` discovers and executes tests and fixtures. `pywinauto` connects Python to Windows GUI automation through the UIA backend. `pyperclip` provides deterministic clipboard text input. Pillow is used by screenshot/image handling, and `allure-pytest` writes structured Allure result files and attachments.",
    whatUk: "`pytest` знаходить і запускає tests та fixtures. `pywinauto` з'єднує Python із Windows GUI automation через UIA backend. `pyperclip` дає deterministic clipboard text input. Pillow використовується для screenshot/image handling, а `allure-pytest` записує structured Allure result files та attachments.",
    why: "Pinned versions make a small lab reproducible. Desktop automation is sensitive to library and platform differences, so a known dependency set reduces one source of unexplained behavior.",
    whyUk: "Pinned versions роблять невеликий lab відтворюваним. Desktop automation чутлива до library і platform differences, тому known dependency set прибирає одне джерело незрозумілої поведінки.",
    state: "Before installation: Python cannot import the automation/test/reporting libraries. After installation: the interpreter has the exact packages required by the project.",
    stateUk: "До installation: Python не може import automation/test/reporting libraries. Після: interpreter має точні packages, потрібні проєкту.",
    breakage: "Removing pytest removes the runner; removing pywinauto removes GUI access; removing pyperclip breaks the layout-independent input strategy; removing Allure integration removes Python report results.",
    breakageUk: "Видалення pytest прибере runner; pywinauto — GUI access; pyperclip зламає layout-independent input strategy; Allure integration прибере Python report results.",
    keyPoints: ["Dependencies describe responsibilities, not just installation commands.", "Pinned versions improve reproducibility."],
    keyPointsUk: ["Dependencies описують responsibilities, а не лише installation commands.", "Pinned versions покращують reproducibility."],
    pitfalls: ["Assuming Pillow is a test runner dependency just because it is in the same file."],
    pitfallsUk: ["Вважати Pillow test-runner dependency лише тому, що він у тому самому файлі."],
    exercise: "For each dependency, identify the exact import or runtime feature in `test_notepad.py` that would fail without it.",
    exerciseUk: "Для кожної dependency знайдіть exact import або runtime feature у `test_notepad.py`, який зламається без неї.",
    sourceIds: ["pywinauto-docs", "pytest-fixtures-docs", "allure-pytest-docs"],
  }),
  lesson({
    id: "ta-lesson-desktop-automation-pytest-fixture",
    order: 51,
    title: "pytest fixture: setup, yield and guaranteed cleanup",
    titleUk: "pytest fixture: setup, yield і гарантований cleanup",
    summary: "Follow the `notepad` fixture as the lifecycle owner of one test document.",
    summaryUk: "Простежте `notepad` fixture як lifecycle owner одного test document.",
    path: "python/tests/test_notepad.py",
    codeLanguage: "python",
    code: "@pytest.fixture\ndef notepad(request):\n    window = None\n    temp_path = None\n\n    try:\n        with tempfile.NamedTemporaryFile(\n            prefix=\"desktop-automation-\",\n            suffix=\".txt\",\n            delete=False,\n        ) as temp_file:\n            temp_path = Path(temp_file.name)\n\n        subprocess.Popen([\"notepad.exe\", str(temp_path)])\n        desktop = Desktop(backend=\"uia\")\n        window = find_window_for_file(desktop, temp_path.name, timeout=15)\n        yield window, temp_path\n    finally:\n        if window is not None and temp_path is not None:\n            close_test_tab(window, temp_path.name)\n        if temp_path is not None:\n            temp_path.unlink(missing_ok=True)",
    what: "pytest sees the test parameter named `notepad`, calls this fixture first, creates a unique temporary text file, launches Notepad with that file, obtains a UI Automation desktop connection, finds the matching window and pauses the fixture at `yield`. The tuple becomes the test argument. When the test ends—pass or fail—execution returns after `yield` and enters `finally` for cleanup.",
    whatUk: "pytest бачить test parameter `notepad`, спочатку викликає fixture, створює unique temporary text file, запускає Notepad з цим file, отримує UI Automation desktop connection, знаходить matching window і зупиняє fixture на `yield`. Tuple стає test argument. Коли test завершується — pass або fail — execution повертається після `yield` і входить у `finally` для cleanup.",
    why: "The fixture makes resource ownership explicit: one test gets one unique document and the same fixture that creates it is responsible for closing and deleting it.",
    whyUk: "Fixture робить resource ownership явним: один test отримує один unique document, а той самий fixture, який його створив, відповідає за close і delete.",
    state: "Before setup: no test document/window. At `yield`: a known file is open and a window wrapper is available. After teardown: the test tab is closed and the temporary file is removed.",
    stateUk: "До setup: немає test document/window. На `yield`: known file відкритий і доступний window wrapper. Після teardown: test tab закритий, temporary file видалений.",
    breakage: "Replacing `yield` with `return` would skip the post-yield teardown path. Removing `finally` would leak files/tabs when an assertion or helper fails.",
    breakageUk: "Заміна `yield` на `return` прибере post-yield teardown path. Видалення `finally` залишить files/tabs після assertion або helper failure.",
    keyPoints: ["Fixture injection is dependency injection performed by pytest.", "`yield` divides setup from teardown."],
    keyPointsUk: ["Fixture injection — це dependency injection, яку виконує pytest.", "`yield` розділяє setup і teardown."],
    pitfalls: ["Thinking code after `yield` only runs after successful tests."],
    pitfallsUk: ["Думати, що code після `yield` виконується лише після successful tests."],
    exercise: "Force the final assertion to fail mentally and trace exactly which lines in the fixture still execute.",
    exerciseUk: "Уявно зламайте final assertion і простежте, які саме lines у fixture все одно виконаються.",
    sourceIds: ["pytest-fixtures-docs", "pywinauto-docs"],
  }),
  lesson({
    id: "ta-lesson-desktop-automation-window-discovery",
    order: 52,
    title: "Find the correct Notepad window by test identity",
    titleUk: "Знайдіть правильне Notepad window за test identity",
    summary: "Understand why the project searches UI windows for the unique filename instead of trusting the launcher PID.",
    summaryUk: "Зрозумійте, чому проєкт шукає UI windows за unique filename замість довіри до launcher PID.",
    path: "python/tests/test_notepad.py",
    codeLanguage: "python",
    code: "def find_window_for_file(desktop, file_name: str, timeout: float):\n    deadline = time.monotonic() + timeout\n    last_titles = []\n\n    while time.monotonic() < deadline:\n        last_titles = []\n        for candidate in desktop.windows(control_type=\"Window\"):\n            try:\n                title = candidate.window_text()\n                last_titles.append(title)\n                if file_name.lower() in title.lower():\n                    return desktop.window(handle=candidate.handle)\n            except Exception:\n                continue\n        time.sleep(0.25)\n\n    raise RuntimeError(\n        f\"Could not find Notepad window for '{file_name}'. \"\n        f\"Top-level windows seen: {last_titles}\"\n    )",
    what: "The helper creates a monotonic deadline, repeatedly enumerates top-level UIA `Window` controls, reads their titles and returns a wrapper for the first title containing the unique test filename. Windows that disappear or become inaccessible while being enumerated are ignored and the search continues until timeout.",
    whatUk: "Helper створює monotonic deadline, повторно enumerates top-level UIA `Window` controls, читає їх titles і повертає wrapper першого title, що містить unique test filename. Windows, які зникають або стають недоступними під час enumeration, ігноруються, а search триває до timeout.",
    why: "Modern Notepad can reuse an existing process/window and open documents as tabs. The process returned by `subprocess.Popen` is therefore not a reliable identity for the final visible test document; the unique filename is.",
    whyUk: "Modern Notepad може reuse existing process/window і відкривати documents як tabs. Тому process від `subprocess.Popen` не є надійною identity для final visible test document; unique filename є.",
    state: "Before: Notepad was launched, but the test does not yet own a UI wrapper. After: the test has the top-level window that contains its uniquely named document.",
    stateUk: "До: Notepad запущений, але test ще не має UI wrapper. Після: test має top-level window, що містить його uniquely named document.",
    breakage: "Attaching to the first Notepad process/window can drive a user's unrelated tab or another parallel test. Removing the timeout can hang indefinitely when the UI never appears.",
    breakageUk: "Attach до першого Notepad process/window може керувати стороннім user tab або іншим test. Видалення timeout може повісити execution назавжди, якщо UI не з'явиться.",
    keyPoints: ["UI identity and process identity are not always the same.", "`time.monotonic()` is appropriate for timeout measurement."],
    keyPointsUk: ["UI identity і process identity не завжди однакові.", "`time.monotonic()` підходить для вимірювання timeout."],
    pitfalls: ["Assuming `Popen(...).pid` must be the process owning the final modern Notepad tab."],
    pitfallsUk: ["Припускати, що `Popen(...).pid` обов'язково є process, який володіє final modern Notepad tab."],
    exercise: "Explain what could happen if another Notepad window is already open before the test starts.",
    exerciseUk: "Поясніть, що може статись, якщо інше Notepad window вже відкрите до старту test.",
    sourceIds: ["microsoft-windows-uia", "pywinauto-docs"],
  }),
  lesson({
    id: "ta-lesson-desktop-automation-editor-locator",
    order: 53,
    title: "Locate the editor across different Notepad UI trees",
    titleUk: "Знайдіть editor у різних Notepad UI trees",
    summary: "See how the project handles `Document` and `Edit` controls without a brittle single-version locator.",
    summaryUk: "Подивіться, як проєкт підтримує `Document` і `Edit` controls без brittle locator для однієї version.",
    path: "python/tests/test_notepad.py",
    codeLanguage: "python",
    code: "def find_editor(window):\n    root = window.wrapper_object()\n\n    for control_type in (\"Document\", \"Edit\"):\n        candidates = []\n        for candidate in root.descendants(control_type=control_type):\n            try:\n                rect = candidate.rectangle()\n                if (\n                    candidate.is_visible()\n                    and candidate.is_enabled()\n                    and rect.width() > 0\n                    and rect.height() > 0\n                ):\n                    candidates.append(candidate)\n            except Exception:\n                continue\n\n        if candidates:\n            return max(\n                candidates,\n                key=lambda item: item.rectangle().width() * item.rectangle().height(),\n            )",
    what: "The window wrapper becomes the search root. The helper first looks for visible, enabled `Document` descendants; if none are usable it tries `Edit`. It filters zero-size/inactive candidates and chooses the candidate with the largest rectangle area, which is expected to be the actual text editing surface rather than a small incidental edit control.",
    whatUk: "Window wrapper стає search root. Helper спочатку шукає visible, enabled `Document` descendants; якщо usable element немає — пробує `Edit`. Він фільтрує zero-size/inactive candidates і вибирає candidate з найбільшою rectangle area, що очікувано є actual text editing surface, а не малим incidental edit control.",
    why: "Windows application versions can expose different UI Automation trees. The fallback is deliberate compatibility logic, while the visibility/size checks reduce accidental matches.",
    whyUk: "Різні versions Windows application можуть expose різні UI Automation trees. Fallback — свідома compatibility logic, а visibility/size checks зменшують accidental matches.",
    state: "Before: the test owns only a top-level Notepad window. After: it owns a wrapper for the interactive text editor control.",
    stateUk: "До: test володіє лише top-level Notepad window. Після: він має wrapper interactive text editor control.",
    breakage: "Hard-coding only `Document` or only `Edit` can fail on another Notepad build. Returning the first descendant without filtering can select the wrong control.",
    breakageUk: "Hard-code лише `Document` або лише `Edit` може впасти на іншому Notepad build. Повернення first descendant без filtering може вибрати wrong control.",
    keyPoints: ["ControlType is one UIA locator dimension, not a complete identity.", "Compatibility fallbacks should be intentional and observable."],
    keyPointsUk: ["ControlType — лише один UIA locator dimension, а не повна identity.", "Compatibility fallbacks мають бути intentional та observable."],
    pitfalls: ["Using broad descendant search without checking whether the result is actually interactive and visible."],
    pitfallsUk: ["Використовувати broad descendant search без перевірки, що result справді interactive та visible."],
    exercise: "If the UI tree contains two visible `Edit` controls sized 100×20 and 1000×700, calculate which one this locator returns and why.",
    exerciseUk: "Якщо UI tree має два visible `Edit` controls розміром 100×20 і 1000×700, визначте, який поверне locator і чому.",
    sourceIds: ["microsoft-windows-uia", "pywinauto-docs"],
  }),
  lesson({
    id: "ta-lesson-desktop-automation-clipboard-input",
    order: 54,
    title: "Deterministic text input through the Windows clipboard",
    titleUk: "Deterministic text input через Windows clipboard",
    summary: "Understand why arbitrary text is pasted while control shortcuts remain real keyboard input.",
    summaryUk: "Зрозумійте, чому arbitrary text вставляється через clipboard, а control shortcuts залишаються real keyboard input.",
    path: "python/tests/test_notepad.py",
    codeLanguage: "python",
    code: "def set_text(editor, text: str) -> None:\n    previous_clipboard_text = \"\"\n    try:\n        previous_clipboard_text = pyperclip.paste()\n    except pyperclip.PyperclipException:\n        pass\n\n    editor.set_focus()\n    editor.type_keys(\"^a\")\n    pyperclip.copy(text)\n    editor.type_keys(\"^v\")\n\n    wait_until(\n        lambda: read_text(editor) == text,\n        timeout=3,\n        failure=f\"Editor did not become exactly {text!r}\",\n    )",
    what: "The helper saves the current clipboard when possible, focuses the editor, selects existing content with Ctrl+A, places the exact target string into the Windows clipboard and pastes it with Ctrl+V. It then polls the editor until UI Automation reports the expected value before continuing.",
    whatUk: "Helper по можливості зберігає current clipboard, фокусує editor, виділяє existing content через Ctrl+A, кладе exact target string у Windows clipboard і вставляє Ctrl+V. Потім він polls editor, доки UI Automation не поверне expected value.",
    why: "Simulated character typing depends on the active keyboard layout. Pasting exact text avoids a Ukrainian/English layout turning intended Latin characters into different glyphs, while shortcuts such as Ctrl+A/S/V still represent real user interactions.",
    whyUk: "Simulated character typing залежить від active keyboard layout. Paste exact text не дозволяє Ukrainian/English layout перетворити потрібні Latin characters на інші symbols, тоді як Ctrl+A/S/V залишаються реальними user interactions.",
    state: "Before: editor text may be anything and clipboard has user state. After: editor equals the requested string and the helper later restores the previous clipboard when possible.",
    stateUk: "До: editor text може бути будь-яким, clipboard містить user state. Після: editor дорівнює requested string, а helper потім відновлює previous clipboard, якщо це можливо.",
    breakage: "Typing the string with `type_keys(text)` can make the test depend on keyboard layout. Omitting the post-paste check creates a race where the assertion/save can run before the UI reflects the paste.",
    breakageUk: "Typing string через `type_keys(text)` може зробити test залежним від keyboard layout. Без post-paste check assertion/save може стартувати до того, як UI відобразить paste.",
    keyPoints: ["Determinism sometimes requires separating text data from keyboard gestures.", "A UI action is not complete until an observable condition confirms it."],
    keyPointsUk: ["Determinism іноді потребує відокремити text data від keyboard gestures.", "UI action не завершена, поки observable condition її не підтвердить."],
    pitfalls: ["Treating fixed sleeps as proof that paste completed."],
    pitfallsUk: ["Сприймати fixed sleep як доказ, що paste завершився."],
    exercise: "Explain why Ctrl+V is safe to simulate under a Ukrainian layout while typing the letters in `Hello` may not be.",
    exerciseUk: "Поясніть, чому Ctrl+V безпечно simulate під Ukrainian layout, а typing letters у `Hello` може бути небезпечним.",
    sourceIds: ["pywinauto-docs", "microsoft-windows-uia"],
  }),
  lesson({
    id: "ta-lesson-desktop-automation-uia-pattern-read",
    order: 55,
    title: "Read text through UI Automation patterns",
    titleUk: "Читайте text через UI Automation patterns",
    summary: "Learn why the code has a ValuePattern/TextPattern fallback instead of reading screen pixels.",
    summaryUk: "Зрозумійте, чому code має ValuePattern/TextPattern fallback замість читання screen pixels.",
    path: "python/tests/test_notepad.py",
    codeLanguage: "python",
    code: "def read_text(editor) -> str:\n    try:\n        value = editor.iface_value.CurrentValue\n    except (NoPatternInterfaceError, AttributeError):\n        value = editor.iface_text.DocumentRange.GetText(-1)\n    return value.rstrip(\"\\r\\n\")",
    what: "The helper first asks the editor for UIA ValuePattern's current value. If that pattern is not exposed by this control/version, it falls back to TextPattern and reads the entire document range. Trailing CR/LF characters are normalized away before equality assertions.",
    whatUk: "Helper спочатку запитує current value через UIA ValuePattern. Якщо цей pattern не expose-иться control/version, він fallback-иться на TextPattern і читає весь document range. Trailing CR/LF нормалізуються перед equality assertions.",
    why: "UI Automation patterns expose semantic control capabilities. Reading through those patterns is more robust and meaningful than OCR or pixel inspection for a text editor.",
    whyUk: "UI Automation patterns expose semantic capabilities control. Читання через patterns надійніше й змістовніше за OCR або pixel inspection для text editor.",
    state: "Before: the test has an editor wrapper. After: it has a normalized Python string representing the editor's current semantic text value.",
    stateUk: "До: test має editor wrapper. Після: він має normalized Python string, що представляє current semantic text value editor.",
    breakage: "Assuming every editor supports the same UIA pattern can break across application versions. Comparing raw text without newline normalization can create false failures.",
    breakageUk: "Припущення, що кожен editor підтримує той самий UIA pattern, може зламатися між versions. Compare raw text без newline normalization може створювати false failures.",
    keyPoints: ["UIA patterns describe supported behavior, not visual appearance.", "Fallbacks should correspond to genuine platform variation."],
    keyPointsUk: ["UIA patterns описують supported behavior, а не visual appearance.", "Fallbacks мають відповідати реальній platform variation."],
    pitfalls: ["Catching every exception and silently returning an empty string."],
    pitfallsUk: ["Catch усіх exceptions із тихим return empty string."],
    exercise: "Describe the difference between a UIA control type and a UIA control pattern using this editor as the example.",
    exerciseUk: "Опишіть різницю між UIA control type і UIA control pattern на прикладі цього editor.",
    sourceIds: ["microsoft-windows-uia", "pywinauto-docs"],
  }),
  lesson({
    id: "ta-lesson-desktop-automation-polling",
    order: 56,
    title: "Synchronization: poll observable state instead of sleeping blindly",
    titleUk: "Synchronization: poll observable state замість blind sleep",
    summary: "Dissect the generic polling helper used for UI and file-system state changes.",
    summaryUk: "Розберіть generic polling helper для UI та file-system state changes.",
    path: "python/tests/test_notepad.py",
    codeLanguage: "python",
    code: "def wait_until(condition, timeout: float, failure: str, interval: float = 0.1) -> None:\n    deadline = time.monotonic() + timeout\n    last_error = None\n\n    while time.monotonic() < deadline:\n        try:\n            if condition():\n                return\n        except Exception as exc:\n            last_error = exc\n        time.sleep(interval)\n\n    suffix = f\" Last error: {last_error}\" if last_error else \"\"\n    raise AssertionError(f\"{failure}.{suffix}\")",
    what: "The caller supplies a condition function. `wait_until` evaluates it repeatedly until true or timeout, tolerating transient exceptions and remembering the latest one for diagnostics. A successful condition returns immediately; the test does not wait for the full timeout.",
    whatUk: "Caller передає condition function. `wait_until` перевіряє її повторно до true або timeout, допускає transient exceptions і зберігає latest one для diagnostics. Successful condition завершує wait одразу; test не чекає весь timeout.",
    why: "Desktop UI and file writes are asynchronous from the test's point of view. Polling a meaningful post-condition reduces both flakiness and wasted time compared with arbitrary multi-second sleeps.",
    whyUk: "Desktop UI та file writes є asynchronous з точки зору test. Poll meaningful post-condition зменшує flakiness і wasted time порівняно з arbitrary multi-second sleeps.",
    state: "Before: the desired condition may still be false. After: either the condition has actually become true, or the helper fails with a bounded timeout and useful diagnostic context.",
    stateUk: "До: desired condition може бути false. Після: condition реально стала true або helper падає за bounded timeout з корисним diagnostic context.",
    breakage: "Replacing polling with `sleep(5)` makes fast operations unnecessarily slow and slow operations still flaky. Removing the timeout can hang the suite forever.",
    breakageUk: "Заміна polling на `sleep(5)` робить fast operations зайво повільними, а slow operations все одно flaky. Без timeout suite може зависнути назавжди.",
    keyPoints: ["Wait for state, not time.", "Timeouts convert indefinite hangs into diagnosable failures."],
    keyPointsUk: ["Чекайте state, а не time.", "Timeout перетворює indefinite hang на diagnosable failure."],
    pitfalls: ["Polling a condition that itself changes the application state."],
    pitfallsUk: ["Polling condition, яка сама змінює application state."],
    exercise: "Compare a 5-second fixed sleep with a 5-second timeout polling every 100 ms when the condition becomes true after 300 ms.",
    exerciseUk: "Порівняйте fixed sleep 5 секунд із timeout 5 секунд і polling кожні 100 ms, якщо condition стає true через 300 ms.",
    sourceIds: ["pytest-fixtures-docs"],
  }),
  lesson({
    id: "ta-lesson-desktop-automation-python-test-flow",
    order: 57,
    title: "The complete Python scenario: UI assertion plus file assertion",
    titleUk: "Повний Python scenario: UI assertion плюс file assertion",
    summary: "Trace the user-visible action and the persisted-state verification in one test.",
    summaryUk: "Простежте user-visible action та persisted-state verification в одному test.",
    path: "python/tests/test_notepad.py",
    codeLanguage: "python",
    code: "@allure.feature(\"Notepad desktop automation\")\n@allure.title(\"Can type, read and save text in Notepad\")\ndef test_can_type_read_and_save_text(notepad, request):\n    window, temp_path = notepad\n    test_name = request.node.name\n\n    with allure.step(\"Open the exact Notepad test tab\"):\n        activate_file_tab(window, temp_path.name, timeout=3)\n        capture_window(window, test_name, \"00-opened\")\n        editor = find_editor(window)\n\n    with allure.step(\"Paste layout-independent text into Notepad\"):\n        set_text(editor, TEXT)\n        capture_window(window, test_name, \"01-text-entered\")\n        assert read_text(editor) == TEXT\n\n    with allure.step(\"Save with Ctrl+S and verify exact file contents\"):\n        editor.set_focus()\n        editor.type_keys(\"^s\")\n        wait_for_saved_text(temp_path, TEXT)\n        capture_window(window, test_name, \"02-saved\")\n        assert temp_path.read_text(encoding=\"utf-8\") == TEXT",
    what: "pytest injects the fixture result, then the test activates the exact tab and locates its editor. The second step changes UI state and verifies the semantic editor value. The third sends Ctrl+S, waits for persisted disk state and independently reads the temporary file for an exact assertion. Screenshots are attached around meaningful state transitions.",
    whatUk: "pytest inject-ить fixture result, після чого test активує exact tab і знаходить editor. Другий step змінює UI state і перевіряє semantic editor value. Третій відправляє Ctrl+S, чекає persisted disk state і незалежно читає temporary file для exact assertion. Screenshots attach-яться біля meaningful state transitions.",
    why: "A desktop test should not stop at 'the UI looks right'. This scenario verifies both the application-facing state (text control) and the externally persisted result (file contents), so it detects failures in either editing or saving.",
    whyUk: "Desktop test не має зупинятися на 'UI виглядає правильно'. Scenario перевіряє application-facing state (text control) і externally persisted result (file contents), тому ловить failures як editing, так і saving.",
    state: "Before: unique empty document. After: editor contains exact text, the file on disk contains the same text, screenshots and Allure step data exist, and fixture teardown can safely clean the document.",
    stateUk: "До: unique empty document. Після: editor містить exact text, file на disk містить той самий text, існують screenshots і Allure step data, а fixture teardown може cleanup document.",
    breakage: "Removing the file assertion would allow a broken Save operation to pass. Removing the UI assertion would make it harder to distinguish input failure from persistence failure.",
    breakageUk: "Без file assertion broken Save operation може пройти. Без UI assertion складніше відрізнити input failure від persistence failure.",
    keyPoints: ["Assert at meaningful boundaries.", "Allure steps organize evidence but do not replace assertions."],
    keyPointsUk: ["Робіть assertions на meaningful boundaries.", "Allure steps організовують evidence, але не замінюють assertions."],
    pitfalls: ["Treating screenshots as the assertion instead of machine-readable state."],
    pitfallsUk: ["Сприймати screenshots як assertion замість machine-readable state."],
    exercise: "Classify each line in the test as arrange/setup, action, synchronization, evidence capture or assertion.",
    exerciseUk: "Класифікуйте кожен line test як arrange/setup, action, synchronization, evidence capture або assertion.",
    sourceIds: ["pytest-fixtures-docs", "allure-pytest-docs", "pywinauto-docs"],
  }),
  lesson({
    id: "ta-lesson-desktop-automation-csharp-project",
    order: 58,
    title: "The .NET test project file is executable configuration",
    titleUk: ".NET test project file — це executable configuration",
    summary: "Read the `.csproj` as the declaration that makes NUnit, FlaUI and Windows APIs available.",
    summaryUk: "Читайте `.csproj` як declaration, що робить NUnit, FlaUI та Windows APIs доступними.",
    path: "flaui/Notepad.Tests/Notepad.Tests.csproj",
    codeLanguage: "xml",
    code: "<PropertyGroup>\n  <TargetFramework>net8.0-windows</TargetFramework>\n  <ImplicitUsings>enable</ImplicitUsings>\n  <Nullable>enable</Nullable>\n  <IsTestProject>true</IsTestProject>\n  <UseWindowsForms>true</UseWindowsForms>\n</PropertyGroup>\n\n<ItemGroup>\n  <PackageReference Include=\"Allure.NUnit\" Version=\"2.15.0\" />\n  <PackageReference Include=\"FlaUI.Core\" Version=\"5.0.0\" />\n  <PackageReference Include=\"FlaUI.UIA3\" Version=\"5.0.0\" />\n  <PackageReference Include=\"Microsoft.NET.Test.Sdk\" Version=\"18.9.0\" />\n  <PackageReference Include=\"NUnit\" Version=\"4.6.1\" />\n  <PackageReference Include=\"NUnit3TestAdapter\" Version=\"6.3.0\" />\n</ItemGroup>",
    what: "MSBuild reads this file before compilation. The Windows target framework enables Windows-specific APIs, `IsTestProject` marks the project as tests, Windows Forms support is needed for clipboard/input-language helpers, and the package references provide the test SDK/adapter, NUnit API, FlaUI core/UIA3 implementation and Allure integration.",
    whatUk: "MSBuild читає цей file до compilation. Windows target framework вмикає Windows-specific APIs, `IsTestProject` позначає project як tests, Windows Forms support потрібен для clipboard/input-language helpers, а package references дають test SDK/adapter, NUnit API, FlaUI core/UIA3 implementation та Allure integration.",
    why: "Unlike Python's `requirements.txt`, the project file also controls compilation/runtime features. It is both dependency declaration and build configuration.",
    whyUk: "На відміну від Python `requirements.txt`, project file також керує compilation/runtime features. Це одночасно dependency declaration і build configuration.",
    state: "Before restore/build: source files reference unknown packages. After restore and build: the .NET test assembly can compile and `dotnet test` can discover it through the test SDK/adapter.",
    stateUk: "До restore/build: source files посилаються на unknown packages. Після restore і build: .NET test assembly компілюється, а `dotnet test` знаходить його через test SDK/adapter.",
    breakage: "Removing `NUnit3TestAdapter` or the test SDK can make tests undiscoverable; removing FlaUI.UIA3 removes the backend implementation; removing Windows Forms breaks clipboard helpers used by the base class.",
    breakageUk: "Без `NUnit3TestAdapter` або test SDK tests можуть не discover-итись; без FlaUI.UIA3 зникає backend implementation; без Windows Forms ламаються clipboard helpers base class.",
    keyPoints: ["A `.csproj` controls more than packages.", "Runner discovery depends on the test SDK/adapter as well as NUnit itself."],
    keyPointsUk: ["`.csproj` керує не лише packages.", "Runner discovery залежить від test SDK/adapter, а не лише від NUnit."],
    pitfalls: ["Assuming `NUnit` package alone is sufficient for `dotnet test` discovery."],
    pitfallsUk: ["Вважати, що package `NUnit` сам по собі достатній для `dotnet test` discovery."],
    exercise: "Separate the shown XML lines into build/runtime settings, test-runner integration and test-library dependencies.",
    exerciseUk: "Розділіть показані XML lines на build/runtime settings, test-runner integration та test-library dependencies.",
    sourceIds: ["flaui-repo", "nunit-lifecycle-docs", "allure-nunit-docs"],
  }),
  lesson({
    id: "ta-lesson-desktop-automation-nunit-setup",
    order: 59,
    title: "NUnit BaseSetUp: create the per-test application state",
    titleUk: "NUnit BaseSetUp: створення per-test application state",
    summary: "Compare the C# lifecycle with the pytest fixture you already traced.",
    summaryUk: "Порівняйте C# lifecycle з pytest fixture, який ви вже розібрали.",
    path: "flaui/Notepad.Tests/NotepadTestBase.cs",
    codeLanguage: "csharp",
    code: "[SetUp]\npublic void BaseSetUp()\n{\n    _automation = new UIA3Automation();\n    _tempFilePath = Path.Combine(\n        Path.GetTempPath(),\n        $\"{TempFilePrefix}{Guid.NewGuid():N}.txt\");\n    File.WriteAllText(_tempFilePath, InitialText);\n\n    Process.Start(new ProcessStartInfo\n    {\n        FileName = \"notepad.exe\",\n        Arguments = $\"\\\"{_tempFilePath}\\\"\",\n        UseShellExecute = true\n    })?.Dispose();\n\n    var expectedFileName = Path.GetFileName(_tempFilePath);\n    var windowResult = Retry.WhileNull(\n        () => FindNotepadWindow(_automation, expectedFileName),\n        timeout: TimeSpan.FromSeconds(15),\n        interval: TimeSpan.FromMilliseconds(250),\n        ignoreException: true);\n\n    _window = windowResult.Result;\n    _notepadProcessId = _window.Properties.ProcessId.Value;\n}",
    what: "Before each NUnit test, the base class creates a UIA3 automation client, generates a GUID-based temporary filename, writes initial content, launches Notepad, then uses FlaUI's retry helper to locate the window containing that filename. The discovered window and process ID are stored in instance fields for the scenario and later teardown.",
    whatUk: "Перед кожним NUnit test base class створює UIA3 automation client, генерує GUID-based temporary filename, записує initial content, запускає Notepad, а потім через FlaUI retry helper знаходить window з цим filename. Discovered window і process ID зберігаються в instance fields для scenario і teardown.",
    why: "This is the C# equivalent of fixture setup: scenario tests inherit a prepared, isolated Notepad document without duplicating lifecycle mechanics.",
    whyUk: "Це C# еквівалент fixture setup: scenario tests успадковують prepared, isolated Notepad document без дублювання lifecycle mechanics.",
    state: "Before `[SetUp]`: no UIA client or test file. After: the base object owns UI automation, a unique file, a discovered Notepad window and its current process ID.",
    stateUk: "До `[SetUp]`: немає UIA client або test file. Після: base object володіє UI automation, unique file, discovered Notepad window і його current process ID.",
    breakage: "If the window search is removed and code relies only on `Process.Start`, modern Notepad process/tab reuse can associate the test with the wrong UI object.",
    breakageUk: "Якщо прибрати window search і покластися лише на `Process.Start`, modern Notepad process/tab reuse може зв'язати test з wrong UI object.",
    keyPoints: ["NUnit `[SetUp]` and pytest fixture setup solve the same lifecycle problem differently.", "GUID filenames create test identity."],
    keyPointsUk: ["NUnit `[SetUp]` і pytest fixture setup вирішують ту саму lifecycle problem по-різному.", "GUID filenames створюють test identity."],
    pitfalls: ["Treating process creation as proof that the expected UI is ready."],
    pitfallsUk: ["Сприймати process creation як доказ, що expected UI вже ready."],
    exercise: "Map every C# setup line to its closest Python fixture equivalent.",
    exerciseUk: "Зіставте кожен C# setup line з найближчим equivalent у Python fixture.",
    sourceIds: ["flaui-repo", "nunit-lifecycle-docs", "microsoft-windows-uia"],
  }),
  lesson({
    id: "ta-lesson-desktop-automation-nunit-teardown",
    order: 60,
    title: "NUnit BaseTearDown: clean only what the test owns",
    titleUk: "NUnit BaseTearDown: cleanup лише того, чим володіє test",
    summary: "Study defensive cleanup in a shared desktop application that may contain unrelated tabs.",
    summaryUk: "Вивчіть defensive cleanup у shared desktop application, де можуть бути unrelated tabs.",
    path: "flaui/Notepad.Tests/NotepadTestBase.cs",
    codeLanguage: "csharp",
    code: "[TearDown]\npublic void BaseTearDown()\n{\n    var testDocumentClosed = false;\n\n    try\n    {\n        CaptureWindow(\"99-final\");\n        BeforeClosingTestDocument();\n\n        if (_window is not null)\n        {\n            var editor = FindEditor(_window);\n            editor.Focus();\n            Keyboard.TypeSimultaneously(VirtualKeyShort.CONTROL, VirtualKeyShort.KEY_W);\n            Thread.Sleep(250);\n            TryDiscardUnsavedChanges();\n            testDocumentClosed = WaitUntilTestFileIsNoLongerOpen(TimeSpan.FromSeconds(3));\n        }\n    }\n    finally\n    {\n        if (_tempFilePath is not null && (testDocumentClosed || !IsTestFileOpen()))\n        {\n            File.Delete(_tempFilePath);\n        }\n        _automation?.Dispose();\n    }\n}",
    what: "After each test, NUnit invokes teardown inherited from the base class. It captures final evidence, gives specialized tests a hook, focuses the test editor and sends Ctrl+W to close that document/tab rather than killing all Notepad. If an unsaved-changes dialog appears it tries to discard it, waits until the unique file is no longer open, then deletes only that temporary file and disposes UIA resources.",
    whatUk: "Після кожного test NUnit викликає teardown, успадкований від base class. Він capture-ить final evidence, дає specialized tests hook, фокусує test editor і відправляє Ctrl+W, щоб закрити саме document/tab, а не весь Notepad. Якщо з'являється unsaved-changes dialog, код намагається discard, чекає поки unique file більше не open, потім delete лише цей temporary file і dispose UIA resources.",
    why: "Desktop tests run against shared operating-system state. Cleanup must be scoped to resources the test created; killing `notepad.exe` globally would be destructive and could affect another test or a user session.",
    whyUk: "Desktop tests працюють із shared operating-system state. Cleanup має бути scoped до resources, створених test; global kill `notepad.exe` був би destructive і міг би зачепити інший test або user session.",
    state: "Before teardown: the test document may be saved or dirty and UIA objects are alive. After: the owned tab/file is gone and the automation client is disposed, while unrelated Notepad state is left alone.",
    stateUk: "До teardown: test document може бути saved або dirty, UIA objects живі. Після: owned tab/file зник, automation client disposed, а unrelated Notepad state не чіпається.",
    breakage: "Replacing Ctrl+W with killing all Notepad processes violates ownership. Deleting the file before confirming the document is closed can race with the application and make cleanup unreliable.",
    breakageUk: "Заміна Ctrl+W на kill усіх Notepad processes порушує ownership. Delete file до підтвердження, що document closed, може race-итись з application і зробити cleanup unreliable.",
    keyPoints: ["Cleanup is part of test correctness.", "Own the smallest possible external resource."],
    keyPointsUk: ["Cleanup — частина test correctness.", "Володійте найменшим можливим external resource."],
    pitfalls: ["Using process-wide cleanup for a tab-scoped test."],
    pitfallsUk: ["Використовувати process-wide cleanup для tab-scoped test."],
    exercise: "Explain why `File.Delete` is guarded by a check that the test file is no longer open.",
    exerciseUk: "Поясніть, чому `File.Delete` guarded перевіркою, що test file більше не open.",
    sourceIds: ["nunit-lifecycle-docs", "flaui-repo"],
  }),
  lesson({
    id: "ta-lesson-desktop-automation-flaui-scenario",
    order: 61,
    title: "FlaUI scenario code stays small because the base owns mechanics",
    titleUk: "FlaUI scenario code малий, бо base володіє mechanics",
    summary: "Separate scenario intent from reusable desktop-automation infrastructure.",
    summaryUk: "Відокремте scenario intent від reusable desktop-automation infrastructure.",
    path: "flaui/Notepad.Tests/NotepadTests.cs",
    codeLanguage: "csharp",
    code: "[Test]\n[Category(\"PortableNotepad\")]\npublic void CanTypeAndSaveText()\n{\n    const string expected = \"Hello desktop automation\";\n\n    var editor = FindEditor();\n    ReplaceTextWithClipboard(editor, expected);\n    CaptureWindow(\"01-text-entered\");\n\n    Assert.That(ReadEditorText(editor), Is.EqualTo(expected));\n\n    SaveAndWaitForText(expected);\n    CaptureWindow(\"02-saved\");\n\n    Assert.That(File.ReadAllText(TestFilePath), Is.EqualTo(expected));\n}",
    what: "NUnit calls inherited setup before entering this method. The scenario asks the base class for the editor, replaces text through the shared clipboard strategy, records evidence and checks the UI value. It then performs the shared save-and-wait action and independently verifies disk contents. Inherited teardown runs after the method.",
    whatUk: "NUnit викликає inherited setup до входу в цей method. Scenario просить base class знайти editor, замінює text через shared clipboard strategy, записує evidence і перевіряє UI value. Потім виконує shared save-and-wait action та незалежно перевіряє disk contents. Inherited teardown запускається після method.",
    why: "The test method reads as business/test intent because low-level UI discovery, timing, clipboard STA handling, screenshots and cleanup are centralized. This is the practical purpose of a test base/framework abstraction.",
    whyUk: "Test method читається як business/test intent, бо low-level UI discovery, timing, clipboard STA handling, screenshots і cleanup централізовані. Це практичний сенс test base/framework abstraction.",
    state: "Before method: setup prepared an empty unique document. After method: exact text has been validated in the editor and on disk; teardown then removes the owned resources.",
    stateUk: "До method: setup підготував empty unique document. Після method: exact text перевірений в editor і на disk; teardown потім видаляє owned resources.",
    breakage: "Inlining every helper here would duplicate complex mechanics across scenarios and make behavior harder to change consistently.",
    breakageUk: "Inline всіх helpers сюди продублює complex mechanics між scenarios і ускладнить consistent change behavior.",
    keyPoints: ["Tests express intent; framework helpers express mechanics.", "The assertions remain visible in the scenario."],
    keyPointsUk: ["Tests виражають intent; framework helpers — mechanics.", "Assertions залишаються видимими у scenario."],
    pitfalls: ["Hiding all assertions inside helpers until the test no longer communicates what it proves."],
    pitfallsUk: ["Сховати всі assertions у helpers так, що test перестає показувати, що саме він доводить."],
    exercise: "Identify which lines are scenario-specific and which could be reused by ten different Notepad tests.",
    exerciseUk: "Визначте, які lines scenario-specific, а які можна reuse у десяти різних Notepad tests.",
    sourceIds: ["flaui-repo", "nunit-lifecycle-docs", "allure-nunit-docs"],
  }),
  lesson({
    id: "ta-lesson-desktop-automation-uia3-base",
    order: 62,
    title: "FlaUI UIA3 is a client over the Windows UI Automation tree",
    titleUk: "FlaUI UIA3 — client над Windows UI Automation tree",
    summary: "Connect the C# wrapper API to the same operating-system automation model used by pywinauto.",
    summaryUk: "Зв'яжіть C# wrapper API з тією самою operating-system automation model, яку використовує pywinauto.",
    path: "flaui/Notepad.Tests/NotepadTestBase.cs",
    codeLanguage: "csharp",
    code: "private static FlaUITextBox FindEditor(Window window)\n{\n    var result = Retry.WhileNull(\n        () => window.FindFirstDescendant(cf => cf.ByControlType(ControlType.Document))\n              ?? window.FindFirstDescendant(cf => cf.ByControlType(ControlType.Edit)),\n        timeout: TimeSpan.FromSeconds(10),\n        interval: TimeSpan.FromMilliseconds(250),\n        ignoreException: true);\n\n    if (!result.Success || result.Result is null)\n    {\n        throw new InvalidOperationException(\n            \"Could not find the Notepad editor through UI Automation.\");\n    }\n\n    return result.Result.AsTextBox();\n}",
    what: "Starting from a FlaUI `Window`, the helper queries descendants in the Windows UI Automation tree. It first asks for a `Document` control, then falls back to `Edit`, retries while the UI is still materializing, validates that a result exists and converts the generic automation element into FlaUI's text-box wrapper.",
    whatUk: "Починаючи з FlaUI `Window`, helper query-ить descendants у Windows UI Automation tree. Він спочатку шукає `Document` control, потім fallback на `Edit`, retry поки UI materialize-иться, перевіряє наявність result і перетворює generic automation element на FlaUI text-box wrapper.",
    why: "FlaUI and pywinauto are different client libraries over the same Windows UIA concepts. Understanding UIA itself makes the libraries easier to compare and prevents library-specific memorization.",
    whyUk: "FlaUI і pywinauto — різні client libraries над тими самими Windows UIA concepts. Розуміння UIA робить libraries простішими для порівняння і не дає зводити learning до library-specific memorization.",
    state: "Before: generic top-level `Window`. After: a typed FlaUI `TextBox` wrapper for the semantic text editor.",
    stateUk: "До: generic top-level `Window`. Після: typed FlaUI `TextBox` wrapper semantic text editor.",
    breakage: "Removing the fallback can make one Windows build unsupported. Removing retry assumes the UI tree is fully available immediately after launch.",
    breakageUk: "Без fallback одна Windows build може стати unsupported. Без retry code припускає, що UI tree fully available одразу після launch.",
    keyPoints: ["Libraries wrap UIA; they do not replace the underlying model.", "Typed wrappers are created after element discovery."],
    keyPointsUk: ["Libraries wrap UIA; вони не замінюють underlying model.", "Typed wrappers створюються після element discovery."],
    pitfalls: ["Learning `FindFirstDescendant` without understanding what a UIA descendant is."],
    pitfallsUk: ["Вчити `FindFirstDescendant` без розуміння, що таке UIA descendant."],
    exercise: "Write a three-column mapping: Windows UIA concept → pywinauto API → FlaUI API for desktop, window, control type and text value.",
    exerciseUk: "Зробіть mapping у три колонки: Windows UIA concept → pywinauto API → FlaUI API для desktop, window, control type і text value.",
    sourceIds: ["microsoft-windows-uia", "flaui-repo", "pywinauto-docs"],
  }),
  lesson({
    id: "ta-lesson-desktop-automation-two-stacks",
    order: 63,
    title: "Compare Python and C# by responsibility, not syntax",
    titleUk: "Порівнюйте Python і C# за responsibility, а не syntax",
    summary: "Collapse two implementations into one shared automation mental model.",
    summaryUk: "Зведіть дві implementations до однієї shared automation mental model.",
    path: "README.md",
    codeLanguage: "text",
    code: "Python                         C#\npytest fixture                 [SetUp] / [TearDown]\nDesktop(backend=\"uia\")        UIA3Automation\nfind_editor()                  FindEditor()\npyperclip                      WinForms Clipboard\nassert                         Assert.That()\nallure-pytest                  Allure.NUnit",
    what: "The concrete APIs differ, but both stacks perform the same responsibilities: test lifecycle, UIA client creation, window/control discovery, deterministic input, observable waits, assertions, evidence capture and cleanup. The repository is valuable because you can compare each responsibility side-by-side against the same application behavior.",
    whatUk: "Concrete APIs різні, але обидва stacks виконують ті самі responsibilities: test lifecycle, UIA client creation, window/control discovery, deterministic input, observable waits, assertions, evidence capture та cleanup. Repository корисний тим, що кожну responsibility можна порівняти side-by-side на тій самій application behavior.",
    why: "Framework knowledge transfers when you understand responsibilities. Memorizing `pytest.fixture` or `[SetUp]` alone does not teach lifecycle design; seeing them as two implementations of the same boundary does.",
    whyUk: "Framework knowledge переноситься, коли ви розумієте responsibilities. Memorize `pytest.fixture` або `[SetUp]` окремо не навчає lifecycle design; розуміння їх як двох implementations одного boundary — навчає.",
    state: "Before: two apparently different test frameworks. After: one conceptual architecture with language/library-specific implementations.",
    stateUk: "До: два начебто різні test frameworks. Після: одна conceptual architecture з language/library-specific implementations.",
    breakage: "If you compare only syntax, you miss architectural differences such as STA clipboard handling in C# and pytest's yield-based teardown in Python.",
    breakageUk: "Якщо порівнювати лише syntax, ви пропустите architectural differences: STA clipboard handling у C# та pytest yield-based teardown у Python.",
    keyPoints: ["Responsibilities transfer across languages.", "Implementation details still matter at OS boundaries."],
    keyPointsUk: ["Responsibilities переносяться між languages.", "Implementation details все одно важливі на OS boundaries."],
    pitfalls: ["Concluding that two APIs are equivalent merely because their test scenarios look similar."],
    pitfallsUk: ["Вважати два APIs equivalent лише тому, що їх test scenarios виглядають схожими."],
    exercise: "Choose one helper in Python and find the closest C# equivalent; list one implementation detail that differs.",
    exerciseUk: "Виберіть один Python helper і знайдіть closest C# equivalent; назвіть одну implementation detail, яка відрізняється.",
    sourceIds: ["flaui-repo", "pywinauto-docs", "nunit-lifecycle-docs", "pytest-fixtures-docs"],
  }),
  lesson({
    id: "ta-lesson-desktop-automation-local-runner",
    order: 64,
    title: "Local PowerShell runner: orchestrate both stacks and fail fast",
    titleUk: "Local PowerShell runner: orchestration двох stacks і fail fast",
    summary: "Trace the local script from environment diagnostics through tests to Allure generation.",
    summaryUk: "Простежте local script від environment diagnostics через tests до Allure generation.",
    path: "scripts/run-local.ps1",
    codeLanguage: "powershell",
    code: "$ErrorActionPreference = \"Stop\"\n$env:DESKTOP_TEST_ENVIRONMENT = \"local-windows\"\n$env:DESKTOP_TEST_ARTIFACTS_DIR = (Join-Path $PWD \"test-artifacts\")\n\nRemove-Item -Recurse -Force allure-results, allure-report, test-artifacts -ErrorAction SilentlyContinue\nNew-Item -ItemType Directory -Force -Path allure-results | Out-Null\n\nWrite-Host \"Running FlaUI suite...\"\ndotnet test flaui/Notepad.Tests/Notepad.Tests.csproj --configuration Debug\nif ($LASTEXITCODE -ne 0) {\n    throw \"FlaUI tests failed with exit code $LASTEXITCODE.\"\n}\n\nWrite-Host \"Running pywinauto suite with Allure results...\"\npython -m pytest python/tests -vv --alluredir=allure-results\nif ($LASTEXITCODE -ne 0) {\n    throw \"pywinauto tests failed with exit code $LASTEXITCODE.\"\n}\n\nnpx -y allure@3.16.0 generate allure-results --config ./allurerc.mjs",
    what: "PowerShell sets strict error behavior and shared environment variables, removes stale report/artifact directories, creates a clean Allure result directory, executes the C# suite and explicitly checks its native exit code, then does the same for pytest. Only after both suites succeed does it invoke the pinned Allure CLI to turn raw results into the HTML report.",
    whatUk: "PowerShell встановлює strict error behavior і shared environment variables, видаляє stale report/artifact directories, створює clean Allure result directory, запускає C# suite і явно перевіряє native exit code, потім робить те саме для pytest. Лише після success обох suites він викликає pinned Allure CLI для перетворення raw results на HTML report.",
    why: "One script gives a developer the same ordered workflow every time and documents the actual commands CI will later automate. Explicit `$LASTEXITCODE` checks prevent failed native commands from being mistaken for success.",
    whyUk: "Один script дає developer однаковий ordered workflow кожного разу і документує actual commands, які потім автоматизує CI. Explicit `$LASTEXITCODE` checks не дають failed native commands пройти як success.",
    state: "Before: possibly stale results and no guarantee about execution order. After: both suites have run against the local interactive desktop and a fresh combined Allure report exists, or the script stopped at the first functional failure.",
    stateUk: "До: можуть бути stale results і немає guarantee execution order. Після: обидва suites виконані на local interactive desktop і існує fresh combined Allure report, або script зупинився на first functional failure.",
    breakage: "Keeping stale `allure-results` can mix old and new tests. Ignoring `$LASTEXITCODE` can allow report generation to hide a failing suite behind a successful final command.",
    breakageUk: "Stale `allure-results` можуть змішати old і new tests. Ігнорування `$LASTEXITCODE` може дозволити report generation приховати failing suite за successful final command.",
    keyPoints: ["Orchestration scripts define execution contracts.", "Native command exit codes must be propagated deliberately in PowerShell."],
    keyPointsUk: ["Orchestration scripts визначають execution contracts.", "Native command exit codes у PowerShell треба propagate свідомо."],
    pitfalls: ["Assuming `$ErrorActionPreference = 'Stop'` automatically converts every non-zero native exit code into a terminating PowerShell error."],
    pitfallsUk: ["Вважати, що `$ErrorActionPreference = 'Stop'` автоматично перетворює кожен non-zero native exit code на terminating PowerShell error."],
    exercise: "Trace what happens if `dotnet test` exits with code 1. Which later commands run and which do not?",
    exerciseUk: "Простежте, що станеться, якщо `dotnet test` завершується code 1. Які later commands виконаються, а які ні?",
    sourceIds: ["allure-pytest-docs", "allure-nunit-docs"],
  }),
  lesson({
    id: "ta-lesson-desktop-automation-ci-triggers-runner",
    order: 65,
    title: "GitHub Actions: triggers, concurrency and the Windows runner",
    titleUk: "GitHub Actions: triggers, concurrency і Windows runner",
    summary: "Read the workflow header as the rule that decides when and where CI exists.",
    summaryUk: "Читайте workflow header як правило, що вирішує, коли і де існує CI.",
    path: ".github/workflows/desktop-ui-tests.yml",
    codeLanguage: "yaml",
    code: "name: Desktop UI tests\n\non:\n  workflow_dispatch:\n  push:\n    branches: [main]\n  pull_request:\n    branches: [main]\n\npermissions:\n  contents: read\n\nconcurrency:\n  group: desktop-ui-${{ github.ref }}\n  cancel-in-progress: true\n\njobs:\n  desktop-tests:\n    name: Notepad UI tests + screenshots + Allure\n    runs-on: windows-latest\n    timeout-minutes: 20",
    what: "GitHub creates a workflow run for manual dispatch, pushes to `main`, and pull requests targeting `main`. The job gets read-only repository content permission, shares a concurrency group keyed by Git ref so a newer run can cancel an obsolete in-progress run for the same ref, and is scheduled onto a temporary GitHub-hosted `windows-latest` runner with a 20-minute job limit.",
    whatUk: "GitHub створює workflow run для manual dispatch, pushes у `main` та pull requests до `main`. Job отримує read-only repository content permission, має concurrency group за Git ref, тому newer run може cancel obsolete in-progress run того самого ref, і scheduler відправляє його на temporary GitHub-hosted `windows-latest` runner з 20-minute job limit.",
    why: "This header defines the CI contract before any command executes: events, permissions, cancellation behavior, operating system and maximum duration.",
    whyUk: "Цей header визначає CI contract до виконання будь-якої command: events, permissions, cancellation behavior, operating system та maximum duration.",
    state: "Before an event: there is no runner. After GitHub schedules the job: a fresh hosted Windows environment exists and can execute the declared steps.",
    stateUk: "До event: runner не існує. Після scheduling job GitHub: існує fresh hosted Windows environment, який може виконувати declared steps.",
    breakage: "Using a Linux runner would make Windows Notepad/UIA tests impossible. Removing concurrency cancellation can waste runner time on superseded commits. Omitting a timeout can leave a stuck desktop job consuming capacity much longer.",
    breakageUk: "Linux runner зробить Windows Notepad/UIA tests неможливими. Без concurrency cancellation runner time витрачатиметься на superseded commits. Без timeout stuck desktop job може займати capacity значно довше.",
    keyPoints: ["CI starts from events and runner selection, not from test commands.", "Hosted runners are ephemeral execution environments."],
    keyPointsUk: ["CI починається з events і runner selection, а не test commands.", "Hosted runners — ephemeral execution environments."],
    pitfalls: ["Reading `runs-on` as a label only instead of the operating-system/runtime boundary for the whole job."],
    pitfallsUk: ["Сприймати `runs-on` лише як label, а не operating-system/runtime boundary для всього job."],
    exercise: "For a PR with three rapid pushes, explain what `cancel-in-progress: true` is intended to do for runs sharing the same ref.",
    exerciseUk: "Для PR із трьома швидкими pushes поясніть, що має зробити `cancel-in-progress: true` для runs з тим самим ref.",
    sourceIds: ["github-actions-workflow-docs", "github-actions-contexts-docs"],
  }),
  lesson({
    id: "ta-lesson-desktop-automation-ci-environment",
    order: 66,
    title: "CI environment setup: checkout, .NET, Python and Node",
    titleUk: "CI environment setup: checkout, .NET, Python і Node",
    summary: "See how a blank hosted runner becomes capable of executing the repository.",
    summaryUk: "Подивіться, як blank hosted runner стає здатним виконати repository.",
    path: ".github/workflows/desktop-ui-tests.yml",
    codeLanguage: "yaml",
    code: "steps:\n  - name: Checkout\n    uses: actions/checkout@v7\n\n  - name: Setup .NET\n    uses: actions/setup-dotnet@v6\n    with:\n      dotnet-version: 8.0.x\n\n  - name: Setup Python\n    uses: actions/setup-python@v7\n    with:\n      python-version: \"3.12\"\n      cache: pip\n      cache-dependency-path: python/requirements.txt\n\n  - name: Setup Node for Allure\n    uses: actions/setup-node@v7\n    with:\n      node-version: \"22\"",
    what: "`checkout` places the repository commit into the runner workspace. The setup actions then select the required .NET SDK, Python 3.12 and Node 22 toolchains. Python setup also enables pip caching keyed from the dependency file, while Node exists because Allure 3 is invoked later through `npx`.",
    whatUk: "`checkout` розміщує repository commit у runner workspace. Setup actions потім обирають потрібні .NET SDK, Python 3.12 і Node 22 toolchains. Python setup також вмикає pip caching, прив'язаний до dependency file, а Node потрібен, бо Allure 3 далі запускається через `npx`.",
    why: "A hosted runner should be treated as reproducible infrastructure, not as your laptop. The workflow explicitly prepares the tools it relies on instead of assuming a developer's preconfigured environment.",
    whyUk: "Hosted runner треба сприймати як reproducible infrastructure, а не ваш laptop. Workflow явно готує tools, від яких залежить, замість припущення про preconfigured developer environment.",
    state: "Before steps: a fresh Windows runner with its image defaults. After: repository files are present and the required language/tool runtimes are selected for subsequent commands.",
    stateUk: "До steps: fresh Windows runner з image defaults. Після: repository files присутні й потрібні language/tool runtimes selected для subsequent commands.",
    breakage: "Without checkout, relative repository paths do not exist. A mismatched .NET/Python version can make dependency restore or tests fail. Without Node, the later `npx allure` command cannot run.",
    breakageUk: "Без checkout relative repository paths не існують. Mismatched .NET/Python version може зламати dependency restore або tests. Без Node later `npx allure` не запуститься.",
    keyPoints: ["CI recreates tools declaratively.", "Each setup action prepares a dependency for later steps."],
    keyPointsUk: ["CI відтворює tools declaratively.", "Кожен setup action готує dependency для later steps."],
    pitfalls: ["Assuming `windows-latest` guarantees the exact runtime versions your project expects forever."],
    pitfallsUk: ["Припускати, що `windows-latest` назавжди гарантує exact runtime versions, які очікує project."],
    exercise: "For each setup step, name the first later command that depends on it.",
    exerciseUk: "Для кожного setup step назвіть першу later command, яка від нього залежить.",
    sourceIds: ["github-actions-workflow-docs"],
  }),
  lesson({
    id: "ta-lesson-desktop-automation-ci-test-execution",
    order: 67,
    title: "CI test execution and `if: always()` semantics",
    titleUk: "CI test execution та semantics `if: always()`",
    summary: "Understand why later diagnostic/reporting work can run after an earlier suite fails.",
    summaryUk: "Зрозумійте, чому later diagnostic/reporting work може виконуватись після failure earlier suite.",
    path: ".github/workflows/desktop-ui-tests.yml",
    codeLanguage: "yaml",
    code: "- name: Run ALL FlaUI tests\n  shell: pwsh\n  run: >-\n    dotnet test flaui/Notepad.Tests/Notepad.Tests.csproj\n    --configuration Release\n    --logger \"trx;LogFileName=flaui.trx\"\n    --results-directory flaui/TestResults\n\n- name: Install Python dependencies\n  if: always()\n  shell: pwsh\n  run: python -m pip install -r python/requirements.txt\n\n- name: Run ALL pywinauto tests\n  if: always()\n  shell: pwsh\n  run: >-\n    python -m pytest python/tests -vv\n    --junitxml=pywinauto-pytest.xml\n    --alluredir=allure-results",
    what: "The job first runs the complete C# project in Release mode and writes TRX results. The next two steps explicitly use the GitHub Actions status function `always()`, so they are still evaluated/run even if the FlaUI step failed (subject to broader run cancellation). Python dependencies are installed, then pytest writes both JUnit XML and Allure result files.",
    whatUk: "Job спочатку запускає complete C# project у Release mode і пише TRX results. Наступні два steps явно використовують GitHub Actions status function `always()`, тому вони все одно evaluation/run навіть якщо FlaUI step failed (крім broader run cancellation). Python dependencies install-яться, потім pytest пише JUnit XML і Allure result files.",
    why: "For a comparison lab, one failing stack should not automatically prevent collecting evidence from the other stack. `always()` allows the run to produce a fuller diagnostic picture and later report/artifact stages can still preserve evidence.",
    whyUk: "Для comparison lab failure одного stack не має автоматично забороняти збір evidence з другого. `always()` дозволяє отримати fuller diagnostic picture, а later report/artifact stages можуть зберегти evidence.",
    state: "Before: toolchains exist and result folders are clean. After: one or both test stacks have produced their native and Allure results, even when the first stack did not pass.",
    stateUk: "До: toolchains існують і result folders clean. Після: один або обидва test stacks створили native та Allure results, навіть якщо first stack не pass.",
    breakage: "Without `if: always()`, GitHub's default success condition can skip Python execution after a FlaUI failure, reducing diagnostic coverage. Using `always()` indiscriminately, however, can run actions that should genuinely stop after a prerequisite failure.",
    breakageUk: "Без `if: always()` default success condition GitHub може skip Python execution після FlaUI failure і зменшити diagnostic coverage. Але indiscriminate `always()` може запустити actions, які справді повинні stop після prerequisite failure.",
    keyPoints: ["Step conditions are part of control flow.", "Failure collection and functional success are different concerns."],
    keyPointsUk: ["Step conditions — частина control flow.", "Failure collection і functional success — різні concerns."],
    pitfalls: ["Reading `always()` as 'ignore failure' rather than 'still run this step according to the always status function'."],
    pitfallsUk: ["Читати `always()` як 'ignore failure', а не 'still run this step за always status function'."],
    exercise: "Trace the job when FlaUI fails: list every shown step that still runs and explain why.",
    exerciseUk: "Простежте job, коли FlaUI fails: перелічіть усі показані steps, що все одно run, і поясніть чому.",
    sourceIds: ["github-actions-workflow-docs", "github-actions-contexts-docs"],
  }),
  lesson({
    id: "ta-lesson-desktop-automation-allure-pipeline",
    order: 68,
    title: "Allure pipeline: raw results → one HTML report → preserved artifacts",
    titleUk: "Allure pipeline: raw results → один HTML report → preserved artifacts",
    summary: "Follow reporting data after the functional test commands have finished.",
    summaryUk: "Простежте reporting data після завершення functional test commands.",
    path: ".github/workflows/desktop-ui-tests.yml",
    codeLanguage: "yaml",
    code: "- name: Show collected Allure results\n  if: always()\n  shell: pwsh\n  run: |\n    $results = @(Get-ChildItem allure-results -Filter \"*-result.json\" -File -ErrorAction SilentlyContinue)\n    Write-Host \"Allure test result files in shared directory: $($results.Count)\"\n    if ($results.Count -eq 0) {\n      throw \"No Allure test result files were produced.\"\n    }\n\n- name: Generate Allure report\n  if: always()\n  shell: pwsh\n  run: npx --prefer-offline -y allure@3.16.0 generate allure-results --config ./allurerc.mjs\n\n- name: Upload report and screenshots\n  if: always()\n  uses: actions/upload-artifact@v7\n  with:\n    name: desktop-ui-test-report\n    path: |\n      allure-report\n      allure-results\n      test-artifacts\n      desktop-environment.txt\n      flaui/TestResults\n      pywinauto-pytest.xml\n    retention-days: 7",
    what: "The workflow first validates that shared Allure result JSON files actually exist. The Allure CLI then converts the raw result model and attachments into a browsable HTML report. Finally GitHub Actions uploads both processed and raw evidence—report, result files, screenshots, environment diagnostics, TRX directory and pytest JUnit XML—as a seven-day workflow artifact.",
    whatUk: "Workflow спочатку перевіряє, що shared Allure result JSON files реально існують. Allure CLI потім перетворює raw result model та attachments на browsable HTML report. Нарешті GitHub Actions upload-ить processed і raw evidence — report, result files, screenshots, environment diagnostics, TRX directory та pytest JUnit XML — як seven-day workflow artifact.",
    why: "Reporting should fail clearly when no test results exist; an empty-looking successful report is misleading. Keeping raw evidence alongside HTML allows later debugging without depending solely on the rendered report.",
    whyUk: "Reporting має явно fail, якщо test results відсутні; empty-looking successful report вводить в оману. Збереження raw evidence разом з HTML дозволяє later debugging без залежності лише від rendered report.",
    state: "Before: test frameworks produced raw files. After: a combined human-readable report exists and GitHub stores a downloadable evidence bundle independent of later deployment.",
    stateUk: "До: test frameworks створили raw files. Після: існує combined human-readable report і GitHub зберігає downloadable evidence bundle незалежно від later deployment.",
    breakage: "Skipping the result-count guard can make a reporting configuration failure look like a test run with no cases. Uploading only HTML discards lower-level evidence useful for debugging.",
    breakageUk: "Без result-count guard reporting configuration failure може виглядати як test run без cases. Upload лише HTML викидає lower-level evidence, корисний для debugging.",
    keyPoints: ["Allure results and the generated report are different artifacts.", "Preserve raw diagnostics as well as presentation output."],
    keyPointsUk: ["Allure results і generated report — різні artifacts.", "Зберігайте raw diagnostics разом із presentation output."],
    pitfalls: ["Treating report generation success as proof that functional tests passed."],
    pitfallsUk: ["Сприймати report generation success як доказ, що functional tests passed."],
    exercise: "Classify every uploaded path as raw test result, rendered report, screenshot/evidence or environment diagnostic.",
    exerciseUk: "Класифікуйте кожен uploaded path як raw test result, rendered report, screenshot/evidence або environment diagnostic.",
    sourceIds: ["github-actions-workflow-docs", "allure-pytest-docs", "allure-nunit-docs"],
  }),
  lesson({
    id: "ta-lesson-desktop-automation-ci-secrets-deploy",
    order: 69,
    title: "Secrets, SSH and report deployment to Hetzner",
    titleUk: "Secrets, SSH та deployment report на Hetzner",
    summary: "Trace the deployment step without confusing repository variables, secrets, runner files and remote commands.",
    summaryUk: "Простежте deployment step, не плутаючи repository variables, secrets, runner files та remote commands.",
    path: ".github/workflows/desktop-ui-tests.yml",
    codeLanguage: "yaml",
    code: "- name: Publish latest Allure report to Hetzner\n  if: always() && github.event_name != 'pull_request'\n  shell: pwsh\n  env:\n    HETZNER_SSH_KEY: ${{ secrets.HETZNER_SSH_KEY }}\n    HETZNER_HOST: ${{ vars.HETZNER_HOST || '46.224.218.150' }}\n    HETZNER_SSH_USER: ${{ vars.HETZNER_SSH_USER || 'root' }}\n    HETZNER_SSH_PORT: ${{ vars.HETZNER_SSH_PORT || '22' }}\n    HETZNER_WEB_PORT: ${{ vars.HETZNER_WEB_PORT || '8089' }}\n  run: |\n    $keyText = $env:HETZNER_SSH_KEY.Trim().Replace('\\n', \"`n\").Replace(\"`r\", \"\")\n    [System.IO.File]::WriteAllText($keyPath, $keyText + \"`n\", [System.Text.UTF8Encoding]::new($false))\n    tar -czf $archive -C allure-report .\n    & scp -P $sshPort @sshOptions $archive scripts/hetzner/deploy-allure.sh \"$sshUser@$hostName`:/tmp/\"\n    & ssh -p $sshPort @sshOptions \"$sshUser@$hostName\" \"bash /tmp/deploy-allure.sh '$releaseId' '$webPort' && rm -f /tmp/deploy-allure.sh\"",
    what: "This step is eligible after tests/reporting even on failure, but it is excluded from pull-request events. GitHub expression evaluation places the secret key and configurable variables into this step's environment. PowerShell writes the private key into a temporary runner file, creates a compressed report archive, copies the archive plus deployment script to the remote host via SCP, then executes that script over SSH with a release ID and web port.",
    whatUk: "Цей step eligible після tests/reporting навіть при failure, але excluded для pull-request events. GitHub expression evaluation кладе secret key та configurable variables у environment цього step. PowerShell записує private key у temporary runner file, створює compressed report archive, копіює archive та deployment script на remote host через SCP, а потім запускає script через SSH з release ID і web port.",
    why: "Secrets and ordinary configuration have different sensitivity. The private key belongs in `secrets`, while host/user/ports can be repository variables or defaults. PRs are prevented from publishing the shared live report, avoiding untrusted/temporary branch output replacing the latest main report.",
    whyUk: "Secrets і ordinary configuration мають різну sensitivity. Private key належить у `secrets`, тоді як host/user/ports можуть бути repository variables або defaults. PRs не публікують shared live report, щоб temporary branch output не замінив latest main report.",
    state: "Before: generated report exists only on the runner. After: archive and deploy script were transferred, remote deployment ran, and the runner can remove the temporary key/archive while GitHub still retains the workflow artifact separately.",
    stateUk: "До: generated report існує лише на runner. Після: archive і deploy script transferred, remote deployment executed, runner може видалити temporary key/archive, а GitHub окремо зберігає workflow artifact.",
    breakage: "Putting the private key in repository variables or source exposes credentials. Publishing from PR events can let review code overwrite shared report state. Skipping key validation/permissions can make SSH fail or weaken secret handling.",
    breakageUk: "Private key у repository variables або source expose-ить credentials. Publish з PR events може дозволити review code overwrite shared report state. Без key validation/permissions SSH може fail або secret handling ослабне.",
    keyPoints: ["GitHub expressions resolve secrets/variables before shell code consumes environment variables.", "CI deployment has a trust boundary separate from test execution."],
    keyPointsUk: ["GitHub expressions resolve secrets/variables до того, як shell code читає environment variables.", "CI deployment має trust boundary, окремий від test execution."],
    pitfalls: ["Treating `${{ secrets.NAME }}` and `$env:NAME` as the same mechanism; the first is workflow expression/context resolution, the second is PowerShell environment access."],
    pitfallsUk: ["Сприймати `${{ secrets.NAME }}` і `$env:NAME` як один механізм; перше — workflow expression/context resolution, друге — PowerShell environment access."],
    exercise: "Trace the SSH key from GitHub secret storage to the exact moment the `ssh` command reads the temporary file, then identify where it is removed.",
    exerciseUk: "Простежте SSH key від GitHub secret storage до моменту, коли `ssh` command читає temporary file, а потім знайдіть, де він видаляється.",
    sourceIds: ["github-actions-workflow-docs", "github-actions-contexts-docs"],
  }),
  lesson({
    id: "ta-lesson-desktop-automation-evidence-diagnostics",
    order: 70,
    title: "Screenshots and environment diagnostics are evidence, not test truth",
    titleUk: "Screenshots та environment diagnostics — evidence, а не test truth",
    summary: "Understand why the project captures evidence around state changes while assertions remain machine-readable.",
    summaryUk: "Зрозумійте, чому проєкт capture-ить evidence біля state changes, але assertions залишаються machine-readable.",
    path: "flaui/Notepad.Tests/NotepadTestBase.cs",
    codeLanguage: "csharp",
    code: "protected void CaptureWindow(string step)\n{\n    if (_window is null)\n    {\n        return;\n    }\n\n    try\n    {\n        var configuredRoot = Environment.GetEnvironmentVariable(\"DESKTOP_TEST_ARTIFACTS_DIR\");\n        var artifactsRoot = string.IsNullOrWhiteSpace(configuredRoot)\n            ? Path.Combine(Directory.GetCurrentDirectory(), \"flaui\", \"TestArtifacts\")\n            : Path.GetFullPath(configuredRoot);\n\n        var testDirectory = Path.Combine(artifactsRoot, SanitizeFileName(TestContext.CurrentContext.Test.Name));\n        Directory.CreateDirectory(testDirectory);\n        var screenshotPath = Path.Combine(testDirectory, $\"{DateTime.UtcNow:HHmmssfff}-{SanitizeFileName(step)}.png\");\n        _window.CaptureToFile(screenshotPath);\n        TestContext.AddTestAttachment(screenshotPath, $\"Notepad: {step}\");\n        AllureApi.AddAttachment($\"Notepad - {step}\", \"image/png\", screenshotPath);\n    }\n    catch (Exception ex)\n    {\n        TestContext.Progress.WriteLine($\"Screenshot warning: {ex.Message}\");\n    }\n}",
    what: "The helper chooses an artifact root from the shared environment variable or a local fallback, creates a test-specific directory, captures the current Notepad window to a timestamped PNG, attaches the same file to NUnit's test context and to Allure, and deliberately converts screenshot failures into warnings rather than functional test failures.",
    whatUk: "Helper обирає artifact root зі shared environment variable або local fallback, створює test-specific directory, capture-ить current Notepad window у timestamped PNG, attach-ить той самий file до NUnit test context і Allure та свідомо перетворює screenshot failures на warnings, а не functional test failures.",
    why: "Screenshots help investigate desktop failures and prove what the UI looked like, but a reporting subsystem should not change a correct functional result just because image capture failed. Assertions against UIA/file state remain the source of test truth.",
    whyUk: "Screenshots допомагають investigate desktop failures і показують, як виглядав UI, але reporting subsystem не має змінювати correct functional result лише через image capture failure. Assertions проти UIA/file state залишаються source of test truth.",
    state: "Before: only live UI state exists. After: there is a timestamped diagnostic image attached to both native and Allure reporting channels, or a warning explaining why capture failed.",
    stateUk: "До: існує лише live UI state. Після: є timestamped diagnostic image, attached до native та Allure reporting channels, або warning із причиною capture failure.",
    breakage: "If screenshot capture throws through the test, a reporting problem can create false functional failures. If screenshots are never taken, debugging intermittent UI state becomes substantially harder.",
    breakageUk: "Якщо screenshot capture exception проходить у test, reporting problem створить false functional failures. Якщо screenshots ніколи не робити, debugging intermittent UI state стане значно складнішим.",
    keyPoints: ["Evidence collection should support, not redefine, assertions.", "Environment variables let local and CI runs share one artifact convention."],
    keyPointsUk: ["Evidence collection має підтримувати, а не redefine, assertions.", "Environment variables дозволяють local і CI runs мати одну artifact convention."],
    pitfalls: ["Using visual evidence as the only validation for deterministic text/file state."],
    pitfallsUk: ["Використовувати visual evidence як єдину validation для deterministic text/file state."],
    exercise: "List which failures in this helper should fail the functional test and which should remain reporting warnings; justify the boundary.",
    exerciseUk: "Перелічіть failures у цьому helper, які мають fail functional test, і які мають залишитися reporting warnings; обґрунтуйте boundary.",
    sourceIds: ["allure-nunit-docs"],
  }),
  lesson({
    id: "ta-lesson-desktop-automation-ci-cd-trace",
    order: 71,
    title: "Put it all together: CI, report delivery and the full state machine",
    titleUk: "Зведіть усе разом: CI, report delivery і повна state machine",
    summary: "Finish by tracing one commit from GitHub event to cleaned desktop tests, report evidence and published output.",
    summaryUk: "Завершіть, простеживши один commit від GitHub event до cleaned desktop tests, report evidence та published output.",
    path: ".github/workflows/desktop-ui-tests.yml",
    codeLanguage: "text",
    code: "push / pull_request / manual\n        ↓\nGitHub-hosted windows-latest runner\n        ↓\ncheckout + .NET + Python + Node\n        ↓\nFlaUI tests → TRX + screenshots + Allure results\n        ↓\npywinauto tests → JUnit XML + screenshots + Allure results\n        ↓\nAllure generate → HTML report\n        ↓\nGitHub artifact (always)\n        ↓\nHetzner publish (non-PR events)",
    what: "A repository event creates an ephemeral Windows runner. The workflow materializes source and toolchains, runs two independent automation implementations against real Notepad UI, captures functional and diagnostic results, renders one report, preserves the evidence bundle in GitHub and—outside PR events—delivers the latest rendered report to the configured Hetzner host. Each test also creates and cleans only its unique file/tab resources.",
    whatUk: "Repository event створює ephemeral Windows runner. Workflow materialize-ить source і toolchains, запускає дві independent automation implementations проти real Notepad UI, capture-ить functional і diagnostic results, render-ить один report, зберігає evidence bundle у GitHub і — поза PR events — доставляє latest rendered report на configured Hetzner host. Кожен test також створює і cleanup лише свої unique file/tab resources.",
    why: "This final trace separates **continuous integration**—reproducibly integrating code and executing validation—from the small **delivery/deployment** part that publishes the generated report. The test code, CI control flow, reporting and deployment are different systems connected by explicit files, exit statuses and environment/context values.",
    whyUk: "Фінальний trace відокремлює **continuous integration** — reproducible integration code і execution validation — від невеликої **delivery/deployment** частини, яка publish-ить generated report. Test code, CI control flow, reporting і deployment — різні systems, з'єднані explicit files, exit statuses та environment/context values.",
    state: "Before: a commit/PR exists in GitHub. After: tests have executed in a clean hosted Windows environment; owned desktop resources are cleaned; raw and rendered evidence is preserved; for eligible events the latest report is also deployed remotely.",
    stateUk: "До: commit/PR існує у GitHub. Після: tests виконані у clean hosted Windows environment; owned desktop resources cleaned; raw і rendered evidence preserved; для eligible events latest report також deployed remotely.",
    breakage: "Collapsing all of these stages into 'CI runs tests' hides important failure boundaries: setup can fail before tests, one stack can fail while another still produces evidence, report generation can fail after tests, artifact upload can preserve evidence even when deployment fails, and deployment is intentionally event-gated.",
    breakageUk: "Зведення всіх stages до 'CI runs tests' приховує важливі failure boundaries: setup може fail до tests, один stack може fail поки інший все одно produce evidence, report generation може fail після tests, artifact upload може preserve evidence навіть коли deployment fails, а deployment навмисно event-gated.",
    keyPoints: ["CI is a state machine of events, environments, commands, conditions and artifacts.", "Functional testing, reporting and deployment have distinct success/failure boundaries."],
    keyPointsUk: ["CI — state machine з events, environments, commands, conditions та artifacts.", "Functional testing, reporting і deployment мають окремі success/failure boundaries."],
    pitfalls: ["Calling the whole workflow 'deployment' or the whole workflow 'tests' and losing the boundaries between stages."],
    pitfallsUk: ["Називати весь workflow 'deployment' або весь workflow 'tests' і втрачати boundaries між stages."],
    exercise: "Starting from a pull request event, write the complete execution trace and explicitly mark which deployment step is skipped, which steps use `always()`, and which artifacts remain available for debugging.",
    exerciseUk: "Починаючи з pull request event, запишіть complete execution trace і явно позначте, який deployment step skipped, які steps використовують `always()`, і які artifacts залишаються для debugging.",
    sourceIds: ["github-actions-workflow-docs", "github-actions-contexts-docs", "allure-pytest-docs", "allure-nunit-docs"],
  }),
];

export const desktopAutomationReference = {
  repo: REVIEWED_REPO,
  branch: REVIEWED_BRANCH,
  verifiedCommit: REVIEWED_COMMIT,
  verifiedAt: REVIEWED_AT,
};
