export const robotFrameworkModule = {
  id: "robot-framework",
  label: "Robot Framework",
  labelUk: "Robot Framework",
  level: "Intermediate",
  description: "Robot Framework in modern test automation: where it still fits, core syntax, resources, Browser and Requests libraries, Python extensions, reporting and CI — with complete local runnable examples.",
  descriptionUk: "Robot Framework у сучасній автоматизації: де він досі доречний, core syntax, resources, Browser і Requests libraries, Python-розширення, reporting та CI — з повними локально runnable прикладами.",
  introMarkdown: [
    "## Does Robot Framework still matter?",
    "",
    "Yes, but it is a specialized choice rather than the default greenfield web-automation recommendation. The project is actively maintained in 2026 and real QA vacancies still ask for Robot Framework, especially in telecom, embedded/IoT, industrial systems and teams that value keyword-driven authoring. For a new code-heavy web project, Playwright with pytest or TypeScript is usually the more direct choice.",
    "",
    "All examples below are complete copy-and-run local examples. Robot Framework and its Browser/Requests libraries cannot honestly run inside GimmeJob's restricted browser Python sandbox, so Robot and shell blocks are rendered as static code instead of showing a broken Python Run button."
  ].join("\n"),
  introMarkdownUk: [
    "## Чи актуальний Robot Framework зараз?",
    "",
    "Так, але це спеціалізований вибір, а не default для нового web-automation проєкту. У 2026 році проєкт активно підтримується, а в реальних QA вакансіях Robot Framework досі зустрічається, особливо в telecom, embedded/IoT, industrial systems та keyword-driven командах. Для нового code-heavy web-проєкту Playwright із pytest або TypeScript зазвичай є прямішим вибором.",
    "",
    "Усі приклади нижче — повні локальні copy-and-run приклади. Robot Framework та Browser/Requests libraries не можна чесно виконувати у restricted browser Python sandbox GimmeJob, тому Robot і shell blocks рендеряться як static code без несправної Python-кнопки Run."
  ].join("\n"),
  sourceIds: [
    "robot-framework-user-guide",
    "robot-framework-guides",
    "robot-framework-releases",
    "robot-framework-browser",
    "robot-framework-requests",
    "robot-framework-python-library",
    "robot-framework-ci",
  ],
};

export const robotFrameworkSources = [
  {
    id: "robot-framework-user-guide",
    title: "Robot Framework User Guide",
    url: "https://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html",
    publisher: "Robot Framework Foundation",
    kind: "Official documentation",
    role: "Core syntax, suites, keywords, variables, tags, execution and output files",
  },
  {
    id: "robot-framework-guides",
    title: "Robot Framework Guides",
    url: "https://docs.robotframework.org/docs",
    publisher: "Robot Framework Foundation",
    kind: "Official guides",
    role: "Getting started, project structure, libraries, examples and CI guidance",
  },
  {
    id: "robot-framework-releases",
    title: "Robot Framework releases",
    url: "https://github.com/robotframework/robotframework/releases",
    publisher: "Robot Framework",
    kind: "Official release history",
    role: "Current maintenance status, stable releases, previews and release notes",
  },
  {
    id: "robot-framework-browser",
    title: "Robot Framework Browser",
    url: "https://robotframework-browser.org/docs/",
    publisher: "Robot Framework Browser contributors",
    kind: "Official documentation",
    role: "Playwright-backed web automation and Browser lifecycle",
  },
  {
    id: "robot-framework-requests",
    title: "Robot Framework RequestsLibrary",
    url: "https://marketsquare.github.io/robotframework-requests/doc/RequestsLibrary.html",
    publisher: "MarketSquare / RequestsLibrary contributors",
    kind: "Official library documentation",
    role: "HTTP API testing through RequestsLibrary",
  },
  {
    id: "robot-framework-python-library",
    title: "Robot Framework Python libraries",
    url: "https://docs.robotframework.org/docs/extending_robot_framework/custom-libraries/python_library",
    publisher: "Robot Framework Foundation",
    kind: "Official guide",
    role: "Creating custom Robot Framework keywords in Python",
  },
  {
    id: "robot-framework-ci",
    title: "Robot Framework in GitHub Actions",
    url: "https://docs.robotframework.org/docs/using_rf_in_ci_systems/ci/github-actions",
    publisher: "Robot Framework Foundation",
    kind: "Official guide",
    role: "Running Robot Framework in CI and preserving reports",
  },
];

export const robotFrameworkLessons = [
  {
    id: "ta-lesson-robot-framework-core",
    moduleId: "robot-framework",
    level: "Intermediate",
    order: 44,
    title: "Robot Framework mental model and first runnable suite",
    titleUk: "Ментальна модель Robot Framework і перший runnable suite",
    summary: "Start with a complete core-only suite that works in an empty directory.",
    summaryUk: "Почніть із повного core-only suite, який працює в порожньому каталозі.",
    concept: [
      "Robot Framework is keyword-driven: `.robot` suites orchestrate keywords from the core, resource files and libraries. Keep tests focused on intent; move technical mechanics into reusable keywords or libraries.",
      "",
      "### Install",
      "```bash",
      "python -m venv .venv",
      "# Windows PowerShell: .\\.venv\\Scripts\\Activate.ps1",
      "# Linux/macOS: source .venv/bin/activate",
      "python -m pip install robotframework==7.4.2",
      "```",
      "",
      "Create `first.robot`:",
      "```robotframework",
      "*** Variables ***",
      "${ENV}    staging",
      "",
      "*** Test Cases ***",
      "Environment Is Staging",
      "    Log    Starting smoke test",
      "    Should Be Equal    ${ENV}    staging",
      "",
      "Simple Calculation Works",
      "    ${total}=    Evaluate    10 + 15",
      "    Should Be Equal As Integers    ${total}    25",
      "```",
      "",
      "Run:",
      "```bash",
      "python -m robot --outputdir results first.robot",
      "```",
      "",
      "Expected result: `2 tests, 2 passed`, plus `results/output.xml`, `log.html` and `report.html`."
    ].join("\n"),
    conceptUk: [
      "Robot Framework є keyword-driven: `.robot` suites оркеструють keywords із core, resource-файлів та libraries. Тести мають показувати intent, а технічну механіку краще переносити в reusable keywords або libraries.",
      "",
      "### Install",
      "```bash",
      "python -m venv .venv",
      "# Windows PowerShell: .\\.venv\\Scripts\\Activate.ps1",
      "# Linux/macOS: source .venv/bin/activate",
      "python -m pip install robotframework==7.4.2",
      "```",
      "",
      "Створіть `first.robot`:",
      "```robotframework",
      "*** Variables ***",
      "${ENV}    staging",
      "",
      "*** Test Cases ***",
      "Environment Is Staging",
      "    Log    Starting smoke test",
      "    Should Be Equal    ${ENV}    staging",
      "",
      "Simple Calculation Works",
      "    ${total}=    Evaluate    10 + 15",
      "    Should Be Equal As Integers    ${total}    25",
      "```",
      "",
      "Запуск:",
      "```bash",
      "python -m robot --outputdir results first.robot",
      "```",
      "",
      "Очікувано: `2 tests, 2 passed` і файли `output.xml`, `log.html`, `report.html` у `results/`."
    ].join("\n"),
    keyPoints: [
      "Every referenced variable must be defined",
      "Use `python -m robot` so execution uses the active virtual environment",
      "A runnable example includes installation, file contents and the exact command",
    ],
    keyPointsUk: [
      "Кожна referenced variable має бути визначена",
      "Використовуйте `python -m robot`, щоб execution ішов через active virtual environment",
      "Runnable example містить installation, file contents і точну команду",
    ],
    pitfalls: ["Using undefined variables or publishing only a test fragment"],
    pitfallsUk: ["Використовувати undefined variables або публікувати лише test fragment"],
    exercise: "Run the example unchanged, then change the expected environment to `production` and inspect the failure in `log.html`.",
    exerciseUk: "Запустіть приклад без змін, потім змініть expected environment на `production` і перегляньте failure у `log.html`.",
    tags: ["robot-framework", "keywords", "test-automation"],
    sourceIds: ["robot-framework-user-guide", "robot-framework-guides", "robot-framework-releases"],
  },
  {
    id: "ta-lesson-robot-framework-resources",
    moduleId: "robot-framework",
    level: "Intermediate",
    order: 45,
    title: "Variables, resources and a runnable two-file example",
    titleUk: "Variables, resources і runnable приклад із двох файлів",
    summary: "A resource example is useful only when the importing suite is included too.",
    summaryUk: "Resource example корисний лише тоді, коли також показано importing suite.",
    concept: [
      "Prefer explicit keyword arguments and return values over broad suite/global state. `.resource` files are the normal way to share domain keywords between suites.",
      "",
      "Create this structure:",
      "```text",
      "robot-demo/",
      "├── resources/greetings.resource",
      "└── tests/greetings.robot",
      "```",
      "",
      "`resources/greetings.resource`:",
      "```robotframework",
      "*** Keywords ***",
      "Build Greeting",
      "    [Arguments]    ${name}",
      "    RETURN    Hello, ${name}!",
      "```",
      "",
      "`tests/greetings.robot`:",
      "```robotframework",
      "*** Settings ***",
      "Resource    ../resources/greetings.resource",
      "",
      "*** Test Cases ***",
      "Greeting Uses Provided Name",
      "    ${message}=    Build Greeting    Alice",
      "    Should Be Equal    ${message}    Hello, Alice!",
      "```",
      "",
      "Run from `robot-demo/`:",
      "```bash",
      "python -m robot --outputdir results tests",
      "```",
      "",
      "This example has no hidden application or Browser dependency."
    ].join("\n"),
    conceptUk: [
      "Віддавайте перевагу explicit keyword arguments і return values замість широкого suite/global state. `.resource` файли — типовий спосіб ділитися domain keywords між suites.",
      "",
      "Створіть структуру:",
      "```text",
      "robot-demo/",
      "├── resources/greetings.resource",
      "└── tests/greetings.robot",
      "```",
      "",
      "`resources/greetings.resource`:",
      "```robotframework",
      "*** Keywords ***",
      "Build Greeting",
      "    [Arguments]    ${name}",
      "    RETURN    Hello, ${name}!",
      "```",
      "",
      "`tests/greetings.robot`:",
      "```robotframework",
      "*** Settings ***",
      "Resource    ../resources/greetings.resource",
      "",
      "*** Test Cases ***",
      "Greeting Uses Provided Name",
      "    ${message}=    Build Greeting    Alice",
      "    Should Be Equal    ${message}    Hello, Alice!",
      "```",
      "",
      "Запустіть із `robot-demo/`:",
      "```bash",
      "python -m robot --outputdir results tests",
      "```",
      "",
      "У прикладі немає hidden application чи Browser dependency."
    ].join("\n"),
    keyPoints: [
      "Use resource files for reusable domain keywords",
      "Show the importing suite, relative path and run command — not only the resource fragment",
    ],
    keyPointsUk: [
      "Використовуйте resource files для reusable domain keywords",
      "Показуйте importing suite, relative path і run command, а не лише resource fragment",
    ],
    pitfalls: ["Creating one giant `common.resource` or publishing a resource without a runnable consumer"],
    pitfallsUk: ["Створювати один гігантський `common.resource` або публікувати resource без runnable consumer"],
    exercise: "Add a `Build Farewell` keyword and a second test, then run the whole `tests` directory.",
    exerciseUk: "Додайте keyword `Build Farewell` і другий тест, потім запустіть увесь каталог `tests`.",
    tags: ["robot-framework", "resources", "variables", "architecture"],
    sourceIds: ["robot-framework-user-guide", "robot-framework-guides"],
  },
  {
    id: "ta-lesson-robot-framework-libraries",
    moduleId: "robot-framework",
    level: "Intermediate",
    order: 46,
    title: "Runnable Browser and API examples",
    titleUk: "Runnable Browser та API приклади",
    summary: "Use real documented targets and include every dependency step.",
    summaryUk: "Використовуйте real documented targets і включайте всі dependency steps.",
    concept: [
      "Browser Library is Playwright-backed; RequestsLibrary wraps Python Requests. Both need real dependencies, so the examples below include installation and use public endpoints from the libraries' own documentation instead of fake `example.test` URLs.",
      "",
      "### Browser Library",
      "```bash",
      "python -m pip install robotframework-browser",
      "rfbrowser init",
      "```",
      "",
      "Create `browser.robot`:",
      "```robotframework",
      "*** Settings ***",
      "Library    Browser",
      "",
      "*** Test Cases ***",
      "Robot Framework Browser Site Opens",
      "    New Page    https://robotframework-browser.org",
      "    Get Title    *=    Robot Framework Browser",
      "```",
      "",
      "```bash",
      "python -m robot --outputdir results browser.robot",
      "```",
      "",
      "### RequestsLibrary",
      "```bash",
      "python -m pip install robotframework-requests",
      "```",
      "",
      "Create `api.robot`:",
      "```robotframework",
      "*** Settings ***",
      "Library    RequestsLibrary",
      "",
      "*** Test Cases ***",
      "Public JSON Post Can Be Read",
      "    ${response}=    GET    https://jsonplaceholder.typicode.com/posts/1    expected_status=200",
      "    Should Be Equal As Strings    1    ${response.json()}[id]",
      "```",
      "",
      "```bash",
      "python -m robot --outputdir results api.robot",
      "```",
      "",
      "Both examples require internet access because they intentionally exercise real public endpoints."
    ].join("\n"),
    conceptUk: [
      "Browser Library базується на Playwright, а RequestsLibrary обгортає Python Requests. Обидві потребують real dependencies, тому приклади містять installation і використовують public endpoints із документації libraries замість fake `example.test` URLs.",
      "",
      "### Browser Library",
      "```bash",
      "python -m pip install robotframework-browser",
      "rfbrowser init",
      "```",
      "",
      "Створіть `browser.robot`:",
      "```robotframework",
      "*** Settings ***",
      "Library    Browser",
      "",
      "*** Test Cases ***",
      "Robot Framework Browser Site Opens",
      "    New Page    https://robotframework-browser.org",
      "    Get Title    *=    Robot Framework Browser",
      "```",
      "",
      "```bash",
      "python -m robot --outputdir results browser.robot",
      "```",
      "",
      "### RequestsLibrary",
      "```bash",
      "python -m pip install robotframework-requests",
      "```",
      "",
      "Створіть `api.robot`:",
      "```robotframework",
      "*** Settings ***",
      "Library    RequestsLibrary",
      "",
      "*** Test Cases ***",
      "Public JSON Post Can Be Read",
      "    ${response}=    GET    https://jsonplaceholder.typicode.com/posts/1    expected_status=200",
      "    Should Be Equal As Strings    1    ${response.json()}[id]",
      "```",
      "",
      "```bash",
      "python -m robot --outputdir results api.robot",
      "```",
      "",
      "Обидва приклади потребують internet access, бо працюють із real public endpoints."
    ].join("\n"),
    keyPoints: [
      "Browser Library needs `rfbrowser init`; installing Robot Framework core alone is not enough",
      "RequestsLibrary supports sessionless `GET` with `expected_status`",
      "Do not use placeholder domains in an example advertised as runnable",
    ],
    keyPointsUk: [
      "Browser Library потребує `rfbrowser init`; одного Robot Framework core недостатньо",
      "RequestsLibrary підтримує sessionless `GET` з `expected_status`",
      "Не використовуйте placeholder domains у прикладі, який названо runnable",
    ],
    pitfalls: ["Omitting dependency initialization or using URLs that cannot resolve"],
    pitfallsUk: ["Пропускати dependency initialization або використовувати URLs, які не можуть resolve"],
    exercise: "Run both examples unchanged, then deliberately break each assertion and inspect the generated reports.",
    exerciseUk: "Запустіть обидва приклади без змін, потім навмисно зламайте assertions і перегляньте generated reports.",
    tags: ["robot-framework", "browser", "playwright", "api", "requests"],
    sourceIds: ["robot-framework-browser", "robot-framework-requests", "robot-framework-guides"],
  },
  {
    id: "ta-lesson-robot-framework-python-libraries",
    moduleId: "robot-framework",
    level: "Intermediate",
    order: 47,
    title: "Custom Python library: complete runnable pair",
    titleUk: "Custom Python library: повна runnable пара",
    summary: "Show both the Python library and the Robot suite that imports it.",
    summaryUk: "Показуйте і Python library, і Robot suite, який її імпортує.",
    concept: [
      "Use Python for logic that becomes awkward in Robot syntax: calculations, parsing, SDK integrations and reusable technical code. A real Robot custom-library example needs both files.",
      "",
      "Create `OrderLibrary.py`:",
      "```python",
      "from robot.api.deco import keyword",
      "",
      "class OrderLibrary:",
      "    @keyword(\"Calculate Expected Total\")",
      "    def calculate_expected_total(self, first: float, second: float) -> float:",
      "        return round(first + second, 2)",
      "```",
      "",
      "Create `order_total.robot` in the same directory:",
      "```robotframework",
      "*** Settings ***",
      "Library    OrderLibrary.py",
      "",
      "*** Test Cases ***",
      "Order Total Uses Python Keyword",
      "    ${total}=    Calculate Expected Total    10.25    4.75",
      "    Should Be Equal As Numbers    ${total}    15.0",
      "```",
      "",
      "Run:",
      "```bash",
      "python -m robot --outputdir results order_total.robot",
      "```",
      "",
      "Robot Framework uses the Python type hints to convert the two Robot arguments to floats before calling the method."
    ].join("\n"),
    conceptUk: [
      "Використовуйте Python для логіки, яка незручна в Robot syntax: calculations, parsing, SDK integrations та reusable technical code. Реальний Robot custom-library example потребує обидва файли.",
      "",
      "Створіть `OrderLibrary.py`:",
      "```python",
      "from robot.api.deco import keyword",
      "",
      "class OrderLibrary:",
      "    @keyword(\"Calculate Expected Total\")",
      "    def calculate_expected_total(self, first: float, second: float) -> float:",
      "        return round(first + second, 2)",
      "```",
      "",
      "У тому самому каталозі створіть `order_total.robot`:",
      "```robotframework",
      "*** Settings ***",
      "Library    OrderLibrary.py",
      "",
      "*** Test Cases ***",
      "Order Total Uses Python Keyword",
      "    ${total}=    Calculate Expected Total    10.25    4.75",
      "    Should Be Equal As Numbers    ${total}    15.0",
      "```",
      "",
      "Запуск:",
      "```bash",
      "python -m robot --outputdir results order_total.robot",
      "```",
      "",
      "Robot Framework використовує Python type hints для conversion Robot arguments у floats."
    ].join("\n"),
    keyPoints: [
      "Keep orchestration in Robot and complex implementation logic in Python",
      "A custom-library example is incomplete without the Robot `Library` import and keyword call",
    ],
    keyPointsUk: [
      "Тримайте orchestration у Robot, а complex implementation logic — у Python",
      "Custom-library example неповний без Robot `Library` import і keyword call",
    ],
    pitfalls: ["Showing only a Python class and calling it a runnable Robot Framework example"],
    pitfallsUk: ["Показувати лише Python class і називати його runnable Robot Framework example"],
    exercise: "Add a third typed tax argument, update the expected result and rerun the Robot suite.",
    exerciseUk: "Додайте третій typed tax argument, оновіть expected result і перезапустіть Robot suite.",
    tags: ["robot-framework", "python", "custom-library", "keywords"],
    sourceIds: ["robot-framework-python-library", "robot-framework-user-guide"],
  },
  {
    id: "ta-lesson-robot-framework-ci",
    moduleId: "robot-framework",
    level: "Intermediate",
    order: 48,
    title: "Tags, reports and runnable CI",
    titleUk: "Tags, reports і runnable CI",
    summary: "Pair tag commands with a real tagged suite and an executable GitHub Actions workflow.",
    summaryUk: "Поєднуйте tag commands із real tagged suite та executable GitHub Actions workflow.",
    concept: [
      "Robot Framework generates `output.xml`, `log.html` and `report.html`. Tags are useful execution semantics for smoke, regression and slow suites. In CI, preserve the original result bundle as artifacts.",
      "",
      "Create `tests/smoke.robot`:",
      "```robotframework",
      "*** Test Cases ***",
      "Fast Smoke",
      "    [Tags]    smoke",
      "    Should Be Equal    GimmeJob    GimmeJob",
      "",
      "Slow Regression",
      "    [Tags]    regression    slow",
      "    Sleep    0.01s",
      "    Should Be True    ${True}",
      "```",
      "",
      "Run smoke only:",
      "```bash",
      "python -m robot --include smoke --outputdir results tests",
      "```",
      "",
      "Minimal `.github/workflows/robot.yml`:",
      "```yaml",
      "name: Robot Framework",
      "on: [push, pull_request]",
      "jobs:",
      "  robot:",
      "    runs-on: ubuntu-latest",
      "    steps:",
      "      - uses: actions/checkout@v4",
      "      - uses: actions/setup-python@v5",
      "        with:",
      "          python-version: '3.13'",
      "      - run: python -m pip install robotframework==7.4.2",
      "      - run: python -m robot --outputdir results tests",
      "      - uses: actions/upload-artifact@v4",
      "        if: always()",
      "        with:",
      "          name: robot-results",
      "          path: results/",
      "```",
      "",
      "This CI example is core-only, so it does not need browser binaries or external credentials."
    ].join("\n"),
    conceptUk: [
      "Robot Framework генерує `output.xml`, `log.html` і `report.html`. Tags зручно використовувати як execution semantics для smoke, regression і slow suites. У CI зберігайте original result bundle як artifacts.",
      "",
      "Створіть `tests/smoke.robot`:",
      "```robotframework",
      "*** Test Cases ***",
      "Fast Smoke",
      "    [Tags]    smoke",
      "    Should Be Equal    GimmeJob    GimmeJob",
      "",
      "Slow Regression",
      "    [Tags]    regression    slow",
      "    Sleep    0.01s",
      "    Should Be True    ${True}",
      "```",
      "",
      "Запустіть лише smoke:",
      "```bash",
      "python -m robot --include smoke --outputdir results tests",
      "```",
      "",
      "Мінімальний `.github/workflows/robot.yml`:",
      "```yaml",
      "name: Robot Framework",
      "on: [push, pull_request]",
      "jobs:",
      "  robot:",
      "    runs-on: ubuntu-latest",
      "    steps:",
      "      - uses: actions/checkout@v4",
      "      - uses: actions/setup-python@v5",
      "        with:",
      "          python-version: '3.13'",
      "      - run: python -m pip install robotframework==7.4.2",
      "      - run: python -m robot --outputdir results tests",
      "      - uses: actions/upload-artifact@v4",
      "        if: always()",
      "        with:",
      "          name: robot-results",
      "          path: results/",
      "```",
      "",
      "Цей CI example core-only, тому не потребує browser binaries або external credentials."
    ].join("\n"),
    keyPoints: [
      "Tags should control execution slices, not be decorative metadata",
      "Upload Robot reports with `if: always()` so failing runs keep their evidence",
      "CI examples must include dependency installation and real test files",
    ],
    keyPointsUk: [
      "Tags мають керувати execution slices, а не бути decorative metadata",
      "Завантажуйте Robot reports з `if: always()`, щоб failing runs зберігали evidence",
      "CI examples мають містити dependency installation і real test files",
    ],
    pitfalls: ["Showing isolated `robot --include` commands without any tagged suite to execute"],
    pitfallsUk: ["Показувати окремі `robot --include` commands без tagged suite для execution"],
    exercise: "Run the tagged suite locally, then use the workflow in a small repository and confirm the artifact appears after a deliberately failing run.",
    exerciseUk: "Запустіть tagged suite локально, потім використайте workflow у small repository і перевірте artifact після навмисно failing run.",
    tags: ["robot-framework", "ci", "tags", "reporting", "github-actions"],
    sourceIds: ["robot-framework-user-guide", "robot-framework-ci", "robot-framework-guides"],
  },
];

export default robotFrameworkModule;
