export const robotFrameworkModule = {
  id: "robot-framework",
  label: "Robot Framework",
  labelUk: "Robot Framework",
  level: "Intermediate",
  description: "Complete Robot Framework guide: syntax, variables, keywords, control flow, lifecycle, libraries, Browser/API automation, Python extensions, reporting, parallel execution, CI and architecture.",
  descriptionUk: "Повний guide з Robot Framework: syntax, variables, keywords, control flow, lifecycle, libraries, Browser/API automation, Python extensions, reporting, parallel execution, CI та architecture.",
  introMarkdown: [
      "## Robot Framework: complete learning path",
      "",
      "Robot Framework is a generic keyword-driven automation framework. It is actively maintained in 2026; Robot Framework 7.5 was released on September 14, 2026. It remains especially useful where readable keyword-level tests, mixed Python/keyword teams, reusable domain libraries, embedded or system testing, API testing, and heterogeneous automation matter. For a new code-heavy web-only project, native Playwright with pytest or TypeScript may still be the simpler default; this guide teaches Robot Framework deeply so you can make that choice deliberately.",
      "",
      "The path starts with the data format and execution model, then moves through variables, user keywords, control flow, failure handling, setup/teardown, project structure, standard libraries, data-driven testing, Browser Library, API testing, Python extensions, tooling, parallel execution, CI and maintainable architecture. Examples are complete enough to run locally. Robot Framework cannot honestly execute inside GimmeJob's restricted browser Python sandbox, so Robot, shell and YAML blocks are rendered as static code rather than showing a misleading Run button.",
    ].join("\n"),
  introMarkdownUk: [
      "## Robot Framework: повний learning path",
      "",
      "Robot Framework — generic keyword-driven automation framework. Він активно підтримується у 2026 році; Robot Framework 7.5 вийшов 14 вересня 2026 року. Він особливо корисний там, де важливі читабельні keyword-level тести, змішані Python/keyword команди, reusable domain libraries, embedded або system testing, API testing і heterogeneous automation. Для нового code-heavy web-only проєкту native Playwright із pytest або TypeScript усе ще може бути простішим default; цей guide розбирає Robot Framework достатньо глибоко, щоб такий вибір був усвідомленим.",
      "",
      "Path починається з data format і execution model, далі проходить variables, user keywords, control flow, failure handling, setup/teardown, project structure, standard libraries, data-driven testing, Browser Library, API testing, Python extensions, tooling, parallel execution, CI та maintainable architecture. Приклади достатньо повні для локального запуску. Robot Framework не можна чесно виконувати у restricted browser Python sandbox GimmeJob, тому Robot, shell і YAML blocks рендеряться як static code без misleading Run button.",
    ].join("\n"),
  sourceIds: ["robot-framework-user-guide", "robot-framework-guides", "robot-framework-releases", "robot-framework-standard-libraries", "robot-framework-browser", "robot-framework-requests", "robot-framework-python-library", "robot-framework-libdoc", "robot-framework-pabot", "robot-framework-ci"],
};

export const robotFrameworkSources = [
  {
    id: "robot-framework-user-guide",
    title: "Robot Framework User Guide",
    url: "https://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html",
    publisher: "Robot Framework Foundation",
    kind: "Official documentation",
    role: "Core syntax, variables, control structures, suites, execution, output files and extension APIs",
  },
  {
    id: "robot-framework-guides",
    title: "Robot Framework Guides",
    url: "https://docs.robotframework.org/docs",
    publisher: "Robot Framework Foundation",
    kind: "Official guides",
    role: "Getting started, project structure, libraries, examples and CI guidance",
  },
  {
    id: "robot-framework-releases",
    title: "Robot Framework releases",
    url: "https://github.com/robotframework/robotframework/releases",
    publisher: "Robot Framework",
    kind: "Official release history",
    role: "Current stable releases, maintenance status and release notes",
  },
  {
    id: "robot-framework-standard-libraries",
    title: "Robot Framework Standard Libraries",
    url: "https://robotframework.org/robotframework/#standard-libraries",
    publisher: "Robot Framework Foundation",
    kind: "Official documentation",
    role: "BuiltIn, Collections, String, DateTime, OperatingSystem, Process, XML and other bundled libraries",
  },
  {
    id: "robot-framework-browser",
    title: "Robot Framework Browser",
    url: "https://robotframework-browser.org/docs/",
    publisher: "Robot Framework Browser contributors",
    kind: "Official documentation",
    role: "Playwright-backed web automation, locators, assertions, waiting and browser lifecycle",
  },
  {
    id: "robot-framework-requests",
    title: "Robot Framework RequestsLibrary",
    url: "https://marketsquare.github.io/robotframework-requests/doc/RequestsLibrary.html",
    publisher: "MarketSquare / RequestsLibrary contributors",
    kind: "Official library documentation",
    role: "HTTP API testing with sessionless and session-based requests",
  },
  {
    id: "robot-framework-python-library",
    title: "Robot Framework Python libraries",
    url: "https://docs.robotframework.org/docs/extending_robot_framework/custom-libraries/python_library",
    publisher: "Robot Framework Foundation",
    kind: "Official guide",
    role: "Creating custom keywords and libraries in Python",
  },
  {
    id: "robot-framework-libdoc",
    title: "Libdoc",
    url: "https://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#libdoc",
    publisher: "Robot Framework Foundation",
    kind: "Official documentation",
    role: "Generating and inspecting library and resource-file documentation",
  },
  {
    id: "robot-framework-pabot",
    title: "Running tests in parallel with Pabot",
    url: "https://docs.robotframework.org/docs/parallel",
    publisher: "Robot Framework Foundation",
    kind: "Official guide",
    role: "Parallel suite/test execution, process count, sharding and shared resources",
  },
  {
    id: "robot-framework-ci",
    title: "Robot Framework in GitHub Actions",
    url: "https://docs.robotframework.org/docs/using_rf_in_ci_systems/ci/github-actions",
    publisher: "Robot Framework Foundation",
    kind: "Official guide",
    role: "Running Robot Framework in CI and preserving reports",
  },
];

export const robotFrameworkLessons = [
  {
    id: "ta-lesson-robot-framework-core",
    moduleId: "robot-framework",
    level: "Intermediate",
    order: 44,
    title: "Execution model, installation and the first suite",
    titleUk: "Execution model, installation і перший suite",
    summary: "Understand what Robot executes before learning the syntax details.",
    summaryUk: "Спочатку зрозумійте, що саме виконує Robot, а вже потім вчіть деталі syntax.",
    concept: [
      "Robot Framework reads plain-text test data, resolves keywords, executes them through the core or imported libraries, and produces machine-readable plus human-readable results. A `.robot` file is usually a suite; directories form higher-level suites. Tests should describe intent, while reusable keywords and libraries hide implementation mechanics.",
      "",
      "### Install",
      "",
      "```bash",
      "python -m venv .venv",
      "# Windows PowerShell: .\\.venv\\Scripts\\Activate.ps1",
      "# Linux/macOS: source .venv/bin/activate",
      "python -m pip install robotframework==7.5",
      "```",
      "",
      "Create `first.robot`:",
      "",
      "```robotframework",
      "*** Variables ***",
      "${ENV}    staging",
      "",
      "*** Test Cases ***",
      "Environment Is Staging",
      "    Log    Starting smoke test",
      "    Should Be Equal    ${ENV}    staging",
      "",
      "Simple Calculation Works",
      "    ${total}=    Evaluate    10 + 15",
      "    Should Be Equal As Integers    ${total}    25",
      "```",
      "",
      "Run it:",
      "",
      "```bash",
      "python -m robot --outputdir results first.robot",
      "```",
      "",
      "The console should report `2 tests, 2 passed`. The result directory contains `output.xml`, `log.html` and `report.html`. `output.xml` is the canonical result model used by Robot tooling; the HTML files are generated views for humans.",
      "",
      "Use `python -m robot` rather than relying on a globally installed `robot` executable when you want to guarantee that the active virtual environment is used.",
    ].join("\n"),
    conceptUk: [
      "Robot Framework читає plain-text test data, знаходить keywords, виконує їх через core або imported libraries і створює machine-readable та human-readable результати. `.robot` файл зазвичай є suite; каталоги формують suites вищого рівня. Тести мають описувати intent, а reusable keywords і libraries — ховати implementation mechanics.",
      "",
      "### Install",
      "",
      "```bash",
      "python -m venv .venv",
      "# Windows PowerShell: .\\.venv\\Scripts\\Activate.ps1",
      "# Linux/macOS: source .venv/bin/activate",
      "python -m pip install robotframework==7.5",
      "```",
      "",
      "Створіть `first.robot`:",
      "",
      "```robotframework",
      "*** Variables ***",
      "${ENV}    staging",
      "",
      "*** Test Cases ***",
      "Environment Is Staging",
      "    Log    Starting smoke test",
      "    Should Be Equal    ${ENV}    staging",
      "",
      "Simple Calculation Works",
      "    ${total}=    Evaluate    10 + 15",
      "    Should Be Equal As Integers    ${total}    25",
      "```",
      "",
      "Запуск:",
      "",
      "```bash",
      "python -m robot --outputdir results first.robot",
      "```",
      "",
      "У console має бути `2 tests, 2 passed`. У result directory з'являться `output.xml`, `log.html` і `report.html`. `output.xml` — canonical result model, який використовують Robot tools; HTML files — представлення для людей.",
      "",
      "`python -m robot` краще за global `robot`, коли потрібно гарантувати використання саме active virtual environment.",
    ].join("\n"),
    keyPoints: ["A suite is executable test data; keywords provide behavior", "`output.xml` is the primary result data and HTML files are views", "Pin the framework version in reproducible projects"],
    keyPointsUk: ["Suite — executable test data; keywords надають behavior", "`output.xml` — primary result data, а HTML files — views", "У reproducible projects фіксуйте framework version"],
    pitfalls: ["Installing Robot globally and then unknowingly running a different interpreter or version"],
    pitfallsUk: ["Встановити Robot global і непомітно запускати інший interpreter або version"],
    tags: ["robot-framework", "installation", "execution"],
    sourceIds: ["robot-framework-user-guide", "robot-framework-releases", "robot-framework-guides"],
  },
  {
    id: "ta-lesson-robot-framework-syntax",
    moduleId: "robot-framework",
    level: "Intermediate",
    order: 45,
    title: "File format, sections, cells, names and documentation",
    titleUk: "File format, sections, cells, names і documentation",
    summary: "Learn how Robot parses a file so whitespace and sections stop feeling magical.",
    summaryUk: "Розберіться, як Robot парсить файл, щоб whitespace і sections не виглядали магією.",
    concept: [
      "Robot test data is tabular even though it looks like indented text. A cell boundary is two or more spaces, a tab, or the pipe-separated format. Indentation is for readability and to show bodies of tests, keywords and control structures, but the parser fundamentally works with cells.",
      "",
      "The main sections are `*** Settings ***`, `*** Variables ***`, `*** Test Cases ***`, `*** Tasks ***`, `*** Keywords ***` and `*** Comments ***`. Test suites use either Test Cases or Tasks, not both for normal usage.",
      "",
      "```robotframework",
      "*** Settings ***",
      "Documentation    Small syntax example",
      "Library          Collections",
      "",
      "*** Variables ***",
      "${USER}          Alice",
      "@{ROLES}         reader    editor",
      "",
      "*** Test Cases ***",
      "Readable Test Name",
      "    [Documentation]    A test-level setting starts with square brackets.",
      "    [Tags]    smoke    users",
      "    Log    User=${USER}",
      "    Length Should Be    ${ROLES}    2",
      "",
      "*** Keywords ***",
      "Log User",
      "    [Arguments]    ${name}",
      "    Log    ${name}",
      "```",
      "",
      "Keyword and variable matching is forgiving about case, spaces and underscores, but you should still use consistent naming. Treat two-space cell separation as syntax, not formatting. Align columns if it helps reading, but do not depend on visual alignment to express meaning.",
      "",
      "Comments can start with `#` in a cell. Use `[Documentation]` for durable intent, constraints or rationale that should appear in generated logs and documentation. Avoid comments that merely restate the next keyword.",
    ].join("\n"),
    conceptUk: [
      "Robot test data є tabular, хоча виглядає як indented text. Межа cell — два або більше пробілів, tab або pipe-separated format. Indentation покращує читабельність і показує bodies tests, keywords і control structures, але parser фактично працює з cells.",
      "",
      "Основні sections: `*** Settings ***`, `*** Variables ***`, `*** Test Cases ***`, `*** Tasks ***`, `*** Keywords ***` і `*** Comments ***`. У звичайному suite використовуйте або Test Cases, або Tasks.",
      "",
      "```robotframework",
      "*** Settings ***",
      "Documentation    Small syntax example",
      "Library          Collections",
      "",
      "*** Variables ***",
      "${USER}          Alice",
      "@{ROLES}         reader    editor",
      "",
      "*** Test Cases ***",
      "Readable Test Name",
      "    [Documentation]    A test-level setting starts with square brackets.",
      "    [Tags]    smoke    users",
      "    Log    User=${USER}",
      "    Length Should Be    ${ROLES}    2",
      "",
      "*** Keywords ***",
      "Log User",
      "    [Arguments]    ${name}",
      "    Log    ${name}",
      "```",
      "",
      "Keyword і variable matching толерантний до case, spaces та underscores, але naming усе одно має бути consistent. Два пробіли між cells — це syntax, а не cosmetic formatting. Вирівнюйте columns для читабельності, але не вкладайте meaning лише у visual alignment.",
      "",
      "Comments можуть починатися з `#` у cell. `[Documentation]` використовуйте для стабільного intent, constraints або rationale, які мають потрапляти в logs і generated documentation. Не пишіть comments, що просто повторюють наступний keyword.",
    ].join("\n"),
    keyPoints: ["Two or more spaces separate cells", "Sections define what each table means", "Prefer documentation that explains intent or constraints"],
    keyPointsUk: ["Два або більше пробілів розділяють cells", "Sections визначають meaning кожної table", "Documentation має пояснювати intent або constraints"],
    pitfalls: ["Using a single visual space where a new Robot cell was intended"],
    pitfallsUk: ["Використовувати один visual space там, де очікується новий Robot cell"],
    tags: ["robot-framework", "syntax", "documentation"],
    sourceIds: ["robot-framework-user-guide"],
  },
  {
    id: "ta-lesson-robot-framework-variables",
    moduleId: "robot-framework",
    level: "Intermediate",
    order: 46,
    title: "Variables, collections, scopes, types and secrets",
    titleUk: "Variables, collections, scopes, types і secrets",
    summary: "Use Robot variables deliberately instead of turning them into hidden global state.",
    summaryUk: "Використовуйте Robot variables усвідомлено, а не як hidden global state.",
    concept: [
      "Robot has scalar `${x}`, list `@{items}`, dictionary `&{config}` and environment `%{NAME}` syntax. The scalar form can hold any Python object; the prefix mostly controls how a value is expanded when passed to a keyword.",
      "",
      "```robotframework",
      "*** Variables ***",
      "${BASE_URL}         https://example.org",
      "@{ROLES}            reader    editor",
      "&{USER}             name=Alice    active=${True}",
      "${RETRIES: int}     3",
      "",
      "*** Test Cases ***",
      "Collections And Types",
      "    Log    ${USER}[name]",
      "    Log Many    @{ROLES}",
      "    Should Be Equal As Integers    ${RETRIES}    3",
      "```",
      "",
      "Robot 7.x also has the `VAR` syntax. Local scope is the default; `scope=TEST`, `SUITE`, `SUITES` or `GLOBAL` widens visibility. Prefer return values and local variables. Wider scopes are useful for lifecycle state, but they make dependencies less obvious.",
      "",
      "```robotframework",
      "*** Test Cases ***",
      "Scoped Value",
      "    VAR    ${token}    abc",
      "    VAR    ${suite_mode}    smoke    scope=SUITE",
      "    Should Be Equal    ${token}    abc",
      "```",
      "",
      "Variable priorities matter: command-line variables can override data-file values, which is useful for environment configuration.",
      "",
      "Robot Framework 7.4 introduced secret variables, and 7.5 keeps them available. A `Secret` prevents the normal string representation from exposing the value in Robot logs, but it does not encrypt the value. Create secrets from environment variables rather than literals:",
      "",
      "```robotframework",
      "*** Variables ***",
      "${API_TOKEN: Secret}    %{API_TOKEN}",
      "```",
      "",
      "Do not access `${API_TOKEN.value}` in test data unless you intentionally want to expose the underlying value.",
    ].join("\n"),
    conceptUk: [
      "Robot має scalar `${x}`, list `@{items}`, dictionary `&{config}` та environment `%{NAME}` syntax. Scalar form може зберігати будь-який Python object; prefix переважно визначає, як value expand'иться при передачі keyword.",
      "",
      "```robotframework",
      "*** Variables ***",
      "${BASE_URL}         https://example.org",
      "@{ROLES}            reader    editor",
      "&{USER}             name=Alice    active=${True}",
      "${RETRIES: int}     3",
      "",
      "*** Test Cases ***",
      "Collections And Types",
      "    Log    ${USER}[name]",
      "    Log Many    @{ROLES}",
      "    Should Be Equal As Integers    ${RETRIES}    3",
      "```",
      "",
      "У Robot 7.x є `VAR` syntax. Default scope — local; `scope=TEST`, `SUITE`, `SUITES` або `GLOBAL` розширює visibility. Віддавайте перевагу return values і local variables. Wider scopes корисні для lifecycle state, але роблять dependencies менш очевидними.",
      "",
      "```robotframework",
      "*** Test Cases ***",
      "Scoped Value",
      "    VAR    ${token}    abc",
      "    VAR    ${suite_mode}    smoke    scope=SUITE",
      "    Should Be Equal    ${token}    abc",
      "```",
      "",
      "Variable priorities важливі: command-line variables можуть override values із data files, що зручно для environment configuration.",
      "",
      "Robot Framework 7.4 додав secret variables, і 7.5 їх підтримує. `Secret` не показує звичайне string representation у Robot logs, але не encrypt'ить value. Secrets краще створювати з environment variables, а не literals:",
      "",
      "```robotframework",
      "*** Variables ***",
      "${API_TOKEN: Secret}    %{API_TOKEN}",
      "```",
      "",
      "Не звертайтесь до `${API_TOKEN.value}` у test data, якщо не хочете навмисно розкрити underlying value.",
    ].join("\n"),
    keyPoints: ["`${x}` can hold any object; `@{x}` and `&{x}` control expansion", "Prefer local scope and return values over global mutation", "Secret variables reduce log exposure but are not encryption"],
    keyPointsUk: ["`${x}` може містити будь-який object; `@{x}` і `&{x}` керують expansion", "Віддавайте перевагу local scope і return values замість global mutation", "Secret variables зменшують exposure у logs, але не є encryption"],
    pitfalls: ["Using suite/global variables as a convenient substitute for explicit keyword inputs"],
    pitfallsUk: ["Використовувати suite/global variables замість explicit keyword inputs"],
    tags: ["robot-framework", "variables", "secrets", "typing"],
    sourceIds: ["robot-framework-user-guide", "robot-framework-releases"],
  },
  {
    id: "ta-lesson-robot-framework-keywords",
    moduleId: "robot-framework",
    level: "Intermediate",
    order: 47,
    title: "User keywords, arguments, returns and reusable interfaces",
    titleUk: "User keywords, arguments, returns і reusable interfaces",
    summary: "Design keywords as small APIs with clear inputs, outputs and responsibility.",
    summaryUk: "Проєктуйте keywords як маленькі APIs з чіткими inputs, outputs і responsibility.",
    concept: [
      "User keywords are Robot Framework's main composition mechanism. A good keyword has one clear responsibility, explicit arguments, a useful return value when needed, and a name that communicates domain intent.",
      "",
      "```robotframework",
      "*** Keywords ***",
      "Build Greeting",
      "    [Arguments]    ${name}    ${prefix}=Hello",
      "    ${message}=    Set Variable    ${prefix}, ${name}!",
      "    RETURN    ${message}",
      "",
      "Validate User",
      "    [Arguments]    ${user}    @{required_roles}",
      "    Should Not Be Empty    ${user}[name]",
      "    FOR    ${role}    IN    @{required_roles}",
      "        List Should Contain Value    ${user}[roles]    ${role}",
      "    END",
      "```",
      "",
      "Arguments can be positional, have defaults, accept varargs (`@{args}`) and named arguments (`&{kwargs}`). Use named arguments at call sites when a call would otherwise be ambiguous. `RETURN` is the modern explicit return syntax.",
      "",
      "Embedded arguments can make domain language readable:",
      "",
      "```robotframework",
      "*** Keywords ***",
      "User ${name} Has Role ${role}",
      "    Log    Checking ${name} / ${role}",
      "```",
      "",
      "Use them selectively. Overly natural-language-like keywords can become hard to search, refactor and debug.",
      "",
      "Robot 7 supports private user keywords through the `robot:private` tag. Use private keywords for implementation details inside one resource file, while exposing a smaller stable public keyword API.",
    ].join("\n"),
    conceptUk: [
      "User keywords — головний composition mechanism Robot Framework. Хороший keyword має одну чітку responsibility, explicit arguments, корисний return value за потреби та name, який передає domain intent.",
      "",
      "```robotframework",
      "*** Keywords ***",
      "Build Greeting",
      "    [Arguments]    ${name}    ${prefix}=Hello",
      "    ${message}=    Set Variable    ${prefix}, ${name}!",
      "    RETURN    ${message}",
      "",
      "Validate User",
      "    [Arguments]    ${user}    @{required_roles}",
      "    Should Not Be Empty    ${user}[name]",
      "    FOR    ${role}    IN    @{required_roles}",
      "        List Should Contain Value    ${user}[roles]    ${role}",
      "    END",
      "```",
      "",
      "Arguments можуть бути positional, мати defaults, приймати varargs (`@{args}`) і named arguments (`&{kwargs}`). На call site використовуйте named arguments, якщо без них виклик ambiguous. `RETURN` — сучасний explicit return syntax.",
      "",
      "Embedded arguments можуть зробити domain language читабельнішим:",
      "",
      "```robotframework",
      "*** Keywords ***",
      "User ${name} Has Role ${role}",
      "    Log    Checking ${name} / ${role}",
      "```",
      "",
      "Використовуйте їх вибірково. Надто natural-language-like keywords складніше search'ити, refactor'ити та debug'ити.",
      "",
      "Robot 7 підтримує private user keywords через tag `robot:private`. Private keywords доречні для implementation details всередині одного resource file; назовні краще expose'ити менший stable public keyword API.",
    ].join("\n"),
    keyPoints: ["Treat keywords as APIs, not macros", "Use explicit arguments and returns", "Keep a small public domain-keyword surface and hide technical helpers"],
    keyPointsUk: ["Сприймайте keywords як APIs, а не macros", "Використовуйте explicit arguments і returns", "Тримайте невеликий public domain-keyword surface, а technical helpers ховайте"],
    pitfalls: ["Creating giant keywords that mix setup, action, assertions and cleanup"],
    pitfallsUk: ["Створювати giant keywords, які змішують setup, action, assertions і cleanup"],
    tags: ["robot-framework", "keywords", "arguments", "architecture"],
    sourceIds: ["robot-framework-user-guide"],
  },
  {
    id: "ta-lesson-robot-framework-control-flow",
    moduleId: "robot-framework",
    level: "Intermediate",
    order: 48,
    title: "IF, FOR, WHILE, BREAK and CONTINUE",
    titleUk: "IF, FOR, WHILE, BREAK і CONTINUE",
    summary: "Use native control structures when the test really needs branching or iteration.",
    summaryUk: "Використовуйте native control structures, коли тесту справді потрібні branching або iteration.",
    concept: [
      "Modern Robot Framework has native `IF/ELSE`, `FOR`, `WHILE`, `BREAK` and `CONTINUE`. Prefer these structures over old `Run Keyword If`-style patterns for new code because the flow is visible and nestable.",
      "",
      "```robotframework",
      "*** Test Cases ***",
      "Control Flow",
      "    ${status}=    Set Variable    ready",
      "    IF    $status == \"ready\"",
      "        Log    Continue",
      "    ELSE",
      "        Fail    Unexpected status: ${status}",
      "    END",
      "",
      "    FOR    ${value}    IN    alpha    beta    gamma",
      "        IF    $value == \"beta\"",
      "            CONTINUE",
      "        END",
      "        Log    ${value}",
      "    END",
      "```",
      "",
      "Inside expression-based conditions, `$variable` exposes the underlying Python value directly. `${variable}` is replaced before expression evaluation and can create quoting problems with arbitrary strings, so `$variable` is often safer for expressions.",
      "",
      "`WHILE` is useful for bounded polling or iterative flows:",
      "",
      "```robotframework",
      "VAR    ${attempt}    0",
      "WHILE    $attempt < 3",
      "    ${attempt}=    Evaluate    $attempt + 1",
      "    Log    Attempt ${attempt}",
      "END",
      "```",
      "",
      "Do not use a loop to hide missing synchronization. For UI automation, use the library's waiting/assertion mechanisms instead of repeatedly sleeping and checking DOM state yourself.",
    ].join("\n"),
    conceptUk: [
      "Сучасний Robot Framework має native `IF/ELSE`, `FOR`, `WHILE`, `BREAK` і `CONTINUE`. Для нового коду вони кращі за old `Run Keyword If` patterns, бо flow видимий і нормально nest'иться.",
      "",
      "```robotframework",
      "*** Test Cases ***",
      "Control Flow",
      "    ${status}=    Set Variable    ready",
      "    IF    $status == \"ready\"",
      "        Log    Continue",
      "    ELSE",
      "        Fail    Unexpected status: ${status}",
      "    END",
      "",
      "    FOR    ${value}    IN    alpha    beta    gamma",
      "        IF    $value == \"beta\"",
      "            CONTINUE",
      "        END",
      "        Log    ${value}",
      "    END",
      "```",
      "",
      "В expression conditions `$variable` передає underlying Python value напряму. `${variable}` substitute'иться до evaluation і може створювати проблеми з quoting для arbitrary strings, тому `$variable` часто безпечніший.",
      "",
      "`WHILE` корисний для bounded polling або iterative flows:",
      "",
      "```robotframework",
      "VAR    ${attempt}    0",
      "WHILE    $attempt < 3",
      "    ${attempt}=    Evaluate    $attempt + 1",
      "    Log    Attempt ${attempt}",
      "END",
      "```",
      "",
      "Не використовуйте loop, щоб приховати відсутність synchronization. Для UI automation краще використовувати waiting/assertion mechanisms самої library, а не вручну повторювати sleeps і DOM checks.",
    ].join("\n"),
    keyPoints: ["Prefer native control structures for new code", "Use `$var` in expressions when you need the underlying object", "Bound every polling loop"],
    keyPointsUk: ["Для нового коду використовуйте native control structures", "У expressions використовуйте `$var`, коли потрібен underlying object", "Кожен polling loop має бути bounded"],
    pitfalls: ["Replacing proper library synchronization with `WHILE` plus `Sleep`"],
    pitfallsUk: ["Замінювати proper library synchronization на `WHILE` плюс `Sleep`"],
    tags: ["robot-framework", "control-flow", "loops"],
    sourceIds: ["robot-framework-user-guide"],
  },
  {
    id: "ta-lesson-robot-framework-errors",
    moduleId: "robot-framework",
    level: "Intermediate",
    order: 49,
    title: "Failures, TRY/EXCEPT and expected negative paths",
    titleUk: "Failures, TRY/EXCEPT і expected negative paths",
    summary: "Handle only failures you actually expect; let unexpected failures fail the test.",
    summaryUk: "Обробляйте лише ті failures, які справді очікуєте; unexpected failures мають валити тест.",
    concept: [
      "By default, a failing keyword stops the current test body and Robot continues with teardown. This fail-fast behavior is usually desirable. Catch failures only when failure is part of the expected scenario.",
      "",
      "Native `TRY/EXCEPT/ELSE/FINALLY` matches Robot failure messages:",
      "",
      "```robotframework",
      "*** Test Cases ***",
      "Expected Failure Path",
      "    TRY",
      "        Should Be Equal    actual    expected",
      "    EXCEPT    actual != expected",
      "        Log    Expected mismatch was observed",
      "    ELSE",
      "        Fail    The comparison unexpectedly passed",
      "    FINALLY",
      "        Log    Always executed",
      "    END",
      "```",
      "",
      "`EXCEPT` can match literal messages or use `type=GLOB`, `REGEXP` or `START`. Avoid a broad catch-all unless the test truly accepts any failure; otherwise a network error or broken locator can be mistaken for the expected business rejection.",
      "",
      "BuiltIn also contains keywords such as `Run Keyword And Return Status` and `Run Keyword And Expect Error`. They are useful for compact negative checks, but native TRY blocks are often clearer once handling becomes multi-step.",
      "",
      "Continue-on-failure features exist, especially in teardowns, but do not use them to collect dozens of unrelated failures in one test. A test should still represent one coherent behavior.",
    ].join("\n"),
    conceptUk: [
      "За default failing keyword зупиняє current test body, після чого Robot переходить до teardown. Такий fail-fast зазвичай правильний. Catch failures лише тоді, коли failure є частиною expected scenario.",
      "",
      "Native `TRY/EXCEPT/ELSE/FINALLY` працює з Robot failure messages:",
      "",
      "```robotframework",
      "*** Test Cases ***",
      "Expected Failure Path",
      "    TRY",
      "        Should Be Equal    actual    expected",
      "    EXCEPT    actual != expected",
      "        Log    Expected mismatch was observed",
      "    ELSE",
      "        Fail    The comparison unexpectedly passed",
      "    FINALLY",
      "        Log    Always executed",
      "    END",
      "```",
      "",
      "`EXCEPT` може match'ити literal messages або використовувати `type=GLOB`, `REGEXP` чи `START`. Уникайте broad catch-all, якщо тест не приймає literally any failure; інакше network error або broken locator можна помилково прийняти за expected business rejection.",
      "",
      "BuiltIn також має `Run Keyword And Return Status` і `Run Keyword And Expect Error`. Вони зручні для компактних negative checks, але native TRY blocks зазвичай ясніші для multi-step handling.",
      "",
      "Continue-on-failure features існують, особливо в teardowns, але не використовуйте їх для збору десятків unrelated failures в одному тесті. Один test має представляти coherent behavior.",
    ].join("\n"),
    keyPoints: ["Unexpected failures should normally propagate", "Match expected errors narrowly", "FINALLY is for unconditional cleanup or evidence, not for hiding failures"],
    keyPointsUk: ["Unexpected failures зазвичай мають propagate'итись", "Expected errors match'те вузько", "FINALLY — для unconditional cleanup/evidence, а не для приховування failures"],
    pitfalls: ["Catching every error and converting infrastructure failures into a passing negative test"],
    pitfallsUk: ["Catch'ити кожну error і перетворювати infrastructure failures на passing negative test"],
    tags: ["robot-framework", "error-handling", "negative-testing"],
    sourceIds: ["robot-framework-user-guide"],
  },
  {
    id: "ta-lesson-robot-framework-lifecycle",
    moduleId: "robot-framework",
    level: "Intermediate",
    order: 50,
    title: "Suite, test and keyword setup/teardown",
    titleUk: "Suite, test і keyword setup/teardown",
    summary: "Make lifecycle ownership explicit and guarantee cleanup even after failures.",
    summaryUk: "Зробіть lifecycle ownership явним і гарантуйте cleanup навіть після failures.",
    concept: [
      "Robot supports suite, test and user-keyword setup/teardown. Setups establish preconditions; teardowns release resources and are executed even when the corresponding body fails.",
      "",
      "```robotframework",
      "*** Settings ***",
      "Suite Setup       Start Environment",
      "Suite Teardown    Stop Environment",
      "Test Setup        Reset Test Data",
      "Test Teardown     Capture Evidence And Clean Up",
      "",
      "*** Test Cases ***",
      "Uses Default Lifecycle",
      "    Do Something",
      "",
      "Overrides Setup",
      "    [Setup]    Prepare Special State",
      "    Do Something Else",
      "```",
      "",
      "A failed suite setup prevents tests in that suite from running. A suite teardown still runs. A test teardown runs even if the test setup or test body fails. Teardown keywords themselves use continue-on-failure semantics so cleanup steps are attempted even when an earlier cleanup step fails.",
      "",
      "Directories can define suite initialization with `__init__.robot`. This is useful for directory-level suite setup, teardown, metadata and other shared suite settings, but only initialization files that belong to the executed suite hierarchy take effect.",
      "",
      "Robot 7 also supports `[Setup]` and `[Teardown]` for user keywords. Use keyword teardown when a reusable keyword opens a temporary resource that it must close regardless of the body result.",
    ].join("\n"),
    conceptUk: [
      "Robot підтримує suite, test і user-keyword setup/teardown. Setups створюють preconditions; teardowns звільняють resources і виконуються навіть при failure відповідного body.",
      "",
      "```robotframework",
      "*** Settings ***",
      "Suite Setup       Start Environment",
      "Suite Teardown    Stop Environment",
      "Test Setup        Reset Test Data",
      "Test Teardown     Capture Evidence And Clean Up",
      "",
      "*** Test Cases ***",
      "Uses Default Lifecycle",
      "    Do Something",
      "",
      "Overrides Setup",
      "    [Setup]    Prepare Special State",
      "    Do Something Else",
      "```",
      "",
      "Failed suite setup не дає tests у цьому suite запускатися. Suite teardown усе одно виконується. Test teardown виконується навіть при failure test setup або test body. Teardown keywords самі мають continue-on-failure semantics, тому cleanup steps намагаються виконатись навіть після failure одного з них.",
      "",
      "Каталоги можуть визначати suite initialization через `__init__.robot`. Це корисно для directory-level suite setup, teardown, metadata та shared suite settings, але effect мають лише initialization files, які входять у реально executed suite hierarchy.",
      "",
      "Robot 7 також підтримує `[Setup]` і `[Teardown]` для user keywords. Keyword teardown доречний, якщо reusable keyword відкриває temporary resource і має закрити його незалежно від результату body.",
    ].join("\n"),
    keyPoints: ["Put resource ownership at the narrowest lifecycle that can manage it safely", "Teardowns are guaranteed cleanup paths, not optional final steps", "A failed suite setup prevents child tests from executing"],
    keyPointsUk: ["Resource ownership має бути на найвужчому lifecycle level, який безпечно ним керує", "Teardowns — guaranteed cleanup paths, а не optional final steps", "Failed suite setup зупиняє execution child tests"],
    pitfalls: ["Opening expensive global resources per test or keeping mutable resources alive across unrelated suites"],
    pitfallsUk: ["Відкривати expensive global resources на кожен test або тримати mutable resources між unrelated suites"],
    tags: ["robot-framework", "setup", "teardown", "lifecycle"],
    sourceIds: ["robot-framework-user-guide"],
  },
  {
    id: "ta-lesson-robot-framework-resources",
    moduleId: "robot-framework",
    level: "Intermediate",
    order: 51,
    title: "Resources, variable files and project structure",
    titleUk: "Resources, variable files і project structure",
    summary: "Split domain keywords, environment data and tests into clear layers.",
    summaryUk: "Розділіть domain keywords, environment data і tests на чіткі layers.",
    concept: [
      "Resource files share Robot keywords and variables without becoming executable suites. Variable files are useful when configuration or test data is easier to express in Python. Keep path relationships simple and run from a stable project root.",
      "",
      "Example structure:",
      "",
      "```text",
      "robot-demo/",
      "├── resources/",
      "│   └── greetings.resource",
      "├── variables/",
      "│   └── env.py",
      "└── tests/",
      "    └── greetings.robot",
      "```",
      "",
      "`resources/greetings.resource`:",
      "",
      "```robotframework",
      "*** Keywords ***",
      "Build Greeting",
      "    [Arguments]    ${name}",
      "    RETURN    Hello, ${name}!",
      "```",
      "",
      "`variables/env.py`:",
      "",
      "```python",
      "ENV = \"staging\"",
      "DEFAULT_USER = \"Alice\"",
      "```",
      "",
      "`tests/greetings.robot`:",
      "",
      "```robotframework",
      "*** Settings ***",
      "Resource    ../resources/greetings.resource",
      "Variables   ../variables/env.py",
      "",
      "*** Test Cases ***",
      "Greeting Uses Provided Name",
      "    ${message}=    Build Greeting    ${DEFAULT_USER}",
      "    Should Be Equal    ${message}    Hello, Alice!",
      "    Should Be Equal    ${ENV}    staging",
      "```",
      "",
      "Run from `robot-demo/`:",
      "",
      "```bash",
      "python -m robot --outputdir results tests",
      "```",
      "",
      "Avoid a giant `common.resource`. Organize resources around a domain or technical capability: `users.resource`, `orders.resource`, `browser_session.resource`, and so on. The test file should import the public capabilities it actually uses.",
    ].join("\n"),
    conceptUk: [
      "Resource files поширюють Robot keywords і variables, але самі не є executable suites. Variable files корисні, коли configuration або test data простіше виразити на Python. Тримайте path relationships простими і запускайте з stable project root.",
      "",
      "Приклад структури:",
      "",
      "```text",
      "robot-demo/",
      "├── resources/",
      "│   └── greetings.resource",
      "├── variables/",
      "│   └── env.py",
      "└── tests/",
      "    └── greetings.robot",
      "```",
      "",
      "`resources/greetings.resource`:",
      "",
      "```robotframework",
      "*** Keywords ***",
      "Build Greeting",
      "    [Arguments]    ${name}",
      "    RETURN    Hello, ${name}!",
      "```",
      "",
      "`variables/env.py`:",
      "",
      "```python",
      "ENV = \"staging\"",
      "DEFAULT_USER = \"Alice\"",
      "```",
      "",
      "`tests/greetings.robot`:",
      "",
      "```robotframework",
      "*** Settings ***",
      "Resource    ../resources/greetings.resource",
      "Variables   ../variables/env.py",
      "",
      "*** Test Cases ***",
      "Greeting Uses Provided Name",
      "    ${message}=    Build Greeting    ${DEFAULT_USER}",
      "    Should Be Equal    ${message}    Hello, Alice!",
      "    Should Be Equal    ${ENV}    staging",
      "```",
      "",
      "Запуск із `robot-demo/`:",
      "",
      "```bash",
      "python -m robot --outputdir results tests",
      "```",
      "",
      "Уникайте giant `common.resource`. Організовуйте resources навколо domain або technical capability: `users.resource`, `orders.resource`, `browser_session.resource` тощо. Test file має import'ити лише public capabilities, які реально використовує.",
    ].join("\n"),
    keyPoints: ["Use `.resource` for shared Robot keywords and variables", "Use Python variable files when data/config benefits from Python", "Organize resources by capability, not by dumping everything into common"],
    keyPointsUk: ["Використовуйте `.resource` для shared Robot keywords і variables", "Python variable files доречні, коли data/config виграє від Python", "Організовуйте resources за capability, а не складайте все в common"],
    pitfalls: ["Creating cyclic resource imports or a monolithic shared file with unrelated keywords"],
    pitfallsUk: ["Створювати cyclic resource imports або monolithic shared file з unrelated keywords"],
    tags: ["robot-framework", "resources", "variable-files", "project-structure"],
    sourceIds: ["robot-framework-user-guide", "robot-framework-guides"],
  },
  {
    id: "ta-lesson-robot-framework-standard-libraries",
    moduleId: "robot-framework",
    level: "Intermediate",
    order: 52,
    title: "BuiltIn and the standard libraries you should know",
    titleUk: "BuiltIn і standard libraries, які варто знати",
    summary: "Know what Robot already provides before adding dependencies or Python helpers.",
    summaryUk: "Знайте, що Robot уже вміє, перш ніж додавати dependencies або Python helpers.",
    concept: [
      "`BuiltIn` is available automatically. Other standard libraries are imported explicitly. The commonly useful set includes `Collections`, `String`, `DateTime`, `OperatingSystem`, `Process` and `XML`.",
      "",
      "```robotframework",
      "*** Settings ***",
      "Library    Collections",
      "Library    String",
      "Library    DateTime",
      "Library    Process",
      "",
      "*** Test Cases ***",
      "Standard Libraries",
      "    @{items}=    Create List    alpha    beta",
      "    Append To List    ${items}    gamma",
      "    Length Should Be    ${items}    3",
      "",
      "    ${upper}=    Convert To Upper Case    robot",
      "    Should Be Equal    ${upper}    ROBOT",
      "",
      "    ${now}=    Get Current Date",
      "    Should Not Be Empty    ${now}",
      "",
      "    ${result}=    Run Process    python    --version",
      "    Should Be Equal As Integers    ${result.rc}    0",
      "```",
      "",
      "Use `OperatingSystem` for filesystem/environment operations and `Process` when the thing under test is a command-line program. `XML` can parse and assert XML structures. `Collections` provides list/dictionary assertions and mutation helpers.",
      "",
      "Do not use standard-library keywords just because they exist. If a Python helper expresses complex transformation more clearly, keep that logic in Python and expose a focused keyword. Conversely, do not write Python for a basic list assertion already provided by Collections.",
    ].join("\n"),
    conceptUk: [
      "`BuiltIn` доступний automatically. Інші standard libraries import'яться явно. Найкорисніший базовий набір: `Collections`, `String`, `DateTime`, `OperatingSystem`, `Process` і `XML`.",
      "",
      "```robotframework",
      "*** Settings ***",
      "Library    Collections",
      "Library    String",
      "Library    DateTime",
      "Library    Process",
      "",
      "*** Test Cases ***",
      "Standard Libraries",
      "    @{items}=    Create List    alpha    beta",
      "    Append To List    ${items}    gamma",
      "    Length Should Be    ${items}    3",
      "",
      "    ${upper}=    Convert To Upper Case    robot",
      "    Should Be Equal    ${upper}    ROBOT",
      "",
      "    ${now}=    Get Current Date",
      "    Should Not Be Empty    ${now}",
      "",
      "    ${result}=    Run Process    python    --version",
      "    Should Be Equal As Integers    ${result.rc}    0",
      "```",
      "",
      "`OperatingSystem` використовуйте для filesystem/environment operations, а `Process` — коли SUT є command-line program. `XML` вміє parse'ити та assert'ити XML structures. `Collections` дає list/dictionary assertions і mutation helpers.",
      "",
      "Не використовуйте standard-library keywords лише тому, що вони існують. Якщо складна transformation ясніше виглядає на Python, залиште її в Python і expose'ніть focused keyword. І навпаки, не пишіть Python для basic list assertion, який уже є в Collections.",
    ].join("\n"),
    keyPoints: ["BuiltIn is always available; other standard libraries are imported", "Prefer the simplest existing library for generic mechanics", "Use Process instead of shell-string hacks when testing subprocesses"],
    keyPointsUk: ["BuiltIn доступний завжди; інші standard libraries import'яться", "Для generic mechanics використовуйте найпростіший existing library", "Для subprocess testing краще Process, а не shell-string hacks"],
    pitfalls: ["Reimplementing standard collection or process behavior in fragile custom keywords"],
    pitfallsUk: ["Переписувати standard collection/process behavior у fragile custom keywords"],
    tags: ["robot-framework", "standard-library", "builtin", "collections"],
    sourceIds: ["robot-framework-standard-libraries", "robot-framework-user-guide"],
  },
  {
    id: "ta-lesson-robot-framework-data-driven",
    moduleId: "robot-framework",
    level: "Intermediate",
    order: 53,
    title: "Templates, tags, metadata and execution selection",
    titleUk: "Templates, tags, metadata і execution selection",
    summary: "Represent repeated behavior as data and use tags for meaningful execution slices.",
    summaryUk: "Представляйте repeated behavior як data, а tags використовуйте для meaningful execution slices.",
    concept: [
      "Test templates let one keyword define the behavior while rows provide data:",
      "",
      "```robotframework",
      "*** Settings ***",
      "Test Template    Addition Should Work",
      "Test Tags        arithmetic",
      "",
      "*** Test Cases ***       A     B     Expected",
      "Small integers           1     2     3",
      "Zeros                    0     0     0",
      "Negative value          -1     2     1",
      "",
      "*** Keywords ***",
      "Addition Should Work",
      "    [Arguments]    ${a}    ${b}    ${expected}",
      "    ${actual}=    Evaluate    int($a) + int($b)",
      "    Should Be Equal As Integers    ${actual}    ${expected}",
      "```",
      "",
      "Templates are appropriate when the same behavior is exercised with many inputs. They are not a substitute for distinct tests that have different flows.",
      "",
      "Tags are execution semantics. Use them for stable slices such as `smoke`, `regression`, `api`, `ui`, `slow` or environment requirements. Select by tag:",
      "",
      "```bash",
      "python -m robot --include smoke --exclude slow tests",
      "```",
      "",
      "Tag patterns support Boolean combinations. Keep tags lowercase and clear, especially because 7.5 deprecates ambiguous forms where Boolean operators are not separated clearly.",
      "",
      "Robot Framework 7.5 adds test/task metadata:",
      "",
      "```robotframework",
      "Example",
      "    [Metadata]    Issue    QA-123",
      "    [Metadata]    Owner    payments",
      "    Log    Test body",
      "```",
      "",
      "Use metadata for descriptive name/value information; use tags when you need filtering or grouping semantics.",
    ].join("\n"),
    conceptUk: [
      "Test templates дозволяють одному keyword визначити behavior, а rows — передавати data:",
      "",
      "```robotframework",
      "*** Settings ***",
      "Test Template    Addition Should Work",
      "Test Tags        arithmetic",
      "",
      "*** Test Cases ***       A     B     Expected",
      "Small integers           1     2     3",
      "Zeros                    0     0     0",
      "Negative value          -1     2     1",
      "",
      "*** Keywords ***",
      "Addition Should Work",
      "    [Arguments]    ${a}    ${b}    ${expected}",
      "    ${actual}=    Evaluate    int($a) + int($b)",
      "    Should Be Equal As Integers    ${actual}    ${expected}",
      "```",
      "",
      "Templates доречні, коли один behavior перевіряється на багатьох inputs. Вони не замінюють окремі tests із різними flows.",
      "",
      "Tags — це execution semantics. Використовуйте їх для stable slices на кшталт `smoke`, `regression`, `api`, `ui`, `slow` або environment requirements. Selection:",
      "",
      "```bash",
      "python -m robot --include smoke --exclude slow tests",
      "```",
      "",
      "Tag patterns підтримують Boolean combinations. Тримайте tags lowercase і clear, особливо тому, що 7.5 deprecate'ить ambiguous forms, де Boolean operators не відокремлені явно.",
      "",
      "Robot Framework 7.5 додає test/task metadata:",
      "",
      "```robotframework",
      "Example",
      "    [Metadata]    Issue    QA-123",
      "    [Metadata]    Owner    payments",
      "    Log    Test body",
      "```",
      "",
      "Metadata використовуйте для descriptive name/value information; tags — коли потрібні filtering або grouping semantics.",
    ].join("\n"),
    keyPoints: ["Templates separate repeated behavior from input rows", "Tags should correspond to execution/grouping needs", "Use metadata for descriptive pairs that should not control selection"],
    keyPointsUk: ["Templates відділяють repeated behavior від input rows", "Tags мають відповідати execution/grouping needs", "Metadata — для descriptive pairs, які не повинні керувати selection"],
    pitfalls: ["Turning every test attribute into a tag and then creating an unmanageable tag taxonomy"],
    pitfallsUk: ["Перетворювати кожен test attribute на tag і створювати некеровану tag taxonomy"],
    tags: ["robot-framework", "templates", "tags", "metadata", "data-driven"],
    sourceIds: ["robot-framework-user-guide", "robot-framework-releases"],
  },
  {
    id: "ta-lesson-robot-framework-browser",
    moduleId: "robot-framework",
    level: "Intermediate",
    order: 54,
    title: "Browser Library: web automation foundation",
    titleUk: "Browser Library: foundation web automation",
    summary: "Use the Playwright-backed Browser Library with explicit browser lifecycle and strong locators.",
    summaryUk: "Використовуйте Playwright-backed Browser Library з explicit lifecycle і strong locators.",
    concept: [
      "Browser Library is a modern web-automation library built on Playwright. It is separate from Robot core.",
      "",
      "```bash",
      "python -m pip install robotframework-browser",
      "rfbrowser init",
      "```",
      "",
      "A minimal suite:",
      "",
      "```robotframework",
      "*** Settings ***",
      "Library    Browser",
      "",
      "*** Test Cases ***",
      "Robot Framework Browser Site Opens",
      "    New Browser    chromium    headless=${True}",
      "    New Context",
      "    New Page    https://robotframework-browser.org",
      "    Get Title    *=    Robot Framework Browser",
      "    Take Screenshot",
      "    Close Browser",
      "```",
      "",
      "Run it:",
      "",
      "```bash",
      "python -m robot --outputdir results browser.robot",
      "```",
      "",
      "Think in three lifecycle levels: Browser process, Context, Page. A context isolates cookies/storage and is often the right unit for test isolation. A page is a tab.",
      "",
      "Prefer locators based on stable user-facing semantics or dedicated test IDs over brittle DOM structure. Browser Library supports CSS and other selector engines; choose locators that describe the element's identity rather than its incidental position.",
      "",
      "SeleniumLibrary also exists and is mature. Choose based on the existing project, browser requirements and team ecosystem. For a new Robot web suite, Browser Library is often the more direct route to Playwright capabilities.",
    ].join("\n"),
    conceptUk: [
      "Browser Library — modern web-automation library на основі Playwright. Вона окрема від Robot core.",
      "",
      "```bash",
      "python -m pip install robotframework-browser",
      "rfbrowser init",
      "```",
      "",
      "Мінімальний suite:",
      "",
      "```robotframework",
      "*** Settings ***",
      "Library    Browser",
      "",
      "*** Test Cases ***",
      "Robot Framework Browser Site Opens",
      "    New Browser    chromium    headless=${True}",
      "    New Context",
      "    New Page    https://robotframework-browser.org",
      "    Get Title    *=    Robot Framework Browser",
      "    Take Screenshot",
      "    Close Browser",
      "```",
      "",
      "Запуск:",
      "",
      "```bash",
      "python -m robot --outputdir results browser.robot",
      "```",
      "",
      "Думайте про три lifecycle levels: Browser process, Context, Page. Context ізолює cookies/storage і часто є правильним unit для test isolation. Page — окремий tab.",
      "",
      "Віддавайте перевагу locators на основі stable user-facing semantics або dedicated test IDs замість brittle DOM structure. Browser Library підтримує CSS та інші selector engines; locator має описувати identity element, а не його випадкову position.",
      "",
      "SeleniumLibrary також існує і є mature. Вибір залежить від existing project, browser requirements і team ecosystem. Для нового Robot web suite Browser Library часто є прямішим шляхом до Playwright capabilities.",
    ].join("\n"),
    keyPoints: ["Browser, Context and Page are distinct lifecycle objects", "Run `rfbrowser init` after installing the library", "Prefer stable semantic/test-id locators"],
    keyPointsUk: ["Browser, Context і Page — різні lifecycle objects", "Після install library виконайте `rfbrowser init`", "Використовуйте stable semantic/test-id locators"],
    pitfalls: ["Treating Browser Library like Selenium and carrying over manual-wait and locator habits unchanged"],
    pitfallsUk: ["Сприймати Browser Library як Selenium і переносити manual-wait та locator habits без змін"],
    tags: ["robot-framework", "browser", "playwright", "web-ui"],
    sourceIds: ["robot-framework-browser", "robot-framework-guides"],
  },
  {
    id: "ta-lesson-robot-framework-browser-sync",
    moduleId: "robot-framework",
    level: "Intermediate",
    order: 55,
    title: "Browser assertions, waiting and page-level keywords",
    titleUk: "Browser assertions, waiting і page-level keywords",
    summary: "Build stable UI tests around retried assertions rather than sleeps.",
    summaryUk: "Будуйте stable UI tests навколо retried assertions, а не sleeps.",
    concept: [
      "Browser Library's waiting model is one of its most important features. Many getters become retrying assertions when you pass an assertion operator. Without an operator they read once.",
      "",
      "```robotframework",
      "Get Text    css=.status    ==    Ready",
      "```",
      "",
      "The line above retries according to the assertion timeout. This line does not:",
      "",
      "```robotframework",
      "${status}=    Get Text    css=.status",
      "```",
      "",
      "For conditions that are not naturally covered by a getter assertion, use `Wait For Condition` or `Wait For Function`. Avoid fixed `Sleep` except when the delay itself is what you are testing.",
      "",
      "Put low-level selectors and mechanics into page/component keywords:",
      "",
      "```robotframework",
      "*** Keywords ***",
      "Login As",
      "    [Arguments]    ${username}    ${password}",
      "    Fill Text    id=username    ${username}",
      "    Fill Secret    id=password    ${password}",
      "    Click    role=button[name=\"Sign in\"]",
      "    Get Url    *=    /dashboard",
      "```",
      "",
      "Then tests can stay at the domain level. Keep assertions close to the behavior they verify. A page keyword may assert that a transition completed when that postcondition is intrinsic to the action; broader business assertions should remain visible in the test.",
      "",
      "When a failure occurs, inspect Browser traces/screenshots together with Robot `log.html`. Evidence should explain both the Robot keyword flow and the browser state.",
    ].join("\n"),
    conceptUk: [
      "Waiting model Browser Library — одна з її найважливіших особливостей. Багато getters стають retrying assertions, якщо передати assertion operator. Без operator вони читають value один раз.",
      "",
      "```robotframework",
      "Get Text    css=.status    ==    Ready",
      "```",
      "",
      "Цей рядок retry'иться відповідно до assertion timeout. А цей — ні:",
      "",
      "```robotframework",
      "${status}=    Get Text    css=.status",
      "```",
      "",
      "Для conditions, які не покриває getter assertion, використовуйте `Wait For Condition` або `Wait For Function`. Fixed `Sleep` краще не використовувати, якщо delay сам по собі не є предметом test.",
      "",
      "Low-level selectors і mechanics винесіть у page/component keywords:",
      "",
      "```robotframework",
      "*** Keywords ***",
      "Login As",
      "    [Arguments]    ${username}    ${password}",
      "    Fill Text    id=username    ${username}",
      "    Fill Secret    id=password    ${password}",
      "    Click    role=button[name=\"Sign in\"]",
      "    Get Url    *=    /dashboard",
      "```",
      "",
      "Тоді tests залишаються на domain level. Assertions тримайте близько до behavior, який вони verify'ять. Page keyword може assert'ити завершення transition, якщо це intrinsic postcondition action; ширші business assertions краще залишити видимими в test.",
      "",
      "При failure аналізуйте Browser traces/screenshots разом із Robot `log.html`. Evidence має пояснювати і Robot keyword flow, і browser state.",
    ].join("\n"),
    keyPoints: ["Getter plus assertion operator is also a synchronization primitive", "Encapsulate selectors in page/component keywords", "Prefer state-based waits over time-based sleeps"],
    keyPointsUk: ["Getter + assertion operator одночасно є synchronization primitive", "Ховайте selectors у page/component keywords", "Віддавайте перевагу state-based waits замість time-based sleeps"],
    pitfalls: ["Reading once and immediately asserting later when a retrying getter assertion would be stable"],
    pitfallsUk: ["Читати value один раз і assert'ити пізніше, хоча retrying getter assertion був би stable"],
    tags: ["robot-framework", "browser", "waiting", "locators"],
    sourceIds: ["robot-framework-browser"],
  },
  {
    id: "ta-lesson-robot-framework-api",
    moduleId: "robot-framework",
    level: "Intermediate",
    order: 56,
    title: "RequestsLibrary: API automation",
    titleUk: "RequestsLibrary: API automation",
    summary: "Test HTTP APIs with explicit status, payload and contract-level assertions.",
    summaryUk: "Тестуйте HTTP APIs з explicit status, payload і contract-level assertions.",
    concept: [
      "RequestsLibrary wraps Python Requests and provides both sessionless and session-based HTTP keywords.",
      "",
      "```bash",
      "python -m pip install robotframework-requests",
      "```",
      "",
      "A runnable sessionless example:",
      "",
      "```robotframework",
      "*** Settings ***",
      "Library    RequestsLibrary",
      "",
      "*** Test Cases ***",
      "Public JSON Post Can Be Read",
      "    ${response}=    GET    https://jsonplaceholder.typicode.com/posts/1    expected_status=200",
      "    Should Be Equal As Integers    ${response.status_code}    200",
      "    Should Be Equal As Integers    ${response.json()}[id]    1",
      "    Should Not Be Empty    ${response.json()}[title]",
      "```",
      "",
      "For a real product API, create a session when several requests share base URL, headers, authentication, proxies or TLS configuration. Keep HTTP mechanics in reusable keywords but keep business assertions visible.",
      "",
      "Validate more than status codes. Important API checks include response schema/shape, required fields, types, domain rules, headers, idempotency, error bodies and persistence side effects. Avoid asserting every field just because it is present; assert the contract and behavior the test owns.",
      "",
      "Secrets such as bearer tokens should come from environment/CI secret storage and can be represented as Robot secret variables before being passed to a library that safely handles them.",
    ].join("\n"),
    conceptUk: [
      "RequestsLibrary обгортає Python Requests і дає sessionless та session-based HTTP keywords.",
      "",
      "```bash",
      "python -m pip install robotframework-requests",
      "```",
      "",
      "Runnable sessionless example:",
      "",
      "```robotframework",
      "*** Settings ***",
      "Library    RequestsLibrary",
      "",
      "*** Test Cases ***",
      "Public JSON Post Can Be Read",
      "    ${response}=    GET    https://jsonplaceholder.typicode.com/posts/1    expected_status=200",
      "    Should Be Equal As Integers    ${response.status_code}    200",
      "    Should Be Equal As Integers    ${response.json()}[id]    1",
      "    Should Not Be Empty    ${response.json()}[title]",
      "```",
      "",
      "Для real product API створюйте session, якщо кілька requests мають спільні base URL, headers, authentication, proxies або TLS configuration. HTTP mechanics винесіть у reusable keywords, а business assertions залишайте видимими.",
      "",
      "Перевіряйте більше, ніж status codes. Важливі API checks: response schema/shape, required fields, types, domain rules, headers, idempotency, error bodies і persistence side effects. Не assert'іть кожне поле лише тому, що воно присутнє; assert'іть contract і behavior, за який відповідає test.",
      "",
      "Secrets на кшталт bearer tokens мають приходити з environment/CI secret storage і можуть бути Robot secret variables перед передачею в library, яка коректно з ними працює.",
    ].join("\n"),
    keyPoints: ["Sessionless requests are enough for isolated calls; sessions centralize shared HTTP configuration", "Assert contract and domain behavior, not only HTTP status", "Keep credentials out of `.robot` files"],
    keyPointsUk: ["Sessionless requests достатні для isolated calls; sessions централізують shared HTTP config", "Assert'іть contract і domain behavior, а не лише HTTP status", "Не зберігайте credentials у `.robot` files"],
    pitfalls: ["Creating one global session whose mutable headers/state leak between independent tests"],
    pitfallsUk: ["Створювати один global session, де mutable headers/state leak'яться між independent tests"],
    tags: ["robot-framework", "api", "requests", "http"],
    sourceIds: ["robot-framework-requests", "robot-framework-user-guide"],
  },
  {
    id: "ta-lesson-robot-framework-python-libraries",
    moduleId: "robot-framework",
    level: "Intermediate",
    order: 57,
    title: "Custom Python libraries, typing and Libdoc",
    titleUk: "Custom Python libraries, typing і Libdoc",
    summary: "Move complex technical logic into typed Python and expose a small Robot keyword API.",
    summaryUk: "Переносьте complex technical logic у typed Python і expose'те маленький Robot keyword API.",
    concept: [
      "Use Python when logic becomes awkward in Robot syntax: parsing, SDK integrations, cryptography, binary protocols, calculations or reusable technical abstractions.",
      "",
      "`OrderLibrary.py`:",
      "",
      "```python",
      "from robot.api.deco import keyword, library",
      "",
      "@library(scope=\"SUITE\", auto_keywords=False)",
      "class OrderLibrary:",
      "    @keyword(\"Calculate Expected Total\")",
      "    def calculate_expected_total(self, first: float, second: float) -> float:",
      "        return round(first + second, 2)",
      "```",
      "",
      "`order_total.robot`:",
      "",
      "```robotframework",
      "*** Settings ***",
      "Library    OrderLibrary.py",
      "",
      "*** Test Cases ***",
      "Order Total Uses Python Keyword",
      "    ${total}=    Calculate Expected Total    10.25    4.75",
      "    Should Be Equal As Numbers    ${total}    15.0",
      "```",
      "",
      "Robot uses supported Python type hints for argument conversion. The library scope controls instance lifecycle; use `TEST`, `SUITE` or `GLOBAL` deliberately depending on whether the object carries state.",
      "",
      "Generate library documentation with Libdoc:",
      "",
      "```bash",
      "python -m libdoc OrderLibrary.py OrderLibrary.html",
      "```",
      "",
      "Robot Framework 7.5 significantly enhances Libdoc, including Markdown documentation support and richer argument/return/exception documentation. Treat your library as a real API: type it, document it, test it directly in Python where appropriate, and keep the Robot-facing surface small.",
    ].join("\n"),
    conceptUk: [
      "Python доречний, коли logic стає незручною в Robot syntax: parsing, SDK integrations, cryptography, binary protocols, calculations або reusable technical abstractions.",
      "",
      "`OrderLibrary.py`:",
      "",
      "```python",
      "from robot.api.deco import keyword, library",
      "",
      "@library(scope=\"SUITE\", auto_keywords=False)",
      "class OrderLibrary:",
      "    @keyword(\"Calculate Expected Total\")",
      "    def calculate_expected_total(self, first: float, second: float) -> float:",
      "        return round(first + second, 2)",
      "```",
      "",
      "`order_total.robot`:",
      "",
      "```robotframework",
      "*** Settings ***",
      "Library    OrderLibrary.py",
      "",
      "*** Test Cases ***",
      "Order Total Uses Python Keyword",
      "    ${total}=    Calculate Expected Total    10.25    4.75",
      "    Should Be Equal As Numbers    ${total}    15.0",
      "```",
      "",
      "Robot використовує supported Python type hints для argument conversion. Library scope керує instance lifecycle; `TEST`, `SUITE` або `GLOBAL` вибирайте залежно від того, чи object тримає state.",
      "",
      "Library documentation генерується через Libdoc:",
      "",
      "```bash",
      "python -m libdoc OrderLibrary.py OrderLibrary.html",
      "```",
      "",
      "Robot Framework 7.5 суттєво покращує Libdoc, включно з Markdown documentation і richer argument/return/exception docs. Ставтесь до library як до справжнього API: типізуйте, документуйте, тестуйте напряму на Python де доречно і тримайте Robot-facing surface малим.",
    ].join("\n"),
    keyPoints: ["Python libraries are for technical implementation, not for hiding test intent", "Library scope is state lifetime", "Use type hints and Libdoc to make keyword contracts explicit"],
    keyPointsUk: ["Python libraries — для technical implementation, а не для приховування test intent", "Library scope — це lifetime state", "Type hints і Libdoc роблять keyword contracts explicit"],
    pitfalls: ["Using `GLOBAL` library scope for stateful clients without designing thread/process isolation"],
    pitfallsUk: ["Використовувати `GLOBAL` library scope для stateful clients без isolation design"],
    tags: ["robot-framework", "python", "custom-library", "libdoc"],
    sourceIds: ["robot-framework-python-library", "robot-framework-libdoc", "robot-framework-releases"],
  },
  {
    id: "ta-lesson-robot-framework-extensions",
    moduleId: "robot-framework",
    level: "Intermediate",
    order: 58,
    title: "Listeners, pre-run modifiers and tool integrations",
    titleUk: "Listeners, pre-run modifiers і tool integrations",
    summary: "Use Robot's APIs for cross-cutting behavior instead of polluting every test.",
    summaryUk: "Для cross-cutting behavior використовуйте Robot APIs, а не дублюйте logic у кожному тесті.",
    concept: [
      "When behavior is truly cross-cutting, Robot Framework provides extension APIs beyond ordinary libraries.",
      "",
      "A listener receives execution events such as suite/test/keyword start and end. Typical uses include telemetry, custom evidence collection, external dashboards and integration with reporting systems. Keep listeners observational whenever possible; hidden mutation from listeners makes tests hard to reason about.",
      "",
      "A pre-run modifier can inspect and modify the parsed execution model before tests run. This can support specialized selection or transformation use cases, but it is an advanced tool. Prefer normal tags and CLI selection when they are sufficient.",
      "",
      "Robot Framework 7.5 also allows custom console loggers using the listener-style API. This can tailor CI console output without changing test data.",
      "",
      "The architecture rule is simple: domain actions belong in keywords/libraries; lifecycle belongs in setup/teardown; cross-cutting observation belongs in listeners; test selection normally belongs in tags/CLI. Use each extension point for its intended responsibility.",
    ].join("\n"),
    conceptUk: [
      "Коли behavior справді cross-cutting, Robot Framework має extension APIs поза ordinary libraries.",
      "",
      "Listener отримує execution events: start/end suite, test, keyword тощо. Типові use cases: telemetry, custom evidence collection, external dashboards та reporting integrations. Listener краще робити observational; hidden mutation через listener сильно ускладнює reasoning про tests.",
      "",
      "Pre-run modifier може inspect'ити й modify'ити parsed execution model до запуску tests. Це корисно для specialized selection або transformation, але є advanced tool. Якщо достатньо normal tags і CLI selection — використовуйте їх.",
      "",
      "Robot Framework 7.5 також дозволяє custom console loggers через listener-style API. Це дає змогу адаптувати CI console output без зміни test data.",
      "",
      "Architecture rule просте: domain actions — у keywords/libraries; lifecycle — у setup/teardown; cross-cutting observation — у listeners; test selection зазвичай — у tags/CLI. Кожен extension point має свою responsibility.",
    ].join("\n"),
    keyPoints: ["Use listeners for observation and integrations", "Prefer tags/CLI over pre-run mutation for normal selection", "Avoid hidden behavior that changes test semantics"],
    keyPointsUk: ["Listeners використовуйте для observation та integrations", "Для normal selection краще tags/CLI, ніж pre-run mutation", "Уникайте hidden behavior, який змінює test semantics"],
    pitfalls: ["Putting business actions into a listener so the test file no longer shows what actually happens"],
    pitfallsUk: ["Переносити business actions у listener так, що test file більше не показує real behavior"],
    tags: ["robot-framework", "listeners", "extensions", "tooling"],
    sourceIds: ["robot-framework-user-guide", "robot-framework-releases"],
  },
  {
    id: "ta-lesson-robot-framework-execution",
    moduleId: "robot-framework",
    level: "Intermediate",
    order: 59,
    title: "CLI execution, output.xml, Rebot and debugging",
    titleUk: "CLI execution, output.xml, Rebot і debugging",
    summary: "Treat execution configuration and result post-processing as first-class parts of the framework.",
    summaryUk: "Сприймайте execution configuration і result post-processing як повноцінні частини framework.",
    concept: [
      "Robot's CLI can select suites/tests/tags, set variables, control output locations and tune logging. Prefer scripts or CI commands that are explicit and reproducible.",
      "",
      "```bash",
      "python -m robot \\",
      "  --outputdir results \\",
      "  --variable ENV:staging \\",
      "  --include smoke \\",
      "  tests",
      "```",
      "",
      "Useful outputs include `output.xml`, `log.html`, `report.html` and optional xUnit-compatible output. `output.xml` can be post-processed with Rebot:",
      "",
      "```bash",
      "python -m rebot --outputdir merged results/output.xml",
      "```",
      "",
      "Rebot can combine multiple output files, adjust report generation and filter/transform result presentation without re-running tests.",
      "",
      "For debugging, start with the earliest meaningful failure in `log.html`. Inspect variable values, keyword arguments, timestamps and setup/teardown results. Increase log level only when needed; very verbose logs can expose sensitive data and make failures harder to scan.",
      "",
      "Robot Framework 7.5 improves console logging configuration and adds custom console loggers. Keep CI console output compact enough to spot the first failure while preserving full result artifacts for detailed investigation.",
    ].join("\n"),
    conceptUk: [
      "Robot CLI може select'ити suites/tests/tags, задавати variables, керувати output paths і logging. Scripts та CI commands мають бути explicit і reproducible.",
      "",
      "```bash",
      "python -m robot \\",
      "  --outputdir results \\",
      "  --variable ENV:staging \\",
      "  --include smoke \\",
      "  tests",
      "```",
      "",
      "Основні outputs: `output.xml`, `log.html`, `report.html` та optional xUnit-compatible output. `output.xml` можна post-process'ити через Rebot:",
      "",
      "```bash",
      "python -m rebot --outputdir merged results/output.xml",
      "```",
      "",
      "Rebot уміє combine'ити кілька output files, налаштовувати report generation і filter/transform result presentation без повторного запуску tests.",
      "",
      "Для debugging починайте з першого meaningful failure у `log.html`. Дивіться variable values, keyword arguments, timestamps і setup/teardown results. Підвищуйте log level лише за потреби; надто verbose logs можуть expose'ити sensitive data і ускладнювати scan failures.",
      "",
      "Robot Framework 7.5 покращує console logging configuration і додає custom console loggers. CI console output має бути достатньо компактним, щоб бачити first failure, а full result artifacts — зберігатися для детального investigation.",
    ].join("\n"),
    keyPoints: ["Keep `output.xml` because it enables post-processing", "Make CLI options reproducible in scripts or CI", "Debug from the first meaningful failure, not the final cascade"],
    keyPointsUk: ["Зберігайте `output.xml`, бо він дозволяє post-processing", "CLI options мають бути reproducible у scripts/CI", "Debug починайте з першого meaningful failure, а не final cascade"],
    pitfalls: ["Discarding output artifacts on CI failure and leaving only console text"],
    pitfallsUk: ["Видаляти output artifacts при CI failure і залишати лише console text"],
    tags: ["robot-framework", "cli", "rebot", "reporting", "debugging"],
    sourceIds: ["robot-framework-user-guide", "robot-framework-releases"],
  },
  {
    id: "ta-lesson-robot-framework-parallel",
    moduleId: "robot-framework",
    level: "Intermediate",
    order: 60,
    title: "Parallel execution with Pabot",
    titleUk: "Parallel execution з Pabot",
    summary: "Parallelize only after tests are isolated and resources have clear ownership.",
    summaryUk: "Паралельте лише після того, як tests ізольовані, а resource ownership чіткий.",
    concept: [
      "Pabot is the common parallel runner for Robot Framework.",
      "",
      "```bash",
      "python -m pip install robotframework-pabot",
      "pabot --processes 4 --outputdir results tests",
      "```",
      "",
      "By default Pabot splits work at suite level. `--testlevelsplit` can split individual tests, but that changes lifecycle behavior: suite setup/teardown may execute for each parallel instance. Use it only when suite assumptions remain valid.",
      "",
      "Parallel failures usually reveal hidden shared state: one test edits data another test expects, processes compete for the same device, or all workers reuse the same account. Fix isolation instead of adding random retries.",
      "",
      "For scarce shared resources, PabotLib can coordinate locks and resource distribution. Sharding can distribute work across machines.",
      "",
      "A good progression is: deterministic sequential suite → isolated suites → parallel suite-level execution → test-level split only if needed. Measure the actual bottleneck; a browser or external system may saturate before CPU does.",
    ].join("\n"),
    conceptUk: [
      "Pabot — common parallel runner для Robot Framework.",
      "",
      "```bash",
      "python -m pip install robotframework-pabot",
      "pabot --processes 4 --outputdir results tests",
      "```",
      "",
      "За default Pabot split'ить work на suite level. `--testlevelsplit` може split'ити окремі tests, але це змінює lifecycle behavior: suite setup/teardown може виконуватись для кожного parallel instance. Використовуйте це лише коли suite assumptions залишаються valid.",
      "",
      "Parallel failures часто показують hidden shared state: один test змінює data, яку очікує інший, processes конкурують за один device або всі workers використовують один account. Fix isolation, а не додавайте random retries.",
      "",
      "Для scarce shared resources PabotLib може координувати locks і resource distribution. Sharding дозволяє рознести work між machines.",
      "",
      "Правильна progression: deterministic sequential suite → isolated suites → parallel suite-level execution → test-level split лише за потреби. Міряйте real bottleneck; browser або external system може saturate'итись раніше за CPU.",
    ].join("\n"),
    keyPoints: ["Parallelism amplifies state leaks; isolation comes first", "Suite-level splitting is the safer default", "Use locks/resource pools only for genuinely scarce shared resources"],
    keyPointsUk: ["Parallelism підсилює state leaks; спочатку isolation", "Suite-level splitting — безпечніший default", "Locks/resource pools використовуйте лише для реально scarce shared resources"],
    pitfalls: ["Turning on test-level parallelism before understanding suite setup/teardown and shared data"],
    pitfallsUk: ["Вмикати test-level parallelism до розуміння suite setup/teardown і shared data"],
    tags: ["robot-framework", "pabot", "parallel", "isolation"],
    sourceIds: ["robot-framework-pabot", "robot-framework-user-guide"],
  },
  {
    id: "ta-lesson-robot-framework-ci",
    moduleId: "robot-framework",
    level: "Intermediate",
    order: 61,
    title: "CI, reports and a production-ready execution workflow",
    titleUk: "CI, reports і production-ready execution workflow",
    summary: "Run Robot deterministically in CI and always preserve evidence.",
    summaryUk: "Запускайте Robot deterministically у CI та завжди зберігайте evidence.",
    concept: [
      "A CI job should install pinned dependencies, initialize required external libraries, run tests, publish machine-readable results when useful, and preserve Robot artifacts even on failure.",
      "",
      "Minimal core-only GitHub Actions example:",
      "",
      "```yaml",
      "name: Robot Framework",
      "on: [push, pull_request]",
      "",
      "jobs:",
      "  robot:",
      "    runs-on: ubuntu-latest",
      "    steps:",
      "      - uses: actions/checkout@v4",
      "      - uses: actions/setup-python@v5",
      "        with:",
      "          python-version: '3.13'",
      "      - run: python -m pip install robotframework==7.5",
      "      - run: python -m robot --outputdir results tests",
      "      - uses: actions/upload-artifact@v4",
      "        if: always()",
      "        with:",
      "          name: robot-results",
      "          path: results/",
      "```",
      "",
      "For Browser Library, install the package and run `rfbrowser init` in CI. For API or system tests, inject credentials through the CI secret mechanism rather than repository files.",
      "",
      "Tag-based jobs can provide quick smoke feedback while a broader regression job runs separately. Avoid duplicating execution rules in many YAML files; centralize commands in a script or task runner if the workflow becomes complex.",
      "",
      "The artifact policy matters: a failed test run is exactly when screenshots, traces, `output.xml` and `log.html` are most valuable.",
    ].join("\n"),
    conceptUk: [
      "CI job має install'ити pinned dependencies, initialize'ити потрібні external libraries, запускати tests, publish'ити machine-readable results де доречно і зберігати Robot artifacts навіть при failure.",
      "",
      "Мінімальний core-only GitHub Actions example:",
      "",
      "```yaml",
      "name: Robot Framework",
      "on: [push, pull_request]",
      "",
      "jobs:",
      "  robot:",
      "    runs-on: ubuntu-latest",
      "    steps:",
      "      - uses: actions/checkout@v4",
      "      - uses: actions/setup-python@v5",
      "        with:",
      "          python-version: '3.13'",
      "      - run: python -m pip install robotframework==7.5",
      "      - run: python -m robot --outputdir results tests",
      "      - uses: actions/upload-artifact@v4",
      "        if: always()",
      "        with:",
      "          name: robot-results",
      "          path: results/",
      "```",
      "",
      "Для Browser Library install'іть package і виконайте `rfbrowser init` у CI. Для API/system tests credentials мають надходити через CI secret mechanism, а не repository files.",
      "",
      "Tag-based jobs можуть давати швидкий smoke feedback, поки broader regression job виконується окремо. Не дублюйте execution rules у багатьох YAML files; якщо workflow стає складним, centralize commands у script або task runner.",
      "",
      "Artifact policy критична: failed test run — саме той момент, коли screenshots, traces, `output.xml` і `log.html` найцінніші.",
    ].join("\n"),
    keyPoints: ["Pin dependencies for reproducible CI", "Always preserve artifacts on failure", "Inject credentials through CI secret storage"],
    keyPointsUk: ["Pin dependencies для reproducible CI", "Завжди зберігайте artifacts при failure", "Передавайте credentials через CI secret storage"],
    pitfalls: ["Making CI pass by suppressing the Robot process exit code without an explicit quarantine policy"],
    pitfallsUk: ["Робити CI green через suppression Robot exit code без explicit quarantine policy"],
    tags: ["robot-framework", "ci", "github-actions", "reporting"],
    sourceIds: ["robot-framework-ci", "robot-framework-guides"],
  },
  {
    id: "ta-lesson-robot-framework-architecture",
    moduleId: "robot-framework",
    level: "Intermediate",
    order: 62,
    title: "Framework architecture, maintainability and the complete mental model",
    titleUk: "Framework architecture, maintainability і complete mental model",
    summary: "Combine the mechanics into a layered Robot project that remains understandable as it grows.",
    summaryUk: "Об'єднайте mechanics у layered Robot project, який залишається зрозумілим при рості.",
    concept: [
      "A maintainable Robot project separates intent, reusable domain actions, technical adapters and environment data.",
      "",
      "```text",
      "robot-project/",
      "├── tests/",
      "│   ├── api/",
      "│   └── ui/",
      "├── resources/",
      "│   ├── domain/",
      "│   │   ├── users.resource",
      "│   │   └── orders.resource",
      "│   └── pages/",
      "│       └── login.resource",
      "├── libraries/",
      "│   └── OrderLibrary.py",
      "├── variables/",
      "│   ├── staging.py",
      "│   └── production.py",
      "├── requirements.txt",
      "└── .github/workflows/robot.yml",
      "```",
      "",
      "A test should read roughly as business intent:",
      "",
      "```robotframework",
      "*** Test Cases ***",
      "Registered User Can See Order",
      "    [Tags]    smoke    ui",
      "    Given User Exists    Alice",
      "    When User Opens Order    1001",
      "    Then Order Total Should Be    1001    42.50",
      "```",
      "",
      "Do not force BDD words everywhere; the important property is that the test describes behavior while details live below it. Domain resource keywords may call Browser/Requests keywords or Python libraries. Python libraries should encapsulate technical logic, not business stories.",
      "",
      "Use suite/test setup for lifecycle, return values/local variables for data flow, tags for selection, metadata for descriptive pairs, listeners for observation, Rebot for result post-processing, and Pabot for parallelism after isolation.",
      "",
      "The strongest Robot Framework design is not the one with the most keywords. It is the one where a reader can move from a failing test to the relevant domain keyword and then to the technical implementation without guessing where behavior is hidden.",
    ].join("\n"),
    conceptUk: [
      "Maintainable Robot project розділяє intent, reusable domain actions, technical adapters і environment data.",
      "",
      "```text",
      "robot-project/",
      "├── tests/",
      "│   ├── api/",
      "│   └── ui/",
      "├── resources/",
      "│   ├── domain/",
      "│   │   ├── users.resource",
      "│   │   └── orders.resource",
      "│   └── pages/",
      "│       └── login.resource",
      "├── libraries/",
      "│   └── OrderLibrary.py",
      "├── variables/",
      "│   ├── staging.py",
      "│   └── production.py",
      "├── requirements.txt",
      "└── .github/workflows/robot.yml",
      "```",
      "",
      "Test має читатися приблизно як business intent:",
      "",
      "```robotframework",
      "*** Test Cases ***",
      "Registered User Can See Order",
      "    [Tags]    smoke    ui",
      "    Given User Exists    Alice",
      "    When User Opens Order    1001",
      "    Then Order Total Should Be    1001    42.50",
      "```",
      "",
      "Не треба силоміць використовувати BDD words всюди; важливо, щоб test описував behavior, а details жили нижче. Domain resource keywords можуть викликати Browser/Requests keywords або Python libraries. Python libraries мають encapsulate technical logic, а не business stories.",
      "",
      "Suite/test setup використовуйте для lifecycle, return values/local variables — для data flow, tags — для selection, metadata — для descriptive pairs, listeners — для observation, Rebot — для result post-processing, Pabot — для parallelism після isolation.",
      "",
      "Найсильніший Robot Framework design — не той, де найбільше keywords. Це той, де reader може пройти від failing test до relevant domain keyword і далі до technical implementation без guessing, де схована behavior.",
    ].join("\n"),
    keyPoints: ["Keep tests at intent level and technical mechanics below them", "Give every concern one clear home in the architecture", "Optimize for traceability from failure to implementation"],
    keyPointsUk: ["Тримайте tests на intent level, а technical mechanics — нижче", "Кожна concern має мати одне чітке місце в architecture", "Оптимізуйте traceability від failure до implementation"],
    pitfalls: ["Building a keyword layer for every single underlying library call and creating indirection without abstraction"],
    pitfallsUk: ["Будувати keyword layer для кожного library call і створювати indirection без abstraction"],
    tags: ["robot-framework", "architecture", "maintainability", "framework-design"],
    sourceIds: ["robot-framework-user-guide", "robot-framework-guides", "robot-framework-browser", "robot-framework-requests"],
  },
];

export default robotFrameworkModule;
