export type DatabaseGuideDialect = "sql" | "mongodb";

const LEGACY_GUIDE_LINE_PATTERN = /^\s*(?:--|\/\/)\s*\[Guide\]\s*/;
const LEADING_COMMENT_PATTERN = /^\s*(?:--|\/\/)\s*/;

function has(source: string, pattern: RegExp): boolean {
  return pattern.test(source);
}

function unique(notes: string[]): string[] {
  return [...new Set(notes)];
}

function sqlDetails(source: string): string[] {
  if (has(source, /WITH\s+ranked_orders\s+AS/i) && has(source, /ROW_NUMBER\s*\(/i)) {
    return [
      "ranked_orders is a temporary result used only by this query.",
      "ROW_NUMBER restarts for each user_id and ranks that user's orders by total_amount, then id, descending.",
      "The outer WHERE keeps ranks 1–3, so the result contains at most three orders per user.",
    ];
  }

  if (has(source, /WITH\s+RECURSIVE\s+sequence/i)) {
    return [
      "The CTE starts with n = 1 and repeatedly adds 1 while n < 10, producing the numbers 1 through 10.",
      "LEFT JOIN then looks for an order whose id matches each generated number; missing orders remain as NULL values.",
    ];
  }

  if (has(source, /CREATE\s+TABLE/i)) {
    const notes: string[] = [];
    if (has(source, /AUTO_INCREMENT|GENERATED\s+BY\s+DEFAULT\s+AS\s+IDENTITY/i)) notes.push("The id value is generated by the database, so INSERT statements do not need to provide it.");
    if (has(source, /PRIMARY\s+KEY/i)) notes.push("PRIMARY KEY uniquely identifies each row; NOT NULL fields must always have a value.");
    if (has(source, /FOREIGN\s+KEY|REFERENCES\s+users/i)) notes.push("user_id must match an existing users.id value, so invalid references are rejected.");
    if (has(source, /\bUNIQUE\b/i)) notes.push("UNIQUE prevents two rows from using the same value for that column.");
    return unique(notes).slice(0, 3);
  }

  if (has(source, /INSERT\s+INTO\s+qa_notes/i)) {
    return ["The values are inserted into title and severity; id and created_at use the table defaults."];
  }

  if (has(source, /UPDATE\s+qa_notes/i)) {
    return ["WHERE selects the matching note; SET changes only its severity column."];
  }

  if (has(source, /DELETE\s+FROM\s+qa_notes/i)) {
    return ["WHERE limits the deletion to notes with this title; the table itself remains."];
  }

  if (has(source, /DROP\s+TABLE\s+IF\s+EXISTS\s+qa_notes/i)) {
    return ["DROP TABLE removes qa_notes and its data; IF EXISTS avoids an error when the table is already absent."];
  }

  if (has(source, /JOIN\s+users\s+u\s+ON\s+u\.id\s*=\s*o\.user_id/i)) {
    const notes = ["JOIN matches each order's user_id to users.id so user fields can be returned with the order."];
    if (has(source, /GROUP\s+BY\s+u\.region/i)) notes.push("GROUP BY u.region creates one group per region; COUNT and SUM are calculated inside each group.");
    if (has(source, /ORDER\s+BY\s+o\.id\s+DESC/i)) notes.push("ORDER BY o.id DESC shows the highest order ids first; LIMIT keeps only the first 20 rows.");
    return notes;
  }

  if (has(source, /JOIN\s+products\s+p\s+ON\s+p\.id\s*=\s*o\.product_id/i)) {
    return [
      "JOIN matches each order's product_id to products.id so product fields can be returned with the order.",
      "ORDER BY o.id DESC shows the highest order ids first; LIMIT keeps only the first 20 rows.",
    ];
  }

  if (has(source, /GROUP\s+BY\s+channel/i)) {
    const notes = ["GROUP BY channel creates one result row per channel; COUNT counts orders and SUM/AVG calculate values inside each channel."];
    if (has(source, /FILTER\s*\(WHERE/i)) notes.push("PostgreSQL FILTER counts paid and cancelled rows separately without running separate queries.");
    if (has(source, /SUM\s*\(status\s*=\s*'paid'\)/i)) notes.push("In MySQL the boolean comparisons evaluate to 1 or 0, so SUM counts paid and cancelled rows.");
    return notes;
  }

  if (has(source, /WHERE\s+EXISTS\s*\(/i)) {
    return [
      "EXISTS keeps a user as soon as one order for that user is both paid and at least 250.",
      "Because the outer query returns users, multiple qualifying orders still produce only one row per user.",
    ];
  }

  if (has(source, /CREATE\s+OR\s+REPLACE\s+VIEW\s+paid_order_summary/i)) {
    return [
      "The view stores this SELECT definition under paid_order_summary; it does not copy the result rows into a new table.",
      "Each future SELECT from the view recalculates paid order count and revenue from the current orders data.",
    ];
  }

  if (has(source, /SET\s+@min_total/i)) {
    return ["@min_total is a MySQL session variable; the following WHERE reuses its value instead of repeating 250."];
  }

  if (has(source, /WITH\s+params\s+AS/i)) {
    return ["params is a one-row CTE containing min_total; CROSS JOIN makes that value available to the main query's WHERE condition."];
  }

  if (has(source, /JSON_EXTRACT|::jsonb|->>/i)) {
    return [has(source, /JSON_EXTRACT/i)
      ? "JSON_EXTRACT reads the status field from the JSON value; JSON_UNQUOTE returns it as normal text."
      : "::jsonb converts the literal to JSONB and ->> returns the status field as text."];
  }

  if (has(source, /CONCAT\s*\(/i)) {
    return ["CONCAT combines email, a separator, and region into the single user_label value."];
  }

  if (has(source, /\|\|/)) {
    return ["PostgreSQL's || operator joins email, a separator, and region into the single user_label value."];
  }

  if (has(source, /^\s*EXPLAIN\b/i)) {
    return [has(source, /ANALYZE/i)
      ? "EXPLAIN ANALYZE executes the query and shows the real plan and timings; BUFFERS also reports buffer usage."
      : "EXPLAIN shows the plan MySQL intends to use, including whether it can use an index or must scan rows."];
  }

  if (has(source, /CREATE\s+UNIQUE\s+INDEX/i)) {
    return ["The index speeds matching lookups and also rejects duplicate qa_notes.title values."];
  }

  if (has(source, /CREATE\s+INDEX\s+idx_orders_user_id/i)) {
    return ["The index stores orders by user_id so lookups on that column can avoid scanning every order row."];
  }

  const notes: string[] = [];
  if (has(source, /WHERE\s+status\s*=\s*'paid'/i)) notes.push("WHERE status = 'paid' removes every non-paid order before the result is returned.");
  if (has(source, /ORDER\s+BY\s+id\s+DESC/i) && has(source, /LIMIT\s+20/i)) notes.push("ORDER BY id DESC puts the highest order ids first; LIMIT 20 keeps the first 20 rows.");
  else if (has(source, /ORDER\s+BY/i) && has(source, /LIMIT/i)) notes.push("ORDER BY determines which rows come first, then LIMIT caps how many of those rows are returned.");
  return notes.slice(0, 3);
}

function mongoDetails(source: string): string[] {
  if (has(source, /"\$lookup"/)) {
    return [
      "$match keeps paid orders and $limit keeps the working set small before the join-like stage.",
      "$lookup matches order user.userId to users.userId and stores the matches in userRecord.",
      "$unwind turns that one-element array into an object; $project keeps only the fields shown in the final result.",
    ];
  }

  if (has(source, /"\$facet"/)) {
    return [
      "$match removes cancelled orders first.",
      "$facet sends that same remaining set through three independent calculations: orders by channel, high-value count, and average value.",
    ];
  }

  if (has(source, /"\$let"/)) {
    return [
      "$let defines taxRate and subtotal only for this expression; it does not change stored documents.",
      "The in expression returns subtotal, calculated tax, and the total including tax for each projected order.",
    ];
  }

  if (has(source, /"\$set"/) && has(source, /"\$cond"/) && has(source, /\.aggregate\s*\(/)) {
    return [
      "$set computes itemCount and valueBand for documents flowing through the pipeline; stored orders are not modified.",
      "$cond labels totals of 250 or more as high and everything else as standard; $project returns only the displayed fields.",
    ];
  }

  if (has(source, /"\$unwind"\s*:\s*"\$items"/)) {
    return [
      "$unwind creates one pipeline document per item in each order.",
      "$group then totals item quantities by category, and $sort puts the largest quantity first.",
    ];
  }

  if (has(source, /"\$group"/) && has(source, /"\$channel"/)) {
    return [
      "$group creates one result per channel; $sum counts orders and adds totalAmount values inside each channel.",
      "$sort by revenue -1 puts the highest-revenue channel first.",
    ];
  }

  if (has(source, /\.findOne\s*\(/)) {
    return ["findOne filters by userId and returns the first matching user document instead of a cursor of many documents."];
  }

  if (has(source, /\$elemMatch/)) {
    return ["$elemMatch requires the same item to have category audio and quantity at least 2; two different items cannot satisfy the conditions separately."];
  }

  if (has(source, /\.find\s*\([\s\S]*?,[\s\S]*?\)/) && has(source, /"_id"\s*:\s*0/)) {
    return ["The first object filters shipped orders; the second object keeps orderId, status, and totalAmount while hiding _id."];
  }

  if (has(source, /"user\.region"/) && has(source, /"\$gt"\s*:\s*100/)) {
    return ["Dot notation reads the embedded user.region field; both region = EU and totalAmount > 100 must be true."];
  }

  if (has(source, /"user\.tier"/) && has(source, /"shipping\.expedited"/)) {
    return ["Dot notation filters embedded user and shipping fields directly; no separate join is needed because both values are inside the order document."];
  }

  if (has(source, /\.insertOne\s*\(/)) {
    return ["insertOne creates one qa_notes document; MongoDB also creates the collection automatically if it does not exist."];
  }

  if (has(source, /\.updateOne\s*\(/) && has(source, /"\$inc"/)) {
    return ["updateOne finds productId 10; $inc adds 5 to stock atomically without replacing the rest of the document."];
  }

  if (has(source, /\.updateOne\s*\(/)) {
    return ["updateOne finds orderId 42; $set changes only status and shipping.expedited, leaving every other field untouched."];
  }

  if (has(source, /\.deleteOne\s*\(/)) {
    return ["deleteOne removes at most one qa_notes document whose title matches Checkout regression."];
  }

  if (has(source, /\.createIndex\s*\(/)) {
    return ["This compound index orders user.region ascending and createdAt descending; queries using the leading region field can benefit from it."];
  }

  if (has(source, /\.getIndexes\s*\(/)) {
    return ["getIndexes returns the index definitions currently attached to orders."];
  }

  if (has(source, /\.explain\s*\("executionStats"\)/)) {
    return ["executionStats shows the chosen plan plus actual execution counters, so you can see whether MongoDB scanned documents or used an index."];
  }

  const notes: string[] = [];
  if (has(source, /\.find\s*\(/) && has(source, /"status"\s*:\s*"paid"/)) notes.push("find keeps only documents whose status is paid.");
  if (has(source, /\.sort\s*\([\s\S]*"createdAt"\s*:\s*-1/) && has(source, /\.limit\s*\(20\)/)) notes.push("sort({ createdAt: -1 }) puts newest documents first; limit(20) returns only the first 20.");
  return notes.slice(0, 3);
}

/**
 * Remove the generated leading explanation comments before execution.
 * Legacy [Guide] comments from previously saved tabs are also removed.
 */
export function stripDatabaseGuideComments(source: string): string {
  const lines = source.split(/\r?\n/);
  let index = 0;
  let sawComment = false;

  while (index < lines.length) {
    const line = lines[index];
    if (LEGACY_GUIDE_LINE_PATTERN.test(line) || LEADING_COMMENT_PATTERN.test(line)) {
      sawComment = true;
      index += 1;
      continue;
    }
    if (sawComment && !line.trim()) {
      index += 1;
      continue;
    }
    break;
  }

  return lines.slice(index).join("\n").trim();
}

export function buildDatabaseGuide(source: string, title: string, description: string, dialect: DatabaseGuideDialect): string {
  const clean = stripDatabaseGuideComments(source).trim();
  if (!clean) return clean;

  const prefix = dialect === "mongodb" ? "//" : "--";
  const summary = description.trim() || title.trim();
  const details = dialect === "mongodb" ? mongoDetails(clean) : sqlDetails(clean);
  const comments = unique([summary, ...details].filter(Boolean)).slice(0, 4);

  return `${comments.map((note) => `${prefix} ${note}`).join("\n")}\n\n${clean}`;
}
