"use client";

import { useEffect } from "react";
import { highlightInterviewCode } from "../../interview-code-highlighting";
import { buildDatabaseGuide, stripDatabaseGuideComments, type DatabaseGuideDialect } from "./database-code-guide";

const annotatedByButton = new WeakMap<HTMLButtonElement, string>();
const clickBound = new WeakSet<HTMLButtonElement>();
const editorOverlayByTextarea = new WeakMap<HTMLTextAreaElement, HTMLPreElement>();
const editorValueByTextarea = new WeakMap<HTMLTextAreaElement, string>();
const editorLanguageByTextarea = new WeakMap<HTMLTextAreaElement, string>();
const EXAMPLE_AUTO_RUN_DELAY_MS = 30;
const LEARNING_NOTE_ATTRIBUTE = "data-db-learning-note";
const SUPPLEMENTAL_EXAMPLE_ATTRIBUTE = "data-db-supplemental-example";

type SqlEngine = "mysql" | "postgres";
type SupplementalSqlExample = {
  title: string;
  description: string;
  sql: string;
  reasoning?: string[];
};

const COMMON_WINDOW_EXAMPLES: SupplementalSqlExample[] = [
  {
    title: "Window function · running SUM",
    description: "Calculate cumulative revenue independently inside each order channel.",
    reasoning: [
      "PARTITION BY restarts the running total for every channel.",
      "ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW defines the cumulative frame explicitly.",
    ],
    sql: `SELECT id,
       channel,
       created_at,
       total_amount,
       ROUND(
         SUM(total_amount) OVER (
           PARTITION BY channel
           ORDER BY created_at, id
           ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
         ),
         2
       ) AS running_revenue
FROM orders
ORDER BY channel, created_at, id
LIMIT 40;`,
  },
  {
    title: "Window function · LAG",
    description: "Compare each order with the previous order from the same user without a self-join.",
    reasoning: [
      "LAG reads a value from the preceding row in the window order.",
      "PARTITION BY user_id prevents an order from being compared with another user's order.",
    ],
    sql: `WITH user_orders AS (
  SELECT id,
         user_id,
         created_at,
         total_amount,
         LAG(total_amount) OVER (
           PARTITION BY user_id
           ORDER BY created_at, id
         ) AS previous_total
  FROM orders
)
SELECT id,
       user_id,
       total_amount,
       previous_total,
       total_amount - previous_total AS change_from_previous
FROM user_orders
WHERE previous_total IS NOT NULL
ORDER BY user_id, created_at, id
LIMIT 40;`,
  },
  {
    title: "Window function · RANK",
    description: "Rank order values inside each channel while keeping every original order row.",
    reasoning: [
      "Unlike GROUP BY, a window function does not collapse the source rows.",
      "RANK gives equal values the same position and leaves gaps after ties.",
    ],
    sql: `SELECT id,
       channel,
       total_amount,
       RANK() OVER (
         PARTITION BY channel
         ORDER BY total_amount DESC
       ) AS amount_rank
FROM orders
ORDER BY channel, amount_rank, id
LIMIT 40;`,
  },
];

function supplementalSqlExamples(engine: SqlEngine): SupplementalSqlExample[] {
  const begin = engine === "mysql" ? "START TRANSACTION;" : "BEGIN;";
  const triggerSql = engine === "mysql"
    ? `CREATE TABLE IF NOT EXISTS order_status_audit (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  order_id BIGINT UNSIGNED NOT NULL,
  old_status VARCHAR(20) NOT NULL,
  new_status VARCHAR(20) NOT NULL,
  changed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

DELETE FROM order_status_audit;
DROP TRIGGER IF EXISTS trg_orders_status_audit;

CREATE TRIGGER trg_orders_status_audit
AFTER UPDATE ON orders
FOR EACH ROW
INSERT INTO order_status_audit (order_id, old_status, new_status)
VALUES (OLD.id, OLD.status, NEW.status);

UPDATE orders
SET status = status
WHERE id = 1;

SELECT id, order_id, old_status, new_status, changed_at
FROM order_status_audit
ORDER BY id DESC
LIMIT 10;`
    : `CREATE TABLE IF NOT EXISTS order_status_audit (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT NOT NULL,
  old_status VARCHAR(20) NOT NULL,
  new_status VARCHAR(20) NOT NULL,
  changed_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

DELETE FROM order_status_audit;

CREATE OR REPLACE FUNCTION log_order_status_change()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  INSERT INTO order_status_audit (order_id, old_status, new_status)
  VALUES (OLD.id, OLD.status, NEW.status);
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_orders_status_audit ON orders;
CREATE TRIGGER trg_orders_status_audit
AFTER UPDATE ON orders
FOR EACH ROW
EXECUTE FUNCTION log_order_status_change();

UPDATE orders
SET status = status
WHERE id = 1;

SELECT id, order_id, old_status, new_status, changed_at
FROM order_status_audit
ORDER BY id DESC
LIMIT 10;`;

  return [
    {
      title: "Transaction · ROLLBACK",
      description: "Change one order inside a transaction, roll it back, and verify that the original row is still stored.",
      reasoning: [
        "The UPDATE is visible only inside the transaction until it is committed.",
        "ROLLBACK discards the change, so the final SELECT shows the original status.",
      ],
      sql: `${begin}
UPDATE orders
SET status = 'transaction-demo'
WHERE id = 1;
ROLLBACK;

SELECT id, status
FROM orders
WHERE id = 1;`,
    },
    {
      title: "Transaction · COMMIT",
      description: "Insert a row into a temporary table and make the transaction durable for the lifetime of this database connection.",
      reasoning: [
        "The temporary table keeps the example isolated from the seeded commerce data.",
        "COMMIT makes the INSERT permanent inside the current temporary-table session before the final SELECT.",
      ],
      sql: `CREATE TEMPORARY TABLE IF NOT EXISTS transaction_demo (
  id INTEGER PRIMARY KEY,
  note VARCHAR(80) NOT NULL
);
DELETE FROM transaction_demo;

${begin}
INSERT INTO transaction_demo (id, note)
VALUES (1, 'committed row');
COMMIT;

SELECT id, note
FROM transaction_demo;`,
    },
    ...COMMON_WINDOW_EXAMPLES,
    {
      title: "Trigger · audit order updates",
      description: "Create an AFTER UPDATE trigger and prove that it writes an audit row when an order is updated.",
      reasoning: [
        "The demo updates status to its existing value, so the seeded order data stays logically unchanged while the trigger still fires.",
        "MySQL can use a single-statement trigger directly; PostgreSQL uses a trigger function and then attaches it to orders.",
      ],
      sql: triggerSql,
    },
  ];
}

function dialectForSource(source: string): DatabaseGuideDialect {
  return /^\s*db\./.test(stripDatabaseGuideComments(source)) ? "mongodb" : "sql";
}

function highlightLanguage(dialect: DatabaseGuideDialect): string {
  return dialect === "mongodb" ? "javascript" : "sql";
}

function appendHighlighted(target: HTMLElement, source: string, dialect: DatabaseGuideDialect) {
  target.replaceChildren();
  for (const token of highlightInterviewCode(source, highlightLanguage(dialect))) {
    if (!token.color) {
      target.append(document.createTextNode(token.text));
      continue;
    }
    const span = document.createElement("span");
    span.textContent = token.text;
    span.style.color = token.color;
    target.appendChild(span);
  }
}

function setControlledTextareaValue(textarea: HTMLTextAreaElement, value: string) {
  const setter = Object.getOwnPropertyDescriptor(HTMLTextAreaElement.prototype, "value")?.set;
  if (!setter) return;
  setter.call(textarea, value);
  textarea.dispatchEvent(new Event("input", { bubbles: true }));
}

function activeEditor(): HTMLTextAreaElement | null {
  return document.querySelector<HTMLTextAreaElement>('textarea[aria-label="SQL editor"], textarea[aria-label="MongoDB query editor"]');
}

function activeRunButton(textarea: HTMLTextAreaElement): HTMLButtonElement | null {
  const editorPane = textarea.closest("section");
  if (!editorPane) return null;
  return [...editorPane.querySelectorAll<HTMLButtonElement>("button")]
    .find((button) => button.textContent?.trim() === "Run SQL" || button.textContent?.trim() === "Run query") ?? null;
}

function activeSqlEngine(): SqlEngine | null {
  const tabList = document.querySelector<HTMLElement>('[aria-label="Query tabs"]');
  const selected = tabList?.querySelector<HTMLButtonElement>('button[role="tab"][aria-selected="true"]');
  const label = selected?.querySelector("small")?.textContent?.trim();
  if (label === "MySQL") return "mysql";
  if (label === "PG") return "postgres";
  return null;
}

function removeSupplementalExamples() {
  for (const card of document.querySelectorAll<HTMLElement>(`[${SUPPLEMENTAL_EXAMPLE_ATTRIBUTE}]`)) card.remove();
}

function createSupplementalExampleCard(entry: SupplementalSqlExample, engine: SqlEngine, className: string): HTMLElement {
  const card = document.createElement("article");
  card.className = className;
  card.setAttribute(SUPPLEMENTAL_EXAMPLE_ATTRIBUTE, engine);

  const title = document.createElement("h2");
  title.textContent = entry.title;
  card.appendChild(title);

  const description = document.createElement("p");
  description.textContent = entry.description;
  card.appendChild(description);

  for (const reasoning of entry.reasoning ?? []) {
    const note = document.createElement("p");
    note.setAttribute(LEARNING_NOTE_ATTRIBUTE, "");
    note.textContent = `Think: ${reasoning}`;
    card.appendChild(note);
  }

  const pre = document.createElement("pre");
  const code = document.createElement("code");
  code.textContent = entry.sql;
  pre.appendChild(code);
  card.appendChild(pre);

  const useButton = document.createElement("button");
  useButton.type = "button";
  useButton.textContent = "Use example";
  card.appendChild(useButton);

  return card;
}

function syncSupplementalSqlExamples() {
  const categoryTabs = document.querySelector<HTMLElement>('[aria-label="Database example categories"]');
  const selectedCategory = categoryTabs?.querySelector<HTMLButtonElement>('button[aria-selected="true"]');
  const examplesList = categoryTabs?.nextElementSibling;
  const engine = activeSqlEngine();

  if (!(examplesList instanceof HTMLElement) || selectedCategory?.textContent?.trim() !== "Advanced SQL" || !engine) {
    removeSupplementalExamples();
    return;
  }

  const existing = [...examplesList.querySelectorAll<HTMLElement>(`[${SUPPLEMENTAL_EXAMPLE_ATTRIBUTE}]`)];
  const expected = supplementalSqlExamples(engine);
  if (existing.length === expected.length && existing.every((card) => card.getAttribute(SUPPLEMENTAL_EXAMPLE_ATTRIBUTE) === engine)) return;

  removeSupplementalExamples();
  const exampleClass = examplesList.querySelector<HTMLElement>("article")?.className || "";
  for (const entry of expected) examplesList.appendChild(createSupplementalExampleCard(entry, engine, exampleClass));
}

function exampleSource(card: HTMLElement): string {
  const original = card.querySelector<HTMLElement>("pre:not(.db-example-highlight) code");
  return stripDatabaseGuideComments(original?.textContent || "");
}

function learningNotes(card: HTMLElement): string[] {
  return [...card.querySelectorAll<HTMLElement>(`[${LEARNING_NOTE_ATTRIBUTE}]`)]
    .map((note) => note.textContent?.trim() || "")
    .filter(Boolean);
}

function annotatedExample(card: HTMLElement, raw: string, title: string, description: string, dialect: DatabaseGuideDialect): string {
  const notes = learningNotes(card);
  if (!notes.length) return buildDatabaseGuide(raw, title, description, dialect);
  const prefix = dialect === "mongodb" ? "//" : "--";
  const comments = [description, ...notes].filter(Boolean).map((note) => `${prefix} ${note}`);
  return `${comments.join("\n")}\n\n${stripDatabaseGuideComments(raw).trim()}`;
}

function ensureExampleOverlay(card: HTMLElement, annotated: string, dialect: DatabaseGuideDialect) {
  const originalPre = card.querySelector<HTMLElement>("pre:not(.db-example-highlight)");
  if (!originalPre) return;
  let overlay = card.querySelector<HTMLPreElement>("pre.db-example-highlight");
  if (!overlay) {
    overlay = document.createElement("pre");
    overlay.className = "db-example-highlight";
    overlay.setAttribute("aria-hidden", "true");
    overlay.appendChild(document.createElement("code"));
    originalPre.insertAdjacentElement("beforebegin", overlay);
    originalPre.hidden = true;
  }
  const code = overlay.querySelector<HTMLElement>("code");
  if (code?.textContent !== annotated) appendHighlighted(code!, annotated, dialect);
}

function decorateExample(button: HTMLButtonElement) {
  const card = button.closest<HTMLElement>("article");
  if (!card) return;
  const raw = exampleSource(card);
  if (!raw) return;
  const title = card.querySelector("h2")?.textContent?.trim() || "Database example";
  const description = card.querySelector("p:not([data-db-learning-note])")?.textContent?.trim() || title;
  const dialect = dialectForSource(raw);
  const annotated = annotatedExample(card, raw, title, description, dialect);
  annotatedByButton.set(button, annotated);
  ensureExampleOverlay(card, annotated, dialect);

  if (clickBound.has(button)) return;
  clickBound.add(button);
  button.addEventListener("click", () => {
    const currentAnnotated = annotatedByButton.get(button);
    if (!currentAnnotated) return;
    window.setTimeout(() => {
      const textarea = activeEditor();
      if (!textarea) return;
      setControlledTextareaValue(textarea, currentAnnotated);
      textarea.focus();
      window.setTimeout(() => {
        const runButton = activeRunButton(textarea);
        if (!runButton || runButton.disabled) return;
        runButton.click();
      }, EXAMPLE_AUTO_RUN_DELAY_MS);
    }, 0);
  }, true);
}

function syncExamples() {
  for (const button of document.querySelectorAll<HTMLButtonElement>("button")) {
    if (button.textContent?.trim() === "Use example") decorateExample(button);
  }
}

function closeAllQueryTabs(tabList: HTMLElement) {
  let remaining = tabList.querySelectorAll<HTMLButtonElement>('button[title="Close query tab"]').length;
  if (!remaining) return;

  const closeNext = () => {
    if (remaining <= 0) return;
    const close = tabList.querySelector<HTMLButtonElement>('button[title="Close query tab"]');
    if (!close) return;
    remaining -= 1;
    close.click();
    if (remaining > 0) window.setTimeout(closeNext, 0);
  };

  closeNext();
}

function ensureCloseAllTabsButton() {
  const tabList = document.querySelector<HTMLElement>('[aria-label="Query tabs"]');
  if (!tabList || tabList.querySelector(".db-query-close-all")) return;

  const button = document.createElement("button");
  button.type = "button";
  button.className = "db-query-close-all";
  button.setAttribute("aria-label", "Close all query tabs");
  button.title = "Close all query tabs";
  button.textContent = "×";
  button.addEventListener("click", () => closeAllQueryTabs(tabList));
  tabList.insertBefore(button, tabList.firstChild);
}

function editorDialect(textarea: HTMLTextAreaElement): DatabaseGuideDialect {
  return textarea.getAttribute("aria-label") === "MongoDB query editor" ? "mongodb" : "sql";
}

function syncEditorScroll(textarea: HTMLTextAreaElement, overlay: HTMLPreElement) {
  overlay.scrollTop = textarea.scrollTop;
  overlay.scrollLeft = textarea.scrollLeft;
}

function ensureEditorOverlay(textarea: HTMLTextAreaElement) {
  let overlay = editorOverlayByTextarea.get(textarea);
  if (!overlay || !overlay.isConnected) {
    const parent = textarea.parentElement;
    if (!parent) return;
    overlay = document.createElement("pre");
    overlay.className = "db-query-highlight";
    overlay.setAttribute("aria-hidden", "true");
    const code = document.createElement("code");
    overlay.appendChild(code);
    parent.insertBefore(overlay, textarea);
    textarea.classList.add("db-query-editor-overlay");
    textarea.addEventListener("scroll", () => syncEditorScroll(textarea, overlay!));
    textarea.addEventListener("input", () => syncEditor(textarea));
    editorOverlayByTextarea.set(textarea, overlay);
  }
  syncEditor(textarea);
}

function syncEditor(textarea: HTMLTextAreaElement) {
  const overlay = editorOverlayByTextarea.get(textarea);
  const code = overlay?.querySelector<HTMLElement>("code");
  if (!overlay || !code) return;
  const dialect = editorDialect(textarea);
  const language = highlightLanguage(dialect);
  const value = textarea.value;
  if (editorValueByTextarea.get(textarea) !== value || editorLanguageByTextarea.get(textarea) !== language) {
    appendHighlighted(code, value || " ", dialect);
    editorValueByTextarea.set(textarea, value);
    editorLanguageByTextarea.set(textarea, language);
  }
  syncEditorScroll(textarea, overlay);
}

function syncPlaygroundCode() {
  syncSupplementalSqlExamples();
  syncExamples();
  ensureCloseAllTabsButton();
  const textarea = activeEditor();
  if (textarea) ensureEditorOverlay(textarea);
}

export default function DatabaseCodeEnhancer() {
  useEffect(() => {
    syncPlaygroundCode();
    const timer = window.setInterval(syncPlaygroundCode, 120);
    const root = document.querySelector(".kb-main") ?? document.body;
    const observer = new MutationObserver(syncPlaygroundCode);
    observer.observe(root, { childList: true, subtree: true });

    return () => {
      window.clearInterval(timer);
      observer.disconnect();
      removeSupplementalExamples();
      for (const textarea of document.querySelectorAll<HTMLTextAreaElement>("textarea.db-query-editor-overlay")) {
        textarea.classList.remove("db-query-editor-overlay");
      }
      for (const overlay of document.querySelectorAll(".db-query-highlight, .db-example-highlight, .db-query-close-all")) overlay.remove();
      for (const original of document.querySelectorAll<HTMLElement>("article pre[hidden]")) original.hidden = false;
    };
  }, []);

  return null;
}
