sonar.organization=sergiiiavt
sonar.projectKey=sergiiiavt_gimme-job
sonar.projectName=gimme-job
sonar.sourceEncoding=UTF-8

sonar.sources=.
sonar.tests=tests
sonar.exclusions=tests/**,node_modules/**,dist/**,.next/**,public/**,assets/**,content/**,data/**,docs/**,examples/**,drizzle/**,agent/src/resume-fonts.ts
sonar.test.inclusions=tests/**
