"use client";

import automationCurriculum from "@/content/automation-learning/catalog";
import LearningDocumentPage from "./learning-document-page";

const reference = automationCurriculum.referenceImplementation;
const live = (path: string) => `https://github.com/${reference.repo}/blob/${reference.branch}/${path}`;
const reviewed = (path: string) => `https://github.com/${reference.repo}/blob/${reference.verifiedCommit}/${path}`;
const linkPair = (label: string, path: string) => `- **${label}** — \`${path}\`: [live](${live(path)}) · [reviewed](${reviewed(path)})`;

const referenceFrameworkModule = {
  id: "reference-framework",
  label: "Reference framework walkthrough",
  labelUk: "Розбір reference framework",
  description: "Now inspect a real implementation of the concepts from the learning path, using the qa-automation-python repository as a guided architecture walkthrough.",
  descriptionUk: "Тепер розбери реальну реалізацію концепцій із learning path на прикладі репозиторію qa-automation-python як послідовний walkthrough архітектури.",
  markdown: [
    "# Reference framework walkthrough",
    "",
    "This area is deliberately different from the theory tracks. It does not teach the same concepts again. Instead, it maps the concepts you have already learned to a real repository and shows where each responsibility lives.",
    "",
    `Reference repository: **${reference.repo}**. The lesson links use both the live \`${reference.branch}\` branch and the reviewed snapshot \`${reference.verifiedCommit.slice(0, 7)}\` (${reference.verifiedAt}).`,
    "",
    "## 1. Start with the repository shape",
    "",
    "Read the repository from the outside inward: project metadata and setup first, pytest wiring second, framework layers third, tests last. This makes the dependency direction easier to see than opening random files.",
    "",
    linkPair("Project overview and local setup", "README.md"),
    linkPair("Python package and dependency declaration", "pyproject.toml"),
    linkPair("Generated/local files excluded from Git", ".gitignore"),
    linkPair("Environment example", ".env.example"),
    "",
    "## 2. pytest wiring and lifecycle",
    "",
    "The root `conftest.py` is the composition boundary for shared pytest configuration and fixtures. The layer-specific `conftest.py` files add web, service, or mobile concerns closer to the tests that need them.",
    "",
    linkPair("Shared pytest fixtures and hooks", "conftest.py"),
    linkPair("Web fixtures", "tests/web/conftest.py"),
    linkPair("Service fixtures", "tests/services/conftest.py"),
    linkPair("Mobile fixtures", "tests/mobile/conftest.py"),
    linkPair("pytest learning notes", "docs/01-pytest-foundations.md"),
    "",
    "## 3. Configuration architecture",
    "",
    "Configuration is kept outside individual tests. Runtime settings are loaded through framework code and environment/project configuration instead of being scattered through page objects or test functions.",
    "",
    linkPair("Typed/runtime configuration layer", "framework/config.py"),
    linkPair("Local configuration example", "config/local.yaml"),
    linkPair("Configuration tests", "tests/framework/test_config.py"),
    linkPair("Architecture explanation", "docs/02-architecture.md"),
    "",
    "## 4. Web automation layer",
    "",
    "The web layer separates reusable browser mechanics from concrete page behaviour, while the tests remain focused on scenarios and assertions.",
    "",
    linkPair("Reusable page mechanics", "framework/web/base_page.py"),
    linkPair("Concrete page objects", "framework/web/pages.py"),
    linkPair("Web test fixtures", "tests/web/conftest.py"),
    linkPair("Example business flow", "tests/web/test_shopping_flow.py"),
    linkPair("Web automation notes", "docs/04-web.md"),
    "",
    "## 5. API and services layer",
    "",
    "The service layer demonstrates the same separation: transport mechanics belong in the HTTP client, domain/service operations belong in API objects, and scenario expectations stay in tests.",
    "",
    linkPair("Instrumented HTTP client", "framework/http/client.py"),
    linkPair("Service/domain API object", "framework/api/shop.py"),
    linkPair("API models", "framework/api/models.py"),
    linkPair("Service scenario", "tests/services/test_cart_flow.py"),
    linkPair("Contract/property example", "tests/services/test_contract_and_properties.py"),
    linkPair("Services notes", "docs/03-services.md"),
    "",
    "## 6. Mobile automation layer",
    "",
    "Mobile keeps device/session creation separate from screen abstractions and test scenarios. This is the mobile equivalent of browser management plus Page Objects.",
    "",
    linkPair("Appium driver/session factory", "framework/mobile/driver_factory.py"),
    linkPair("Reusable screen mechanics", "framework/mobile/base_screen.py"),
    linkPair("Concrete screen objects", "framework/mobile/screens.py"),
    linkPair("Native application test", "tests/mobile/test_native_app.py"),
    linkPair("Real-device mobile web test", "tests/mobile/test_mobile_web_real_device.py"),
    linkPair("Mobile automation notes", "docs/05-mobile.md"),
    "",
    "## 7. Test data, assertions and reporting",
    "",
    "Cross-cutting helpers are kept out of test scenarios so that data generation, reusable assertions, and reporting can evolve independently.",
    "",
    linkPair("Test data factories", "framework/data/factories.py"),
    linkPair("Reusable assertions", "framework/utils/assertions.py"),
    linkPair("Reporting helpers", "framework/utils/reporting.py"),
    linkPair("Test data notes", "docs/06-test-data.md"),
    linkPair("Flakiness notes", "docs/08-flakiness.md"),
    "",
    "## 8. CI and execution model",
    "",
    "The framework is complete only when the same suite can run consistently outside a developer laptop. Follow the workflow from dependency installation through execution and artifacts.",
    "",
    linkPair("GitHub Actions pipeline", ".github/workflows/ci.yml"),
    linkPair("CI and reporting notes", "docs/07-ci-reporting.md"),
    linkPair("Automation strategy notes", "docs/09-strategy.md"),
    "",
    "## How to use this track",
    "",
    "For each concept, first understand the generic rule in the earlier tracks, then inspect the linked implementation here. Ask three questions: **what responsibility does this file own, what is it intentionally not responsible for, and which layer depends on it?** That turns the repository into an architecture exercise rather than a collection of code snippets.",
  ].join("\n"),
  markdownUk: [
    "# Розбір reference framework",
    "",
    "Ця частина навмисно відрізняється від теоретичних tracks. Вона не пояснює ті самі концепції вдруге. Замість цього вона мапить уже вивчені концепції на реальний репозиторій і показує, де живе кожна відповідальність.",
    "",
    `Reference repository: **${reference.repo}**. Посилання ведуть і на live \`${reference.branch}\`, і на reviewed snapshot \`${reference.verifiedCommit.slice(0, 7)}\` (${reference.verifiedAt}).`,
    "",
    "## 1. Почни зі структури репозиторію",
    "",
    "Читай репозиторій ззовні всередину: спочатку metadata та setup проєкту, потім pytest wiring, далі framework layers і лише після цього tests. Так dependency direction видно значно краще, ніж при випадковому відкриванні файлів.",
    "",
    linkPair("Огляд проєкту та локальний setup", "README.md"),
    linkPair("Python package і dependency declaration", "pyproject.toml"),
    linkPair("Локальні/generated файли поза Git", ".gitignore"),
    linkPair("Приклад environment configuration", ".env.example"),
    "",
    "## 2. pytest wiring і lifecycle",
    "",
    "Кореневий `conftest.py` є composition boundary для спільної pytest configuration та fixtures. Layer-specific `conftest.py` додають web, service або mobile concerns ближче до tests, яким вони потрібні.",
    "",
    linkPair("Спільні pytest fixtures і hooks", "conftest.py"),
    linkPair("Web fixtures", "tests/web/conftest.py"),
    linkPair("Service fixtures", "tests/services/conftest.py"),
    linkPair("Mobile fixtures", "tests/mobile/conftest.py"),
    linkPair("pytest learning notes", "docs/01-pytest-foundations.md"),
    "",
    "## 3. Архітектура configuration",
    "",
    "Configuration винесена за межі окремих tests. Runtime settings завантажуються через framework code та environment/project configuration, а не розкидані по page objects чи test functions.",
    "",
    linkPair("Runtime configuration layer", "framework/config.py"),
    linkPair("Приклад local configuration", "config/local.yaml"),
    linkPair("Tests configuration layer", "tests/framework/test_config.py"),
    linkPair("Пояснення архітектури", "docs/02-architecture.md"),
    "",
    "## 4. Web automation layer",
    "",
    "Web layer відокремлює reusable browser mechanics від конкретної поведінки pages, а tests залишаються сфокусованими на сценаріях та assertions.",
    "",
    linkPair("Reusable page mechanics", "framework/web/base_page.py"),
    linkPair("Concrete page objects", "framework/web/pages.py"),
    linkPair("Web test fixtures", "tests/web/conftest.py"),
    linkPair("Приклад business flow", "tests/web/test_shopping_flow.py"),
    linkPair("Web automation notes", "docs/04-web.md"),
    "",
    "## 5. API та services layer",
    "",
    "Service layer показує ту саму separation: transport mechanics належать HTTP client, domain/service operations — API objects, а scenario expectations — tests.",
    "",
    linkPair("Instrumented HTTP client", "framework/http/client.py"),
    linkPair("Service/domain API object", "framework/api/shop.py"),
    linkPair("API models", "framework/api/models.py"),
    linkPair("Service scenario", "tests/services/test_cart_flow.py"),
    linkPair("Contract/property example", "tests/services/test_contract_and_properties.py"),
    linkPair("Services notes", "docs/03-services.md"),
    "",
    "## 6. Mobile automation layer",
    "",
    "Mobile відділяє створення device/session від screen abstractions та test scenarios. Це mobile-еквівалент browser management плюс Page Objects.",
    "",
    linkPair("Appium driver/session factory", "framework/mobile/driver_factory.py"),
    linkPair("Reusable screen mechanics", "framework/mobile/base_screen.py"),
    linkPair("Concrete screen objects", "framework/mobile/screens.py"),
    linkPair("Native application test", "tests/mobile/test_native_app.py"),
    linkPair("Real-device mobile web test", "tests/mobile/test_mobile_web_real_device.py"),
    linkPair("Mobile automation notes", "docs/05-mobile.md"),
    "",
    "## 7. Test data, assertions і reporting",
    "",
    "Cross-cutting helpers винесені з test scenarios, щоб data generation, reusable assertions і reporting могли еволюціонувати незалежно.",
    "",
    linkPair("Test data factories", "framework/data/factories.py"),
    linkPair("Reusable assertions", "framework/utils/assertions.py"),
    linkPair("Reporting helpers", "framework/utils/reporting.py"),
    linkPair("Test data notes", "docs/06-test-data.md"),
    linkPair("Flakiness notes", "docs/08-flakiness.md"),
    "",
    "## 8. CI та execution model",
    "",
    "Framework є завершеним лише тоді, коли той самий suite стабільно працює не тільки на laptop розробника. Простеж workflow від dependency installation до execution та artifacts.",
    "",
    linkPair("GitHub Actions pipeline", ".github/workflows/ci.yml"),
    linkPair("CI і reporting notes", "docs/07-ci-reporting.md"),
    linkPair("Automation strategy notes", "docs/09-strategy.md"),
    "",
    "## Як використовувати цей track",
    "",
    "Для кожної концепції спочатку зрозумій generic rule у попередніх tracks, а потім відкрий відповідну implementation тут. Постав три питання: **за яку відповідальність відповідає цей файл, за що він навмисно не відповідає, і який layer від нього залежить?** Так repository стає вправою з architecture, а не просто набором code snippets.",
  ].join("\n"),
};

const curriculum = {
  ...automationCurriculum,
  taxonomy: [...automationCurriculum.taxonomy, referenceFrameworkModule],
};

const trackOptions = [
  { id: "foundations", label: "Foundations", labelUk: "Основи", available: true, moduleIds: ["automation-foundations"] },
  { id: "python-setup", label: "Python Setup", labelUk: "Python Setup", available: true, moduleIds: ["project-setup"] },
  { id: "pytest", label: "pytest", labelUk: "pytest", available: true, moduleIds: ["pytest-core"] },
  { id: "automation", label: "Web / API / Mobile", labelUk: "Web / API / Mobile", available: true, moduleIds: ["api-testing", "web-ui-testing", "mobile-testing", "contract-and-property"] },
  { id: "architecture", label: "Architecture", labelUk: "Архітектура", available: true, moduleIds: ["framework-architecture", "test-data", "flakiness", "ci-and-reporting", "quality-strategy"] },
  { id: "reference-framework", label: "Reference Framework", labelUk: "Reference Framework", available: true, moduleIds: ["reference-framework"] },
];

export default function AutomationLearningPage({ mode }: { mode: "public" | "personal" }) {
  return (
    <LearningDocumentPage
      curriculum={curriculum}
      defaultTrackId="foundations"
      mode={mode}
      personalHref="/workspace/learn/automation"
      publicHref="/learn/automation"
      secondaryTitle="Test automation"
      section="automation"
      trackOptions={trackOptions}
    />
  );
}