const taxonomy = [
  {
    id: "csharp-language-basics",
    label: "Language basics, types & control flow",
    labelUk: "Основи мови, типи та control flow",
    level: "Foundations",
    description: "Core C# syntax, variables, nullability, value/reference semantics, conditions and loops.",
    descriptionUk: "Базовий синтаксис C#, змінні, nullability, value/reference semantics, умови та цикли.",
  },
  {
    id: "csharp-methods-parameters",
    label: "Methods, parameters & overloads",
    labelUk: "Методи, параметри та overloads",
    level: "Foundations",
    description: "Method signatures, return values, optional/named parameters, ref/out/in and overloading.",
    descriptionUk: "Сигнатури методів, return values, optional/named parameters, ref/out/in та перевантаження.",
  },
  {
    id: "csharp-classes-objects",
    label: "Classes, objects & access modifiers",
    labelUk: "Класи, об’єкти та access modifiers",
    level: "Foundations",
    description: "Classes, instances, constructors, fields, properties, static members and visibility.",
    descriptionUk: "Класи, instances, constructors, fields, properties, static members та видимість.",
  },
  {
    id: "csharp-oop",
    label: "Object-oriented programming",
    labelUk: "Об’єктно-орієнтоване програмування",
    level: "Core",
    description: "Encapsulation, inheritance, polymorphism and abstraction with practical C# examples.",
    descriptionUk: "Encapsulation, inheritance, polymorphism та abstraction на практичних прикладах C#.",
  },
  {
    id: "csharp-abstractions",
    label: "Interfaces, abstract classes, structs & records",
    labelUk: "Interfaces, abstract classes, structs та records",
    level: "Core",
    description: "How C# models contracts and data shapes, and when each abstraction fits.",
    descriptionUk: "Як C# моделює контракти й data shapes та коли підходить кожна abstraction.",
  },
  {
    id: "csharp-collections-generics",
    label: "Collections, generics & IEnumerable",
    labelUk: "Collections, generics та IEnumerable",
    level: "Core",
    description: "List, Dictionary, HashSet, generic type parameters and enumerable sequences.",
    descriptionUk: "List, Dictionary, HashSet, generic type parameters та enumerable sequences.",
  },
  {
    id: "csharp-delegates-linq",
    label: "Delegates, events, lambdas & LINQ",
    labelUk: "Delegates, events, lambdas та LINQ",
    level: "Core",
    description: "Executable references, event publication, lambda syntax and querying collections with LINQ.",
    descriptionUk: "Посилання на executable behavior, events, lambda syntax та LINQ-запити до collections.",
  },
  {
    id: "csharp-exceptions-disposal",
    label: "Exceptions & resource management",
    labelUk: "Exceptions та керування ресурсами",
    level: "Core",
    description: "try/catch/finally, custom exceptions, IDisposable and using.",
    descriptionUk: "try/catch/finally, custom exceptions, IDisposable та using.",
  },
  {
    id: "csharp-async",
    label: "async/await, Task & concurrency basics",
    labelUk: "async/await, Task та основи concurrency",
    level: "Core",
    description: "Task-based asynchronous code, awaiting work and the basic difference between async and parallel execution.",
    descriptionUk: "Task-based asynchronous code, await та базова різниця між async і parallel execution.",
  },
  {
    id: "csharp-runtime-memory",
    label: "Runtime, memory, GC & equality",
    labelUk: "Runtime, пам’ять, GC та equality",
    level: "Core",
    description: "Managed memory, garbage collection, boxing/unboxing, identity and value equality.",
    descriptionUk: "Managed memory, garbage collection, boxing/unboxing, identity та value equality.",
  },
];

const sources = [
  {
    id: "csharp-tour",
    title: "A tour of C#",
    url: "https://learn.microsoft.com/en-us/dotnet/csharp/tour-of-csharp/",
    publisher: "Microsoft Learn",
    kind: "Official documentation",
    role: "Language syntax, control flow, methods, classes and general C# semantics",
  },
  {
    id: "csharp-type-system",
    title: "The C# type system",
    url: "https://learn.microsoft.com/en-us/dotnet/csharp/fundamentals/types/",
    publisher: "Microsoft Learn",
    kind: "Official documentation",
    role: "Value/reference types, nullability, conversions and type-system fundamentals",
  },
  {
    id: "csharp-oop-docs",
    title: "Object-oriented programming",
    url: "https://learn.microsoft.com/en-us/dotnet/csharp/fundamentals/object-oriented/",
    publisher: "Microsoft Learn",
    kind: "Official documentation",
    role: "Encapsulation, inheritance, polymorphism and abstraction",
  },
  {
    id: "csharp-interfaces",
    title: "Interfaces",
    url: "https://learn.microsoft.com/en-us/dotnet/csharp/fundamentals/types/interfaces",
    publisher: "Microsoft Learn",
    kind: "Official documentation",
    role: "Interface contracts, implementation and multiple-interface composition",
  },
  {
    id: "dotnet-collections",
    title: "Collections and data structures",
    url: "https://learn.microsoft.com/en-us/dotnet/standard/collections/",
    publisher: "Microsoft Learn",
    kind: "Official documentation",
    role: "Collection families, generic collections and selection trade-offs",
  },
  {
    id: "csharp-generics",
    title: "Generics",
    url: "https://learn.microsoft.com/en-us/dotnet/csharp/fundamentals/types/generics",
    publisher: "Microsoft Learn",
    kind: "Official documentation",
    role: "Generic types, methods and type parameters",
  },
  {
    id: "csharp-delegates",
    title: "Delegates",
    url: "https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/delegates/",
    publisher: "Microsoft Learn",
    kind: "Official documentation",
    role: "Delegate types, method references, callbacks and events",
  },
  {
    id: "csharp-linq",
    title: "Language Integrated Query (LINQ)",
    url: "https://learn.microsoft.com/en-us/dotnet/csharp/linq/",
    publisher: "Microsoft Learn",
    kind: "Official documentation",
    role: "LINQ operators, deferred execution and sequence queries",
  },
  {
    id: "csharp-exceptions",
    title: "Exceptions and exception handling",
    url: "https://learn.microsoft.com/en-us/dotnet/csharp/fundamentals/exceptions/",
    publisher: "Microsoft Learn",
    kind: "Official documentation",
    role: "Exception flow, try/catch/finally and exception design",
  },
  {
    id: "csharp-async-docs",
    title: "Asynchronous programming with async and await",
    url: "https://learn.microsoft.com/en-us/dotnet/csharp/asynchronous-programming/",
    publisher: "Microsoft Learn",
    kind: "Official documentation",
    role: "Task-based asynchronous programming, async and await",
  },
  {
    id: "dotnet-gc",
    title: "Fundamentals of garbage collection",
    url: "https://learn.microsoft.com/en-us/dotnet/standard/garbage-collection/fundamentals",
    publisher: "Microsoft Learn",
    kind: "Official documentation",
    role: "Managed heap, generations, collection and object lifetime",
  },
];

const lessons = [
  {
    id: "cs-language-basics",
    moduleId: "csharp-language-basics",
    level: "Foundations",
    order: 1,
    title: "Language basics, types and control flow",
    titleUk: "Основи мови, типи та control flow",
    summary: "Start with the pieces that appear in almost every C# program: strongly typed variables, nullability, expressions, conditions and loops.",
    summaryUk: "Починаємо з речей, які є майже в кожній C# програмі: strongly typed variables, nullability, expressions, умови та цикли.",
    concept: "C# is statically typed: every expression has a type known to the compiler, even when local type inference with `var` hides the explicit spelling. Built-in numeric and Boolean types such as `int`, `double` and `bool` are value types; `string`, arrays and ordinary classes are reference types. Nullable value types use `T?` such as `int?`. With nullable reference types enabled, `string?` means null is expected while `string` communicates that null should not be assigned. Control flow uses familiar `if`, `switch`, `for`, `foreach` and `while` constructs. `var` does not make a variable dynamically typed: the compiler infers one concrete type and that variable keeps it.",
    conceptUk: "C# — statically typed мова: кожен expression має тип, відомий compiler-у, навіть коли local type inference через `var` приховує явне написання типу. Вбудовані numeric та Boolean типи на кшталт `int`, `double`, `bool` є value types; `string`, arrays і звичайні classes — reference types. Nullable value type записується як `T?`, наприклад `int?`. Коли nullable reference types увімкнені, `string?` означає, що `null` очікуваний, а `string` декларує намір не присвоювати null. Control flow використовує `if`, `switch`, `for`, `foreach`, `while`. `var` не робить змінну dynamically typed: compiler виводить один конкретний тип, і далі він не змінюється.",
    keyPoints: [
      "`var` is compile-time type inference, not dynamic typing",
      "Value types hold their value directly; reference-type variables hold a reference to an object",
      "Nullable annotations express null expectations and let the compiler warn about unsafe dereferences",
    ],
    keyPointsUk: [
      "`var` — це compile-time type inference, а не dynamic typing",
      "Value types зберігають значення безпосередньо; reference-type variables зберігають reference на object",
      "Nullable annotations описують очікування щодо null і дають compiler-у можливість попереджати про небезпечне dereference",
    ],
    codeLanguage: "csharp",
    code: "string name = \"Ada\";\nint? retries = null;\nvar score = 90; // inferred as int\n\nif (score >= 80)\n{\n    Console.WriteLine($\"{name}: passed\");\n}\n\nforeach (var value in new[] { 1, 2, 3 })\n{\n    Console.WriteLine(value);\n}",
    codeCaption: "Explicit types and `var` coexist; the inferred variable is still an `int`.",
    codeCaptionUk: "Explicit types і `var` використовуються разом; inferred variable усе одно має тип `int`.",
    pitfalls: [
      "Treating `var` like JavaScript `let` or Python variables; its inferred type cannot later become another type",
      "Assuming every reference is non-null at runtime merely because it is written as a non-nullable reference type",
    ],
    pitfallsUk: [
      "Сприймати `var` як JavaScript `let` або Python variable; inferred type не може потім стати іншим типом",
      "Вважати, що reference гарантовано не може бути null у runtime лише тому, що він записаний як non-nullable reference type",
    ],
    sourceIds: ["csharp-tour", "csharp-type-system"],
  },
  {
    id: "cs-methods-parameters",
    moduleId: "csharp-methods-parameters",
    level: "Foundations",
    order: 1,
    title: "Methods, parameters and overloads",
    titleUk: "Методи, параметри та overloads",
    summary: "A method is defined by its name, parameter list and containing type; C# adds explicit parameter-passing modes and overload resolution.",
    summaryUk: "Method визначається name, parameter list і containing type; C# також має явні режими parameter passing та overload resolution.",
    concept: "Parameters are passed by value by default. For a value type, the method receives a copy of the value; for a reference type, it receives a copy of the reference, so it can mutate the referenced object but cannot replace the caller's variable unless the parameter itself is passed by reference. `ref` passes an existing variable by reference, `out` requires the called method to assign a value before returning, and `in` passes by reference while preventing reassignment through that parameter. Methods may be overloaded when parameter lists differ. The return type alone cannot distinguish overloads. Optional parameters provide defaults, while named arguments make call sites explicit.",
    conceptUk: "За замовчуванням parameters передаються by value. Для value type method отримує copy значення; для reference type — copy самого reference, тому method може змінювати referenced object, але не може підмінити variable у caller без передачі самого parameter by reference. `ref` передає існуючу variable by reference, `out` вимагає присвоїти значення до повернення з method, а `in` передає by reference, але забороняє reassignment через цей parameter. Methods можна overload-ити, якщо parameter lists відрізняються. Лише return type не може розрізняти overloads. Optional parameters задають defaults, named arguments роблять call site явнішим.",
    keyPoints: [
      "Default parameter passing is by value, including a copied reference for class instances",
      "`ref`, `out` and `in` change how the parameter variable itself is passed",
      "Overloads must differ by parameter signature; return type alone is insufficient",
    ],
    keyPointsUk: [
      "Default parameter passing — by value, включно з copy reference для class instances",
      "`ref`, `out` та `in` змінюють спосіб передачі самої parameter variable",
      "Overloads мають відрізнятися parameter signature; одного return type недостатньо",
    ],
    codeLanguage: "csharp",
    code: "static bool TryParsePort(string text, out int port)\n{\n    return int.TryParse(text, out port) && port is > 0 and <= 65535;\n}\n\nstatic decimal Total(decimal price, int quantity = 1) => price * quantity;\n\nif (TryParsePort(\"8080\", out var port))\n{\n    Console.WriteLine(port);\n}\n\nConsole.WriteLine(Total(price: 12.5m, quantity: 2));",
    codeCaption: "`out`, optional parameters, named arguments and expression-bodied methods in one small example.",
    codeCaptionUk: "`out`, optional parameters, named arguments та expression-bodied method в одному прикладі.",
    pitfalls: [
      "Saying a class object is passed by reference by default; the object reference is passed by value",
      "Creating overloads that differ only by return type; the compiler cannot resolve those calls",
    ],
    pitfallsUk: [
      "Казати, що class object за замовчуванням передається by reference; насправді object reference передається by value",
      "Створювати overloads, які відрізняються лише return type; compiler не зможе resolve такий call",
    ],
    sourceIds: ["csharp-tour", "csharp-type-system"],
  },
  {
    id: "cs-classes-objects",
    moduleId: "csharp-classes-objects",
    level: "Foundations",
    order: 1,
    title: "Classes, objects, constructors and access modifiers",
    titleUk: "Класи, об’єкти, constructors та access modifiers",
    summary: "Classes define reference-type blueprints; objects are their runtime instances with state and behavior.",
    summaryUk: "Classes визначають blueprint для reference types; objects — runtime instances із state та behavior.",
    concept: "A class groups state and behavior. Fields store implementation state; properties expose controlled access through `get`/`set` or `init`; methods implement behavior. A constructor establishes a valid initial state. `static` members belong to the type rather than an instance. The most common access modifiers are `public`, `private`, `protected` and `internal`; keeping fields private and exposing only the behavior or properties callers need is a basic encapsulation practice. An object is created with `new` and, for ordinary classes, variables point to that object through references.",
    conceptUk: "Class групує state та behavior. Fields зберігають implementation state; properties надають контрольований доступ через `get`/`set` або `init`; methods реалізують behavior. Constructor формує валідний initial state. `static` members належать type, а не конкретному instance. Найуживаніші access modifiers — `public`, `private`, `protected`, `internal`; private fields і мінімальний public surface — базова практика encapsulation. Object створюється через `new`, а для звичайного class variables посилаються на нього через references.",
    keyPoints: [
      "Class = type definition; object = runtime instance of that class",
      "Constructors establish initial state and can be overloaded",
      "Properties are part of the public contract; fields are commonly kept private",
    ],
    keyPointsUk: [
      "Class = визначення type; object = runtime instance цього class",
      "Constructors формують initial state і можуть бути overloaded",
      "Properties є частиною public contract; fields зазвичай залишають private",
    ],
    codeLanguage: "csharp",
    code: "public class TestRun\n{\n    private int _failed;\n\n    public string Name { get; }\n    public int Failed => _failed;\n\n    public TestRun(string name)\n    {\n        Name = name;\n    }\n\n    public void AddFailure() => _failed++;\n}\n\nvar run = new TestRun(\"Smoke\");\nrun.AddFailure();",
    codeCaption: "Private state is changed through public behavior instead of exposing the field directly.",
    codeCaptionUk: "Private state змінюється через public behavior, а не через прямий доступ до field.",
    pitfalls: [
      "Exposing every field as public and then having no control over valid object state",
      "Confusing a static member with a singleton instance; `static` simply belongs to the type",
    ],
    pitfallsUk: [
      "Робити всі fields public і втрачати контроль над valid object state",
      "Плутати static member із singleton instance; `static` означає лише належність до type",
    ],
    sourceIds: ["csharp-tour", "csharp-oop-docs"],
  },
  {
    id: "cs-oop",
    moduleId: "csharp-oop",
    level: "Core",
    order: 1,
    title: "Encapsulation, inheritance, polymorphism and abstraction",
    titleUk: "Encapsulation, inheritance, polymorphism та abstraction",
    summary: "The four classic OOP ideas become concrete in C# through visibility, base classes, virtual dispatch and abstract contracts.",
    summaryUk: "Чотири класичні OOP concepts у C# реалізуються через visibility, base classes, virtual dispatch та abstract contracts.",
    concept: "Encapsulation protects an object's internal state behind a deliberate public API. Inheritance lets a derived class reuse and specialize a base class. Polymorphism means code written against a base type can execute behavior supplied by a derived runtime object; in C# this commonly uses `virtual` on the base member and `override` in the derived class. Abstraction exposes the essential contract while hiding implementation details, using interfaces or abstract classes. `abstract` members have no base implementation and must be implemented by a concrete derived class; `sealed` can prevent further inheritance or overriding.",
    conceptUk: "Encapsulation захищає internal state object-а за свідомо спроєктованим public API. Inheritance дозволяє derived class повторно використати й спеціалізувати base class. Polymorphism означає, що code, написаний проти base type, може виконати behavior конкретного derived runtime object; у C# для цього часто використовують `virtual` у base member та `override` у derived class. Abstraction показує суттєвий contract і приховує implementation details через interfaces або abstract classes. `abstract` member не має base implementation і мусить бути реалізований concrete derived class; `sealed` може заборонити подальше inheritance або overriding.",
    keyPoints: [
      "Inheritance models an is-a relationship; composition is often preferable for has-a relationships",
      "Runtime polymorphism requires an overridable contract such as virtual/abstract members or interfaces",
      "`override` replaces virtual behavior polymorphically; `new` hides a member and is a different mechanism",
    ],
    keyPointsUk: [
      "Inheritance моделює is-a relationship; для has-a relationships часто краща composition",
      "Runtime polymorphism потребує overridable contract: virtual/abstract members або interfaces",
      "`override` polymorphically замінює virtual behavior; `new` лише hides member і працює інакше",
    ],
    codeLanguage: "csharp",
    code: "public abstract class Reporter\n{\n    public abstract string BuildReport();\n}\n\npublic sealed class JsonReporter : Reporter\n{\n    public override string BuildReport() => \"{ \\\"status\\\": \\\"ok\\\" }\";\n}\n\nReporter reporter = new JsonReporter();\nConsole.WriteLine(reporter.BuildReport());",
    codeCaption: "The variable has the base type, while virtual dispatch executes the derived implementation.",
    codeCaptionUk: "Variable має base type, але virtual dispatch виконує derived implementation.",
    pitfalls: [
      "Using inheritance only to reuse a few lines of code even when the types do not have a real is-a relationship",
      "Confusing method hiding with overriding and then getting different behavior depending on the variable's compile-time type",
    ],
    pitfallsUk: [
      "Використовувати inheritance лише заради reuse кількох рядків, коли між types немає реального is-a relationship",
      "Плутати method hiding з overriding і отримувати різний behavior залежно від compile-time type variable",
    ],
    sourceIds: ["csharp-oop-docs"],
  },
  {
    id: "cs-abstractions",
    moduleId: "csharp-abstractions",
    level: "Core",
    order: 1,
    title: "Interfaces, abstract classes, structs and records",
    titleUk: "Interfaces, abstract classes, structs та records",
    summary: "C# offers several type shapes because a behavioral contract, shared base implementation and data value are different design problems.",
    summaryUk: "C# має кілька type shapes, тому що behavioral contract, shared base implementation та data value — різні design problems.",
    concept: "An interface describes a capability or contract and a class can implement multiple interfaces. An abstract class can define abstract members and also carry shared state, constructors and implemented behavior, but a class can inherit from only one base class. A `struct` is a value type and is best suited to small value-like data where copy semantics make sense. A `record` is designed for data-centric models and provides value-based equality by default; records can be reference types (`record`) or value types (`record struct`). These constructs overlap, but they are not interchangeable.",
    conceptUk: "Interface описує capability або contract, і class може implement кілька interfaces. Abstract class може мати abstract members, shared state, constructors та вже реалізований behavior, але class може inherit лише один base class. `struct` — value type, доречний для невеликих value-like data, де copy semantics логічні. `record` орієнтований на data-centric models і за замовчуванням дає value-based equality; records можуть бути reference types (`record`) або value types (`record struct`). Ці constructs перетинаються, але не є взаємозамінними.",
    keyPoints: [
      "Use an interface for a contract that unrelated types can implement",
      "Use an abstract class when derived types need a shared base implementation or state",
      "Structs copy by value; records primarily add data-oriented syntax and value equality semantics",
    ],
    keyPointsUk: [
      "Interface підходить для contract, який можуть implement unrelated types",
      "Abstract class підходить, коли derived types потребують shared base implementation або state",
      "Structs копіюються by value; records передусім дають data-oriented syntax та value equality semantics",
    ],
    codeLanguage: "csharp",
    code: "public interface IHealthCheck\n{\n    bool IsHealthy();\n}\n\npublic class ApiHealthCheck : IHealthCheck\n{\n    public bool IsHealthy() => true;\n}\n\npublic readonly record struct Coordinate(int X, int Y);\n\nIHealthCheck check = new ApiHealthCheck();\nvar point = new Coordinate(10, 20);",
    codeCaption: "The interface models behavior; the record struct models a small immutable value.",
    codeCaptionUk: "Interface моделює behavior; record struct моделює невелике immutable value.",
    pitfalls: [
      "Choosing an abstract class only because interfaces cannot store instance fields, then forcing unrelated types into one inheritance tree",
      "Using a mutable large struct and unexpectedly copying it many times",
    ],
    pitfallsUk: [
      "Обирати abstract class лише тому, що interfaces не зберігають instance fields, і змушувати unrelated types входити в одне inheritance tree",
      "Використовувати великий mutable struct і неочікувано копіювати його багато разів",
    ],
    sourceIds: ["csharp-interfaces", "csharp-type-system", "csharp-oop-docs"],
  },
  {
    id: "cs-collections-generics",
    moduleId: "csharp-collections-generics",
    level: "Core",
    order: 1,
    title: "Collections, generics and IEnumerable",
    titleUk: "Collections, generics та IEnumerable",
    summary: "Generic collections give type-safe containers, while IEnumerable<T> is the common abstraction for a sequence that can be enumerated.",
    summaryUk: "Generic collections дають type-safe containers, а IEnumerable<T> є спільною abstraction для sequence, яку можна enumerate.",
    concept: "`List<T>` is an ordered resizable sequence, `Dictionary<TKey,TValue>` maps unique keys to values, and `HashSet<T>` stores unique values with set-style operations. Generics let the same algorithm or data structure work with different types while keeping compile-time type safety. `IEnumerable<T>` represents something that can yield elements one by one; `foreach` works over this enumeration pattern. It does not promise indexing, a known count or mutability. Depending on the source, enumerating an `IEnumerable<T>` may execute work each time, which matters when the sequence comes from LINQ or an external provider.",
    conceptUk: "`List<T>` — ordered resizable sequence, `Dictionary<TKey,TValue>` мапить unique keys на values, а `HashSet<T>` зберігає unique values і підтримує set operations. Generics дозволяють одному algorithm або data structure працювати з різними types без втрати compile-time type safety. `IEnumerable<T>` означає щось, що може по одному yield elements; `foreach` працює поверх цього enumeration pattern. Він не гарантує indexing, known count чи mutability. Залежно від source, кожне enumeration `IEnumerable<T>` може повторно виконувати роботу — це важливо для LINQ або зовнішніх providers.",
    keyPoints: [
      "Choose collections by access semantics, not by habit: sequence, key lookup or uniqueness",
      "Generics provide reuse without falling back to `object` and repeated casts",
      "`IEnumerable<T>` promises enumeration, not a concrete in-memory collection",
    ],
    keyPointsUk: [
      "Collections треба обирати за access semantics: sequence, key lookup або uniqueness",
      "Generics дають reuse без переходу до `object` і повторних casts",
      "`IEnumerable<T>` гарантує enumeration, а не конкретну in-memory collection",
    ],
    codeLanguage: "csharp",
    code: "var tests = new List<string> { \"login\", \"checkout\" };\nvar durations = new Dictionary<string, int>\n{\n    [\"login\"] = 120,\n    [\"checkout\"] = 350\n};\nvar tags = new HashSet<string> { \"smoke\", \"api\", \"smoke\" };\n\nIEnumerable<string> names = tests;\nforeach (var test in names)\n{\n    Console.WriteLine(test);\n}",
    codeCaption: "Three common generic collections plus the sequence abstraction they can expose.",
    codeCaptionUk: "Три поширені generic collections і sequence abstraction, яку вони можуть expose.",
    pitfalls: [
      "Using `List<T>` for repeated key lookup when a dictionary expresses the operation better",
      "Assuming an `IEnumerable<T>` can be indexed or enumerated repeatedly without cost",
    ],
    pitfallsUk: [
      "Використовувати `List<T>` для постійного key lookup, коли `Dictionary` краще виражає operation",
      "Вважати, що `IEnumerable<T>` можна index або багаторазово enumerate без додаткової вартості",
    ],
    sourceIds: ["dotnet-collections", "csharp-generics"],
  },
  {
    id: "cs-delegates-linq",
    moduleId: "csharp-delegates-linq",
    level: "Core",
    order: 1,
    title: "Delegates, events, lambdas and LINQ",
    titleUk: "Delegates, events, lambdas та LINQ",
    summary: "Delegates represent executable methods, lambdas create them concisely, events restrict publication, and LINQ composes sequence operations.",
    summaryUk: "Delegates представляють executable methods, lambdas створюють їх компактно, events обмежують publication, а LINQ компонує operations над sequences.",
    concept: "A delegate is a strongly typed reference to one or more methods with a compatible signature. `Action` and `Func<...>` are common generic delegate types. A lambda expression is concise syntax for creating a delegate or expression tree. An event is based on a delegate but exposes controlled subscription: outside code can normally add or remove handlers, while only the declaring type raises the event. LINQ provides operators such as `Where`, `Select`, `OrderBy`, `Any` and `FirstOrDefault`. Many LINQ operators use deferred execution, meaning the query is built now but actually enumerated later.",
    conceptUk: "Delegate — strongly typed reference на один або кілька methods із compatible signature. `Action` та `Func<...>` — поширені generic delegate types. Lambda expression — короткий syntax для створення delegate або expression tree. Event базується на delegate, але дає controlled subscription: зовнішній code зазвичай може додавати/видаляти handlers, а raise event може лише declaring type. LINQ має operators `Where`, `Select`, `OrderBy`, `Any`, `FirstOrDefault`. Багато LINQ operators використовують deferred execution: query будується зараз, а реально enumerated пізніше.",
    keyPoints: [
      "Delegate = typed callable reference; lambda = concise callable syntax",
      "Events separate subscription from the right to publish",
      "LINQ chains sequence transformations, often with deferred execution",
    ],
    keyPointsUk: [
      "Delegate = typed callable reference; lambda = компактний callable syntax",
      "Events розділяють subscription і право publish подію",
      "LINQ ланцюжить sequence transformations, часто з deferred execution",
    ],
    codeLanguage: "csharp",
    code: "var results = new[] { 200, 500, 404, 201 };\n\nFunc<int, bool> isFailure = status => status >= 400;\nvar failures = results\n    .Where(isFailure)\n    .OrderBy(status => status)\n    .ToList();\n\nforeach (var status in failures)\n{\n    Console.WriteLine(status);\n}",
    codeCaption: "A lambda is stored in a delegate and passed into a LINQ operator.",
    codeCaptionUk: "Lambda зберігається в delegate і передається у LINQ operator.",
    pitfalls: [
      "Assuming a LINQ query has already executed before it is enumerated or materialized",
      "Exposing a delegate field publicly when an event better models subscribe/unsubscribe behavior",
    ],
    pitfallsUk: [
      "Вважати, що LINQ query вже виконався до enumeration або materialization",
      "Expose public delegate field там, де event краще моделює subscribe/unsubscribe behavior",
    ],
    sourceIds: ["csharp-delegates", "csharp-linq"],
  },
  {
    id: "cs-exceptions-disposal",
    moduleId: "csharp-exceptions-disposal",
    level: "Core",
    order: 1,
    title: "Exceptions and deterministic resource cleanup",
    titleUk: "Exceptions та deterministic cleanup ресурсів",
    summary: "Exceptions signal exceptional failure paths; IDisposable and using handle resources whose lifetime should not depend on garbage collection.",
    summaryUk: "Exceptions сигналізують exceptional failure paths; IDisposable та using керують ресурсами, lifetime яких не повинен залежати від garbage collection.",
    concept: "`try` contains code that may fail, `catch` handles selected exceptions, and `finally` runs whether the operation succeeds or throws. Catch the most specific exception you can actually handle; swallowing `Exception` without action hides failures. `throw;` inside a catch rethrows while preserving the original stack trace, whereas `throw ex;` resets useful stack information. Managed memory is reclaimed by the garbage collector, but resources such as files, streams and some OS handles often need deterministic cleanup. Types that own such resources commonly implement `IDisposable`; a `using` statement/declaration ensures `Dispose()` is called even when an exception occurs.",
    conceptUk: "`try` містить code, який може fail, `catch` обробляє вибрані exceptions, а `finally` виконується і при success, і при throw. Треба catch найбільш specific exception, який ви реально можете handle; мовчазний `catch (Exception)` приховує failures. `throw;` всередині catch rethrow зберігає original stack trace, тоді як `throw ex;` втрачає корисну stack information. Managed memory звільняє garbage collector, але files, streams та деякі OS handles потребують deterministic cleanup. Types, що володіють такими ресурсами, часто implement `IDisposable`; `using` гарантує `Dispose()` навіть коли виникає exception.",
    keyPoints: [
      "Exceptions are for exceptional paths, not routine branching",
      "Prefer specific catches and preserve stack traces when rethrowing",
      "GC manages memory; `Dispose`/`using` manages deterministic release of disposable resources",
    ],
    keyPointsUk: [
      "Exceptions призначені для exceptional paths, а не звичайного branching",
      "Краще specific catches і збереження stack trace під час rethrow",
      "GC керує memory; `Dispose`/`using` — deterministic release disposable resources",
    ],
    codeLanguage: "csharp",
    code: "try\n{\n    using var reader = File.OpenText(\"settings.txt\");\n    Console.WriteLine(reader.ReadToEnd());\n}\ncatch (FileNotFoundException ex)\n{\n    Console.WriteLine($\"Missing file: {ex.FileName}\");\n}",
    codeCaption: "The file reader is disposed on both the success and exception paths.",
    codeCaptionUk: "File reader буде disposed і при success, і при exception path.",
    pitfalls: [
      "Catching every exception and continuing with an invalid state",
      "Relying on the garbage collector to promptly close files or other disposable resources",
    ],
    pitfallsUk: [
      "Catch усіх exceptions і продовження роботи з invalid state",
      "Покладатися на garbage collector для своєчасного закриття files чи інших disposable resources",
    ],
    sourceIds: ["csharp-exceptions", "dotnet-gc"],
  },
  {
    id: "cs-async",
    moduleId: "csharp-async",
    level: "Core",
    order: 1,
    title: "async, await, Task and concurrency basics",
    titleUk: "async, await, Task та основи concurrency",
    summary: "async/await lets code suspend around incomplete asynchronous operations without blocking a thread for the whole wait.",
    summaryUk: "async/await дозволяє code suspend на незавершеній asynchronous operation без блокування thread протягом усього очікування.",
    concept: "A `Task` represents work that may complete later. Marking a method `async` allows `await`, but `async` alone does not create a new thread. When an awaited operation is incomplete, the method can return control to its caller and continue later after completion. This is especially useful for I/O such as HTTP, database and file operations. Asynchrony and parallelism are different: async is about not blocking while waiting; parallelism is about executing CPU work simultaneously. Prefer `Task`/`Task<T>` return types for async methods; `async void` is mainly reserved for event handlers because callers cannot await it or observe failures normally.",
    conceptUk: "`Task` представляє work, що може завершитися пізніше. `async` дозволяє використовувати `await`, але сам по собі не створює new thread. Якщо awaited operation ще не завершена, method може повернути control caller-у і продовжити після completion. Це особливо корисно для I/O: HTTP, database, files. Asynchrony і parallelism — різні речі: async не блокує під час waiting; parallelism одночасно виконує CPU work. Для async methods варто повертати `Task`/`Task<T>`; `async void` переважно залишають event handlers, бо caller не може нормально await його або спостерігати failures.",
    keyPoints: [
      "`async` does not automatically mean another thread",
      "`await` asynchronously waits for a Task and resumes the method when it completes",
      "Use Task-returning methods so callers can await completion and observe exceptions",
    ],
    keyPointsUk: [
      "`async` не означає автоматичне створення іншого thread",
      "`await` asynchronous waits Task і продовжує method після completion",
      "Task-returning methods дають caller-у можливість await completion та observe exceptions",
    ],
    codeLanguage: "csharp",
    code: "static async Task<int> GetStatusAsync(HttpClient client, string url)\n{\n    using var response = await client.GetAsync(url);\n    return (int)response.StatusCode;\n}\n\nusing var client = new HttpClient();\nint status = await GetStatusAsync(client, \"https://example.com\");\nConsole.WriteLine(status);",
    codeCaption: "The HTTP wait is asynchronous; the method returns a Task<int> that the caller can await.",
    codeCaptionUk: "HTTP wait є asynchronous; method повертає Task<int>, який caller може await.",
    pitfalls: [
      "Using `.Result` or `.Wait()` everywhere and turning asynchronous code back into blocking code",
      "Assuming `async` makes CPU-heavy work parallel or faster by itself",
    ],
    pitfallsUk: [
      "Всюди використовувати `.Result` або `.Wait()` і перетворювати asynchronous code назад на blocking",
      "Вважати, що `async` сам робить CPU-heavy work parallel або швидшим",
    ],
    sourceIds: ["csharp-async-docs"],
  },
  {
    id: "cs-runtime-memory",
    moduleId: "csharp-runtime-memory",
    level: "Core",
    order: 1,
    title: "Managed memory, garbage collection, boxing and equality",
    titleUk: "Managed memory, garbage collection, boxing та equality",
    summary: "C# runs on a managed runtime: object lifetime, value/reference behavior and equality rules are more useful than memorizing a simplistic stack-versus-heap slogan.",
    summaryUk: "C# працює на managed runtime: object lifetime, value/reference behavior та equality rules важливіші за спрощене правило stack-versus-heap.",
    concept: "The .NET garbage collector manages memory for managed objects and reclaims objects that are no longer reachable. It uses generations to optimize around the observation that many objects die young. Value types and reference types differ primarily in assignment/copy semantics, not by a universal rule that one always lives on the stack and the other always on the heap; storage location depends on context. Boxing converts a value type to `object` or an implemented interface by placing a boxed copy in a reference-type object; unboxing extracts it back to the value type. Equality also has layers: reference equality asks whether two references point to the same object, while value equality asks whether their contents should be considered equal. Records provide value equality by default; ordinary classes default to reference-based `Equals` behavior unless customized.",
    conceptUk: " .NET garbage collector керує memory managed objects і звільняє objects, які більше не reachable. Він використовує generations, оптимізуючись під те, що багато objects живуть недовго. Value types і reference types відрізняються насамперед assignment/copy semantics, а не універсальним правилом «value завжди stack, reference завжди heap»; storage location залежить від context. Boxing перетворює value type на `object` або implemented interface, створюючи boxed copy в reference-type object; unboxing дістає value назад. Equality також має рівні: reference equality питає, чи два references вказують на один object, value equality — чи їхній content вважається рівним. Records мають value equality by default; звичайні classes за замовчуванням мають reference-oriented `Equals`, якщо behavior не перевизначений.",
    keyPoints: [
      "GC tracks reachability and reclaims managed objects; it does not replace deterministic disposal",
      "Value/reference is mainly a semantic distinction about copying and identity, not a guaranteed physical memory location",
      "Boxing creates a reference-type wrapper/copy for a value type and can add allocation/copy overhead",
    ],
    keyPointsUk: [
      "GC відстежує reachability і звільняє managed objects; він не замінює deterministic disposal",
      "Value/reference — передусім semantic distinction про copying та identity, а не guaranteed physical memory location",
      "Boxing створює reference-type wrapper/copy для value type і може додавати allocation/copy overhead",
    ],
    codeLanguage: "csharp",
    code: "int number = 42;\nobject boxed = number;   // boxing\nint copy = (int)boxed;   // unboxing\n\nvar a = new object();\nvar b = a;\nConsole.WriteLine(ReferenceEquals(a, b)); // True\n\nvar p1 = new Point(1, 2);\nvar p2 = new Point(1, 2);\nConsole.WriteLine(p1 == p2); // True for records\n\npublic record Point(int X, int Y);",
    codeCaption: "The example contrasts boxing, object identity and record value equality.",
    codeCaptionUk: "Приклад порівнює boxing, object identity та record value equality.",
    pitfalls: [
      "Repeating 'value types are on the stack and reference types are on the heap' as an absolute runtime rule",
      "Assuming `==`, `Equals` and `ReferenceEquals` always mean the same kind of equality",
    ],
    pitfallsUk: [
      "Повторювати «value types на stack, reference types на heap» як абсолютне runtime правило",
      "Вважати, що `==`, `Equals` та `ReferenceEquals` завжди означають один тип equality",
    ],
    sourceIds: ["csharp-type-system", "dotnet-gc"],
  },
];

export const csharpCurriculum = {
  version: 1,
  title: "C# programming fundamentals",
  titleUk: "Основи програмування на C#",
  description: "A deliberately incomplete C# foundation focused on the language and runtime concepts most useful before moving into frameworks and test automation.",
  lastReviewedAt: null,
  methodology: {
    coverage: "A focused first slice of C# fundamentals. It is intentionally not a complete language course and remains under review.",
    answers: "Explanations are grounded primarily in Microsoft Learn documentation and use small executable-style examples.",
    publishing: "The section is visible early with a Waiting for review marker so content can be reviewed and expanded iteratively.",
  },
  taxonomy,
  sources,
  lessons,
};

export default csharpCurriculum;
