const lines = (...items: string[]) => items.join("\n");

const sources = [
  {
    id: "csharp-tour",
    title: "A tour of C#",
    url: "https://learn.microsoft.com/en-us/dotnet/csharp/tour-of-csharp/",
    publisher: "Microsoft Learn",
    kind: "Official documentation",
    role: "Core language syntax, control flow, methods, classes and general C# semantics",
  },
  {
    id: "csharp-type-system",
    title: "The C# type system",
    url: "https://learn.microsoft.com/en-us/dotnet/csharp/fundamentals/types/",
    publisher: "Microsoft Learn",
    kind: "Official documentation",
    role: "Value/reference types, nullability, conversions and type-system fundamentals",
  },
  {
    id: "csharp-oop-docs",
    title: "Object-oriented programming",
    url: "https://learn.microsoft.com/en-us/dotnet/csharp/fundamentals/object-oriented/",
    publisher: "Microsoft Learn",
    kind: "Official documentation",
    role: "Encapsulation, inheritance, polymorphism and abstraction",
  },
  {
    id: "csharp-interfaces",
    title: "Interfaces",
    url: "https://learn.microsoft.com/en-us/dotnet/csharp/fundamentals/types/interfaces",
    publisher: "Microsoft Learn",
    kind: "Official documentation",
    role: "Interface contracts and implementation",
  },
  {
    id: "dotnet-collections",
    title: "Collections and data structures",
    url: "https://learn.microsoft.com/en-us/dotnet/standard/collections/",
    publisher: "Microsoft Learn",
    kind: "Official documentation",
    role: "Collection families, generic collections and common selection trade-offs",
  },
  {
    id: "csharp-generics",
    title: "Generics",
    url: "https://learn.microsoft.com/en-us/dotnet/csharp/fundamentals/types/generics",
    publisher: "Microsoft Learn",
    kind: "Official documentation",
    role: "Generic types, methods and type parameters",
  },
  {
    id: "csharp-delegates",
    title: "Delegates",
    url: "https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/delegates/",
    publisher: "Microsoft Learn",
    kind: "Official documentation",
    role: "Delegate types, callbacks and event foundations",
  },
  {
    id: "csharp-linq",
    title: "Language Integrated Query (LINQ)",
    url: "https://learn.microsoft.com/en-us/dotnet/csharp/linq/",
    publisher: "Microsoft Learn",
    kind: "Official documentation",
    role: "LINQ operators, sequence queries and deferred execution",
  },
  {
    id: "csharp-exceptions",
    title: "Exceptions and exception handling",
    url: "https://learn.microsoft.com/en-us/dotnet/csharp/fundamentals/exceptions/",
    publisher: "Microsoft Learn",
    kind: "Official documentation",
    role: "Exception flow and handling rules",
  },
  {
    id: "csharp-async-docs",
    title: "Asynchronous programming with async and await",
    url: "https://learn.microsoft.com/en-us/dotnet/csharp/asynchronous-programming/",
    publisher: "Microsoft Learn",
    kind: "Official documentation",
    role: "Task-based asynchronous programming, async and await",
  },
  {
    id: "dotnet-gc",
    title: "Fundamentals of garbage collection",
    url: "https://learn.microsoft.com/en-us/dotnet/standard/garbage-collection/fundamentals",
    publisher: "Microsoft Learn",
    kind: "Official documentation",
    role: "Managed heap, generations, collection and object lifetime",
  },
];

const taxonomy = [
  {
    id: "csharp-language-basics",
    label: "Language basics, types & control flow",
    labelUk: "Основи мови, типи та control flow",
    level: "Foundations",
    description: "Core C# syntax, variables, nullability, value/reference types, conditions and loops.",
    descriptionUk: "Базовий синтаксис C#, змінні, nullability, value/reference types, умови та цикли.",
    sourceIds: ["csharp-tour", "csharp-type-system"],
    markdown: lines(
      "# Language basics, types & control flow",
      "",
      "C# is a statically typed language. Every expression has a compile-time type, including local variables declared with `var`. `var` asks the compiler to infer the type; it does not make the variable dynamically typed.",
      "",
      "## Types and nullability",
      "",
      "Built-in types such as `int`, `double`, `bool`, `char` and user-defined `struct` types are value types. Classes, arrays, delegates and `string` are reference types. The important distinction is assignment and identity semantics: assigning a value type copies its value; assigning a reference-type variable copies the reference to the same object.",
      "",
      "Nullable value types use `T?`, for example `int?`. With nullable reference types enabled, `string?` communicates that null is expected, while `string` communicates that callers should treat the value as non-null.",
      "",
      "```csharp",
      "string name = \"Ada\";",
      "int? retries = null;",
      "var score = 90;      // inferred as int",
      "string? note = null; // nullable reference",
      "```",
      "",
      "## Conditions and loops",
      "",
      "C# uses `if`, `switch`, `for`, `foreach`, `while` and `do`. Pattern matching can also appear inside conditions and switch expressions.",
      "",
      "```csharp",
      "if (score >= 80)",
      "{",
      "    Console.WriteLine($\"{name}: passed\");",
      "}",
      "",
      "foreach (var value in new[] { 1, 2, 3 })",
      "{",
      "    Console.WriteLine(value);",
      "}",
      "```",
      "",
      "## Key points",
      "",
      "- `var` is compile-time type inference, not dynamic typing.",
      "- Value types and reference types differ primarily in copy/identity semantics.",
      "- Nullable annotations describe intent and enable compiler warnings; they do not magically prevent every runtime null.",
      "- `foreach` is the normal way to enumerate a sequence when you do not need manual indexing."
    ),
    markdownUk: lines(
      "# Основи мови, типи та control flow",
      "",
      "C# — statically typed мова. Кожен expression має compile-time type, включно з local variables, оголошеними через `var`. `var` лише просить compiler вивести тип; variable не стає dynamically typed.",
      "",
      "## Типи та nullability",
      "",
      "Вбудовані типи `int`, `double`, `bool`, `char` і user-defined `struct` є value types. Classes, arrays, delegates і `string` — reference types. Головна різниця тут у semantics присвоєння та identity: присвоєння value type копіює значення, а присвоєння reference-type variable копіює reference на той самий object.",
      "",
      "Nullable value types записуються як `T?`, наприклад `int?`. Коли nullable reference types увімкнені, `string?` означає, що null очікуваний, а `string` декларує намір працювати з non-null value.",
      "",
      "```csharp",
      "string name = \"Ada\";",
      "int? retries = null;",
      "var score = 90;      // inferred as int",
      "string? note = null; // nullable reference",
      "```",
      "",
      "## Умови та цикли",
      "",
      "C# використовує `if`, `switch`, `for`, `foreach`, `while`, `do`. Pattern matching також може бути частиною conditions і switch expressions.",
      "",
      "```csharp",
      "if (score >= 80)",
      "{",
      "    Console.WriteLine($\"{name}: passed\");",
      "}",
      "",
      "foreach (var value in new[] { 1, 2, 3 })",
      "{",
      "    Console.WriteLine(value);",
      "}",
      "```",
      "",
      "## Ключові моменти",
      "",
      "- `var` — compile-time type inference, а не dynamic typing.",
      "- Value types і reference types насамперед відрізняються copy/identity semantics.",
      "- Nullable annotations описують намір і дають compiler warnings, але не роблять runtime null фізично неможливим.",
      "- `foreach` — типовий спосіб enumerate sequence, коли ручний index не потрібний."
    ),
  },
  {
    id: "csharp-methods-parameters",
    label: "Methods, parameters & overloads",
    labelUk: "Методи, параметри та overloads",
    level: "Foundations",
    description: "Method signatures, return values, optional/named parameters, ref/out/in and overloading.",
    descriptionUk: "Сигнатури methods, return values, optional/named parameters, ref/out/in та overloads.",
    sourceIds: ["csharp-tour", "csharp-type-system"],
    markdown: lines(
      "# Methods, parameters & overloads",
      "",
      "A method groups behavior behind a name and parameter list. Parameters are passed by value by default. For a class instance this means the method receives a copy of the reference: it can mutate the referenced object, but it cannot replace the caller's variable unless the parameter variable itself is passed by reference.",
      "",
      "## `ref`, `out` and `in`",
      "",
      "- `ref` passes an existing variable by reference; it must already be assigned.",
      "- `out` passes by reference and requires the called method to assign a value before returning.",
      "- `in` passes by reference but prevents reassignment through that parameter.",
      "",
      "```csharp",
      "static bool TryParsePort(string text, out int port)",
      "{",
      "    return int.TryParse(text, out port) && port is > 0 and <= 65535;",
      "}",
      "",
      "if (TryParsePort(\"8080\", out var port))",
      "{",
      "    Console.WriteLine(port);",
      "}",
      "```",
      "",
      "## Overloading and optional parameters",
      "",
      "Methods can share the same name when their parameter signatures differ. Return type alone cannot distinguish overloads. Optional parameters define defaults, while named arguments make the meaning of call-site values explicit.",
      "",
      "```csharp",
      "static decimal Total(decimal price, int quantity = 1) => price * quantity;",
      "",
      "Console.WriteLine(Total(12.5m));",
      "Console.WriteLine(Total(price: 12.5m, quantity: 2));",
      "```",
      "",
      "## Key points",
      "",
      "- Default parameter passing is by value, including a copied reference for reference types.",
      "- `ref`, `out` and `in` change how the parameter variable itself is passed.",
      "- Overloads must differ by parameter signature; return type alone is insufficient."
    ),
    markdownUk: lines(
      "# Методи, параметри та overloads",
      "",
      "Method групує behavior за name і parameter list. За замовчуванням parameters передаються by value. Для class instance це означає, що method отримує copy reference: він може mutate referenced object, але не може підмінити variable у caller, якщо сама parameter variable не передана by reference.",
      "",
      "## `ref`, `out` та `in`",
      "",
      "- `ref` передає вже існуючу variable by reference; вона має бути initialized.",
      "- `out` передає by reference і вимагає, щоб called method присвоїв value до return.",
      "- `in` передає by reference, але забороняє reassignment через цей parameter.",
      "",
      "```csharp",
      "static bool TryParsePort(string text, out int port)",
      "{",
      "    return int.TryParse(text, out port) && port is > 0 and <= 65535;",
      "}",
      "",
      "if (TryParsePort(\"8080\", out var port))",
      "{",
      "    Console.WriteLine(port);",
      "}",
      "```",
      "",
      "## Overloading та optional parameters",
      "",
      "Methods можуть мати однакове name, якщо parameter signatures відрізняються. Лише return type не може розрізняти overloads. Optional parameters задають defaults, а named arguments роблять значення в call site зрозумілішими.",
      "",
      "```csharp",
      "static decimal Total(decimal price, int quantity = 1) => price * quantity;",
      "",
      "Console.WriteLine(Total(12.5m));",
      "Console.WriteLine(Total(price: 12.5m, quantity: 2));",
      "```",
      "",
      "## Ключові моменти",
      "",
      "- Default parameter passing — by value, включно з copy reference для reference types.",
      "- `ref`, `out`, `in` змінюють спосіб передачі самої parameter variable.",
      "- Overloads мають відрізнятися parameter signature; одного return type недостатньо."
    ),
  },
  {
    id: "csharp-classes-objects",
    label: "Classes, objects & access modifiers",
    labelUk: "Класи, об’єкти та access modifiers",
    level: "Foundations",
    description: "Classes, instances, constructors, fields, properties, static members and visibility.",
    descriptionUk: "Classes, instances, constructors, fields, properties, static members та visibility.",
    sourceIds: ["csharp-tour", "csharp-oop-docs"],
    markdown: lines(
      "# Classes, objects & access modifiers",
      "",
      "A class defines a reference type that groups state and behavior. An object is a runtime instance of that class. Fields usually hold implementation state; properties expose controlled access; methods implement behavior; constructors establish valid initial state.",
      "",
      "## Class example",
      "",
      "```csharp",
      "public class TestRun",
      "{",
      "    private int _failed;",
      "",
      "    public string Name { get; }",
      "    public int Failed => _failed;",
      "",
      "    public TestRun(string name)",
      "    {",
      "        Name = name;",
      "    }",
      "",
      "    public void AddFailure() => _failed++;",
      "}",
      "",
      "var run = new TestRun(\"Smoke\");",
      "run.AddFailure();",
      "```",
      "",
      "## Access modifiers",
      "",
      "`public` exposes a member broadly. `private` keeps it inside the declaring type. `protected` makes it available to the type and derived types. `internal` limits access to the same assembly. Good encapsulation normally keeps implementation details private and exposes the smallest useful public API.",
      "",
      "`static` members belong to the type itself rather than an object instance. Static does not automatically mean singleton; it only changes ownership and access semantics.",
      "",
      "## Key points",
      "",
      "- Class = type definition; object = runtime instance.",
      "- Constructors establish initial object state and can be overloaded.",
      "- Properties are usually preferable to public mutable fields when state is part of a public API.",
      "- `static` members belong to the type rather than a particular instance."
    ),
    markdownUk: lines(
      "# Класи, об’єкти та access modifiers",
      "",
      "Class визначає reference type, який групує state та behavior. Object — runtime instance цього class. Fields зазвичай зберігають implementation state; properties дають контрольований access; methods реалізують behavior; constructors формують valid initial state.",
      "",
      "## Приклад class",
      "",
      "```csharp",
      "public class TestRun",
      "{",
      "    private int _failed;",
      "",
      "    public string Name { get; }",
      "    public int Failed => _failed;",
      "",
      "    public TestRun(string name)",
      "    {",
      "        Name = name;",
      "    }",
      "",
      "    public void AddFailure() => _failed++;",
      "}",
      "",
      "var run = new TestRun(\"Smoke\");",
      "run.AddFailure();",
      "```",
      "",
      "## Access modifiers",
      "",
      "`public` широко expose member. `private` залишає його всередині declaring type. `protected` дозволяє access у самому type та derived types. `internal` обмежує access тією самою assembly. Нормальна encapsulation зазвичай залишає implementation details private і відкриває мінімальний public API.",
      "",
      "`static` members належать самому type, а не object instance. Static не означає singleton автоматично; це лише інша ownership/access semantics.",
      "",
      "## Ключові моменти",
      "",
      "- Class = визначення type; object = runtime instance.",
      "- Constructors формують initial object state і можуть бути overloaded.",
      "- Properties зазвичай кращі за public mutable fields, якщо state входить у public API.",
      "- `static` members належать type, а не конкретному instance."
    ),
  },
  {
    id: "csharp-oop",
    label: "Object-oriented programming",
    labelUk: "Об’єктно-орієнтоване програмування",
    level: "Core",
    description: "Encapsulation, inheritance, polymorphism and abstraction with practical C# examples.",
    descriptionUk: "Encapsulation, inheritance, polymorphism та abstraction на практичних прикладах C#.",
    sourceIds: ["csharp-oop-docs"],
    markdown: lines(
      "# Object-oriented programming",
      "",
      "The four classic OOP ideas are easiest to understand through the C# mechanisms that implement them.",
      "",
      "## Encapsulation",
      "",
      "Encapsulation keeps internal state behind a deliberate API. Callers should not need to know every field or invariant inside an object.",
      "",
      "## Inheritance and polymorphism",
      "",
      "Inheritance models an is-a relationship. A derived class can reuse and specialize a base class. Runtime polymorphism lets code written against a base type execute behavior supplied by a derived runtime object.",
      "",
      "```csharp",
      "public abstract class Reporter",
      "{",
      "    public abstract string BuildReport();",
      "}",
      "",
      "public sealed class JsonReporter : Reporter",
      "{",
      "    public override string BuildReport() => \"{ \\\"status\\\": \\\"ok\\\" }\";",
      "}",
      "",
      "Reporter reporter = new JsonReporter();",
      "Console.WriteLine(reporter.BuildReport());",
      "```",
      "",
      "The variable is typed as `Reporter`, but virtual dispatch calls the `JsonReporter` implementation.",
      "",
      "## Abstraction",
      "",
      "Abstraction exposes the essential contract while hiding implementation details. C# commonly expresses abstraction through interfaces and abstract classes. `abstract` members have no concrete base implementation; `sealed` can prevent further inheritance or overriding.",
      "",
      "## Key points",
      "",
      "- Encapsulation protects state and invariants behind an API.",
      "- Inheritance is best for real is-a relationships; composition often fits has-a relationships better.",
      "- `virtual`/`override` and abstract members enable runtime polymorphism.",
      "- Method hiding with `new` is not the same mechanism as overriding."
    ),
    markdownUk: lines(
      "# Об’єктно-орієнтоване програмування",
      "",
      "Чотири класичні OOP ideas найкраще розуміти через конкретні C# mechanisms, які їх реалізують.",
      "",
      "## Encapsulation",
      "",
      "Encapsulation приховує internal state за продуманим API. Caller не повинен знати всі fields та invariants всередині object.",
      "",
      "## Inheritance та polymorphism",
      "",
      "Inheritance моделює is-a relationship. Derived class може reuse і specialize base class. Runtime polymorphism дозволяє code, написаному проти base type, виконувати behavior конкретного derived runtime object.",
      "",
      "```csharp",
      "public abstract class Reporter",
      "{",
      "    public abstract string BuildReport();",
      "}",
      "",
      "public sealed class JsonReporter : Reporter",
      "{",
      "    public override string BuildReport() => \"{ \\\"status\\\": \\\"ok\\\" }\";",
      "}",
      "",
      "Reporter reporter = new JsonReporter();",
      "Console.WriteLine(reporter.BuildReport());",
      "```",
      "",
      "Variable має type `Reporter`, але virtual dispatch викликає implementation з `JsonReporter`.",
      "",
      "## Abstraction",
      "",
      "Abstraction показує essential contract і приховує implementation details. У C# для цього часто використовують interfaces та abstract classes. `abstract` member не має concrete base implementation; `sealed` може заборонити further inheritance або overriding.",
      "",
      "## Ключові моменти",
      "",
      "- Encapsulation захищає state та invariants за API.",
      "- Inheritance найкраще підходить для реального is-a relationship; для has-a часто краще composition.",
      "- `virtual`/`override` та abstract members дають runtime polymorphism.",
      "- Method hiding через `new` — не те саме, що overriding."
    ),
  },
  {
    id: "csharp-abstractions",
    label: "Interfaces, abstract classes, structs & records",
    labelUk: "Interfaces, abstract classes, structs та records",
    level: "Core",
    description: "Contracts, shared base behavior and value-oriented data models.",
    descriptionUk: "Contracts, shared base behavior та value-oriented data models.",
    sourceIds: ["csharp-interfaces", "csharp-type-system", "csharp-oop-docs"],
    markdown: lines(
      "# Interfaces, abstract classes, structs & records",
      "",
      "These C# type forms solve different design problems and should not be treated as synonyms.",
      "",
      "## Interface vs abstract class",
      "",
      "An interface describes a capability or contract that unrelated types can implement. A class can implement multiple interfaces. An abstract class can combine abstract members with shared state, constructors and implemented behavior, but a class can inherit from only one base class.",
      "",
      "```csharp",
      "public interface IHealthCheck",
      "{",
      "    bool IsHealthy();",
      "}",
      "",
      "public class ApiHealthCheck : IHealthCheck",
      "{",
      "    public bool IsHealthy() => true;",
      "}",
      "```",
      "",
      "## Structs and records",
      "",
      "A `struct` is a value type and works best for small value-like data where copy semantics make sense. A `record` is designed for data-centric models and provides value-based equality by default. `record` is a reference type; `record struct` is a value type.",
      "",
      "```csharp",
      "public readonly record struct Coordinate(int X, int Y);",
      "",
      "var first = new Coordinate(10, 20);",
      "var second = new Coordinate(10, 20);",
      "Console.WriteLine(first == second); // True",
      "```",
      "",
      "## Key points",
      "",
      "- Interface: behavioral contract that many unrelated types can implement.",
      "- Abstract class: shared base behavior/state plus incomplete members.",
      "- Struct: value type with copy semantics.",
      "- Record: data-oriented type with value equality semantics by default."
    ),
    markdownUk: lines(
      "# Interfaces, abstract classes, structs та records",
      "",
      "Ці C# type forms вирішують різні design problems і не є синонімами.",
      "",
      "## Interface vs abstract class",
      "",
      "Interface описує capability або contract, який можуть implement unrelated types. Class може implement кілька interfaces. Abstract class може поєднувати abstract members, shared state, constructors і вже реалізований behavior, але class може inherit лише один base class.",
      "",
      "```csharp",
      "public interface IHealthCheck",
      "{",
      "    bool IsHealthy();",
      "}",
      "",
      "public class ApiHealthCheck : IHealthCheck",
      "{",
      "    public bool IsHealthy() => true;",
      "}",
      "```",
      "",
      "## Structs та records",
      "",
      "`struct` — value type, який найкраще підходить для невеликих value-like data з логічними copy semantics. `record` орієнтований на data-centric models і за замовчуванням має value-based equality. `record` — reference type; `record struct` — value type.",
      "",
      "```csharp",
      "public readonly record struct Coordinate(int X, int Y);",
      "",
      "var first = new Coordinate(10, 20);",
      "var second = new Coordinate(10, 20);",
      "Console.WriteLine(first == second); // True",
      "```",
      "",
      "## Ключові моменти",
      "",
      "- Interface: behavioral contract для unrelated types.",
      "- Abstract class: shared base behavior/state плюс incomplete members.",
      "- Struct: value type із copy semantics.",
      "- Record: data-oriented type з value equality semantics by default."
    ),
  },
  {
    id: "csharp-collections-generics",
    label: "Collections, generics & IEnumerable",
    labelUk: "Collections, generics та IEnumerable",
    level: "Core",
    description: "List, Dictionary, HashSet, generic type parameters and enumerable sequences.",
    descriptionUk: "List, Dictionary, HashSet, generic type parameters та enumerable sequences.",
    sourceIds: ["dotnet-collections", "csharp-generics"],
    markdown: lines(
      "# Collections, generics & IEnumerable",
      "",
      "Generic collections give type-safe containers. The most common choices solve different access patterns rather than being interchangeable containers.",
      "",
      "## Common collections",
      "",
      "- `List<T>`: ordered resizable sequence.",
      "- `Dictionary<TKey,TValue>`: key-to-value lookup with unique keys.",
      "- `HashSet<T>`: unique values and set operations.",
      "",
      "```csharp",
      "var tests = new List<string> { \"login\", \"checkout\" };",
      "var durations = new Dictionary<string, int>",
      "{",
      "    [\"login\"] = 120,",
      "    [\"checkout\"] = 350",
      "};",
      "",
      "var tags = new HashSet<string> { \"smoke\", \"api\", \"smoke\" };",
      "```",
      "",
      "## Generics",
      "",
      "Generics let a type or method work with different element types while keeping compile-time type safety. `List<string>` and `List<int>` reuse the same generic implementation without falling back to `object` and repeated casts.",
      "",
      "## `IEnumerable<T>`",
      "",
      "`IEnumerable<T>` means that a sequence can yield elements one by one. It does not promise indexing, mutability or even a known count. A sequence can also execute work each time it is enumerated.",
      "",
      "```csharp",
      "IEnumerable<string> names = tests;",
      "",
      "foreach (var test in names)",
      "{",
      "    Console.WriteLine(test);",
      "}",
      "```",
      "",
      "## Key points",
      "",
      "- Choose a collection according to the operation you need: order, key lookup or uniqueness.",
      "- Generics provide reuse with compile-time type safety.",
      "- `IEnumerable<T>` is an enumeration contract, not a guarantee of an in-memory list."
    ),
    markdownUk: lines(
      "# Collections, generics та IEnumerable",
      "",
      "Generic collections дають type-safe containers. Найпоширеніші collections вирішують різні access patterns і не є взаємозамінними просто тому, що всі зберігають data.",
      "",
      "## Поширені collections",
      "",
      "- `List<T>`: ordered resizable sequence.",
      "- `Dictionary<TKey,TValue>`: key-to-value lookup з unique keys.",
      "- `HashSet<T>`: unique values та set operations.",
      "",
      "```csharp",
      "var tests = new List<string> { \"login\", \"checkout\" };",
      "var durations = new Dictionary<string, int>",
      "{",
      "    [\"login\"] = 120,",
      "    [\"checkout\"] = 350",
      "};",
      "",
      "var tags = new HashSet<string> { \"smoke\", \"api\", \"smoke\" };",
      "```",
      "",
      "## Generics",
      "",
      "Generics дозволяють одному type або method працювати з різними element types і зберігати compile-time type safety. `List<string>` та `List<int>` reuse ту саму generic implementation без переходу до `object` та repeated casts.",
      "",
      "## `IEnumerable<T>`",
      "",
      "`IEnumerable<T>` означає, що sequence може yield elements по одному. Він не гарантує indexing, mutability чи навіть known count. Sequence також може виконувати роботу заново при кожному enumeration.",
      "",
      "```csharp",
      "IEnumerable<string> names = tests;",
      "",
      "foreach (var test in names)",
      "{",
      "    Console.WriteLine(test);",
      "}",
      "```",
      "",
      "## Ключові моменти",
      "",
      "- Collection треба обирати за потрібною operation: order, key lookup або uniqueness.",
      "- Generics дають reuse з compile-time type safety.",
      "- `IEnumerable<T>` — enumeration contract, а не гарантія in-memory list."
    ),
  },
  {
    id: "csharp-delegates-linq",
    label: "Delegates, events, lambdas & LINQ",
    labelUk: "Delegates, events, lambdas та LINQ",
    level: "Core",
    description: "Typed callables, event publication, lambda syntax and LINQ sequence operations.",
    descriptionUk: "Typed callables, event publication, lambda syntax та LINQ operations над sequences.",
    sourceIds: ["csharp-delegates", "csharp-linq"],
    markdown: lines(
      "# Delegates, events, lambdas & LINQ",
      "",
      "A delegate is a strongly typed reference to one or more compatible methods. `Action` and `Func<...>` are common generic delegate types. Lambda expressions provide compact syntax for creating delegates.",
      "",
      "## Delegate and lambda",
      "",
      "```csharp",
      "Func<int, bool> isFailure = status => status >= 400;",
      "",
      "Console.WriteLine(isFailure(500)); // True",
      "```",
      "",
      "An event is built on a delegate but controls who can publish it. Outside code normally subscribes or unsubscribes, while the declaring type raises the event.",
      "",
      "## LINQ",
      "",
      "LINQ provides composable operators such as `Where`, `Select`, `OrderBy`, `Any`, `FirstOrDefault` and `GroupBy`. Many operators use deferred execution: the query is defined now but does not actually enumerate the source until a consumer requests the results.",
      "",
      "```csharp",
      "var statuses = new[] { 200, 500, 404, 201 };",
      "",
      "var failures = statuses",
      "    .Where(status => status >= 400)",
      "    .OrderBy(status => status)",
      "    .ToList();",
      "```",
      "",
      "`ToList()` materializes the query immediately. Without it, many LINQ pipelines remain deferred and can re-run when enumerated again.",
      "",
      "## Key points",
      "",
      "- Delegate = typed callable reference.",
      "- Lambda = concise syntax for behavior that can become a delegate or expression tree.",
      "- Event separates subscription from the right to publish.",
      "- LINQ composes sequence operations; deferred execution matters for correctness and performance."
    ),
    markdownUk: lines(
      "# Delegates, events, lambdas та LINQ",
      "",
      "Delegate — strongly typed reference на один або кілька compatible methods. `Action` та `Func<...>` — поширені generic delegate types. Lambda expressions дають короткий syntax для створення delegates.",
      "",
      "## Delegate та lambda",
      "",
      "```csharp",
      "Func<int, bool> isFailure = status => status >= 400;",
      "",
      "Console.WriteLine(isFailure(500)); // True",
      "```",
      "",
      "Event побудований на delegate, але контролює, хто може publish його. External code зазвичай subscribe/unsubscribe, а raise event може declaring type.",
      "",
      "## LINQ",
      "",
      "LINQ дає composable operators `Where`, `Select`, `OrderBy`, `Any`, `FirstOrDefault`, `GroupBy`. Багато operators використовують deferred execution: query визначається зараз, але source реально не enumerated до моменту, коли consumer попросить results.",
      "",
      "```csharp",
      "var statuses = new[] { 200, 500, 404, 201 };",
      "",
      "var failures = statuses",
      "    .Where(status => status >= 400)",
      "    .OrderBy(status => status)",
      "    .ToList();",
      "```",
      "",
      "`ToList()` materialize query одразу. Без нього багато LINQ pipelines залишаються deferred і можуть виконатись повторно при наступному enumeration.",
      "",
      "## Ключові моменти",
      "",
      "- Delegate = typed callable reference.",
      "- Lambda = компактний syntax для behavior, який може стати delegate або expression tree.",
      "- Event розділяє subscription та право publish.",
      "- LINQ компонує sequence operations; deferred execution важливий і для correctness, і для performance."
    ),
  },
  {
    id: "csharp-exceptions-disposal",
    label: "Exceptions & resource management",
    labelUk: "Exceptions та керування ресурсами",
    level: "Core",
    description: "try/catch/finally, exception propagation, IDisposable and using.",
    descriptionUk: "try/catch/finally, exception propagation, IDisposable та using.",
    sourceIds: ["csharp-exceptions", "dotnet-gc"],
    markdown: lines(
      "# Exceptions & resource management",
      "",
      "Exceptions represent exceptional failure paths. `try` contains code that may fail, `catch` handles selected exceptions and `finally` runs regardless of success or failure.",
      "",
      "## Handling exceptions",
      "",
      "Catch the most specific exception you can actually handle. A broad `catch (Exception)` that simply ignores the error hides failures. Inside a catch, `throw;` rethrows while preserving the original stack trace; `throw ex;` loses useful stack information.",
      "",
      "```csharp",
      "try",
      "{",
      "    var text = File.ReadAllText(\"settings.txt\");",
      "    Console.WriteLine(text);",
      "}",
      "catch (FileNotFoundException ex)",
      "{",
      "    Console.WriteLine($\"Missing file: {ex.FileName}\");",
      "}",
      "```",
      "",
      "## `IDisposable` and `using`",
      "",
      "The garbage collector manages managed memory, but files, streams and some OS/native resources need deterministic cleanup. Types that own such resources commonly implement `IDisposable`; `using` ensures `Dispose()` is called even if an exception occurs.",
      "",
      "```csharp",
      "using var reader = File.OpenText(\"settings.txt\");",
      "string content = reader.ReadToEnd();",
      "```",
      "",
      "## Key points",
      "",
      "- Exceptions are for exceptional paths, not routine branching.",
      "- Prefer specific catches; do not silently swallow failures.",
      "- GC manages memory; `Dispose`/`using` handles deterministic release of disposable resources."
    ),
    markdownUk: lines(
      "# Exceptions та керування ресурсами",
      "",
      "Exceptions представляють exceptional failure paths. `try` містить code, який може fail, `catch` handle вибрані exceptions, а `finally` виконується незалежно від success/failure.",
      "",
      "## Handling exceptions",
      "",
      "Catch треба робити для найбільш specific exception, який реально можна handle. Широкий `catch (Exception)`, що просто ігнорує error, приховує failure. Усередині catch `throw;` rethrow зберігає original stack trace; `throw ex;` втрачає корисну stack information.",
      "",
      "```csharp",
      "try",
      "{",
      "    var text = File.ReadAllText(\"settings.txt\");",
      "    Console.WriteLine(text);",
      "}",
      "catch (FileNotFoundException ex)",
      "{",
      "    Console.WriteLine($\"Missing file: {ex.FileName}\");",
      "}",
      "```",
      "",
      "## `IDisposable` та `using`",
      "",
      "Garbage collector керує managed memory, але files, streams і деякі OS/native resources потребують deterministic cleanup. Types, що володіють такими ресурсами, часто implement `IDisposable`; `using` гарантує `Dispose()` навіть коли виникає exception.",
      "",
      "```csharp",
      "using var reader = File.OpenText(\"settings.txt\");",
      "string content = reader.ReadToEnd();",
      "```",
      "",
      "## Ключові моменти",
      "",
      "- Exceptions призначені для exceptional paths, а не звичайного branching.",
      "- Краще specific catches; failure не треба silently swallow.",
      "- GC керує memory; `Dispose`/`using` — deterministic release disposable resources."
    ),
  },
  {
    id: "csharp-async",
    label: "async/await, Task & concurrency basics",
    labelUk: "async/await, Task та основи concurrency",
    level: "Core",
    description: "Task-based asynchronous code and the distinction between asynchronous waiting and parallel execution.",
    descriptionUk: "Task-based asynchronous code та різниця між asynchronous waiting і parallel execution.",
    sourceIds: ["csharp-async-docs"],
    markdown: lines(
      "# async/await, Task & concurrency basics",
      "",
      "A `Task` represents an operation that may complete later. Marking a method `async` allows the use of `await`, but `async` does not automatically create a new thread.",
      "",
      "## What `await` changes",
      "",
      "When an awaited operation is incomplete, the async method can return control to its caller rather than blocking until the operation finishes. The method continues later after the task completes. This is particularly useful for I/O such as HTTP, databases and file operations.",
      "",
      "```csharp",
      "static async Task<int> GetStatusAsync(HttpClient client, string url)",
      "{",
      "    using var response = await client.GetAsync(url);",
      "    return (int)response.StatusCode;",
      "}",
      "",
      "using var client = new HttpClient();",
      "int status = await GetStatusAsync(client, \"https://example.com\");",
      "Console.WriteLine(status);",
      "```",
      "",
      "## Async is not parallelism",
      "",
      "Asynchrony is mainly about not blocking while waiting. Parallelism is about executing CPU work simultaneously. An async method can run entirely without parallel execution.",
      "",
      "Prefer `Task` or `Task<T>` as return types for async methods. `async void` is mainly for event handlers because a caller cannot normally await it or observe its exceptions through a returned task.",
      "",
      "## Key points",
      "",
      "- `async` does not automatically mean another thread.",
      "- `await` asynchronously waits for a Task and resumes when it completes.",
      "- `.Result` and `.Wait()` turn asynchronous flows into blocking waits and should not be the default approach.",
      "- Async and parallel are related concurrency concepts, but they solve different problems."
    ),
    markdownUk: lines(
      "# async/await, Task та основи concurrency",
      "",
      "`Task` представляє operation, яка може завершитися пізніше. `async` дозволяє використовувати `await`, але `async` не створює new thread автоматично.",
      "",
      "## Що змінює `await`",
      "",
      "Якщо awaited operation ще не завершена, async method може повернути control caller-у замість blocking до completion. Method продовжиться пізніше після завершення task. Це особливо корисно для I/O: HTTP, database, files.",
      "",
      "```csharp",
      "static async Task<int> GetStatusAsync(HttpClient client, string url)",
      "{",
      "    using var response = await client.GetAsync(url);",
      "    return (int)response.StatusCode;",
      "}",
      "",
      "using var client = new HttpClient();",
      "int status = await GetStatusAsync(client, \"https://example.com\");",
      "Console.WriteLine(status);",
      "```",
      "",
      "## Async — не те саме, що parallelism",
      "",
      "Asynchrony насамперед означає не блокуватися під час waiting. Parallelism означає simultaneous execution CPU work. Async method може працювати взагалі без parallel execution.",
      "",
      "Для async methods краще повертати `Task` або `Task<T>`. `async void` переважно залишають event handlers, тому що caller не може нормально await його або observe exceptions через returned task.",
      "",
      "## Ключові моменти",
      "",
      "- `async` не означає automatic new thread.",
      "- `await` asynchronous waits Task і resume method після completion.",
      "- `.Result` та `.Wait()` перетворюють asynchronous flow на blocking wait і не мають бути default approach.",
      "- Async і parallel — related concurrency concepts, але вирішують різні problems."
    ),
  },
  {
    id: "csharp-runtime-memory",
    label: "Runtime, memory, GC & equality",
    labelUk: "Runtime, пам’ять, GC та equality",
    level: "Core",
    description: "Managed memory, garbage collection, boxing/unboxing, identity and value equality.",
    descriptionUk: "Managed memory, garbage collection, boxing/unboxing, identity та value equality.",
    sourceIds: ["csharp-type-system", "dotnet-gc"],
    markdown: lines(
      "# Runtime, memory, GC & equality",
      "",
      "C# runs on the .NET managed runtime. Understanding object lifetime and value/reference semantics is more useful than memorizing the oversimplified rule that value types are always on the stack and reference types are always on the heap.",
      "",
      "## Garbage collection",
      "",
      "The garbage collector tracks managed object reachability and reclaims objects that are no longer reachable. It uses generations because most objects are short-lived. GC timing is nondeterministic, which is why disposable resources still need `Dispose`/`using`.",
      "",
      "## Boxing and unboxing",
      "",
      "Boxing converts a value type to `object` or an implemented interface, creating a boxed copy represented as a reference-type object. Unboxing extracts the value type again.",
      "",
      "```csharp",
      "int number = 42;",
      "object boxed = number;   // boxing",
      "int copy = (int)boxed;   // unboxing",
      "```",
      "",
      "## Equality",
      "",
      "Reference equality asks whether two references point to the same object. Value equality asks whether their contents should be considered equal. Ordinary classes use reference-oriented equality by default unless they customize it; records provide value equality by default.",
      "",
      "```csharp",
      "var first = new object();",
      "var same = first;",
      "Console.WriteLine(ReferenceEquals(first, same)); // True",
      "",
      "var p1 = new Point(1, 2);",
      "var p2 = new Point(1, 2);",
      "Console.WriteLine(p1 == p2); // True",
      "",
      "public record Point(int X, int Y);",
      "```",
      "",
      "## Key points",
      "",
      "- GC manages managed object memory; it does not replace deterministic disposal.",
      "- Value/reference type is primarily a semantic distinction about copying and identity, not a guaranteed physical storage location.",
      "- Boxing creates a reference-type representation/copy of a value type.",
      "- `==`, `Equals` and `ReferenceEquals` are not universally the same equality operation."
    ),
    markdownUk: lines(
      "# Runtime, пам’ять, GC та equality",
      "",
      "C# працює на .NET managed runtime. Розуміння object lifetime і value/reference semantics корисніше, ніж спрощене правило «value types завжди stack, reference types завжди heap».",
      "",
      "## Garbage collection",
      "",
      "Garbage collector відстежує reachability managed objects і звільняє objects, які більше не reachable. Він використовує generations, тому що більшість objects живуть недовго. GC timing nondeterministic, тому disposable resources все одно потребують `Dispose`/`using`.",
      "",
      "## Boxing та unboxing",
      "",
      "Boxing перетворює value type на `object` або implemented interface, створюючи boxed copy у reference-type representation. Unboxing дістає value type назад.",
      "",
      "```csharp",
      "int number = 42;",
      "object boxed = number;   // boxing",
      "int copy = (int)boxed;   // unboxing",
      "```",
      "",
      "## Equality",
      "",
      "Reference equality питає, чи два references вказують на один object. Value equality питає, чи content двох values треба вважати рівним. Звичайні classes за замовчуванням мають reference-oriented equality, якщо її не customize; records мають value equality by default.",
      "",
      "```csharp",
      "var first = new object();",
      "var same = first;",
      "Console.WriteLine(ReferenceEquals(first, same)); // True",
      "",
      "var p1 = new Point(1, 2);",
      "var p2 = new Point(1, 2);",
      "Console.WriteLine(p1 == p2); // True",
      "",
      "public record Point(int X, int Y);",
      "```",
      "",
      "## Ключові моменти",
      "",
      "- GC керує managed object memory, але не замінює deterministic disposal.",
      "- Value/reference type — насамперед semantic distinction про copying та identity, а не guaranteed physical storage location.",
      "- Boxing створює reference-type representation/copy для value type.",
      "- `==`, `Equals` та `ReferenceEquals` не є універсально однаковими equality operations."
    ),
  },
];

export const csharpCurriculum = {
  title: "C# programming fundamentals",
  titleUk: "Основи програмування на C#",
  description: "A deliberately incomplete C# foundation focused on core language and runtime concepts before frameworks and test automation.",
  taxonomy,
  sources,
};

export default csharpCurriculum;
